// Practice, answers, checklists, glossary and references, in the same block format as content.js.
module.exports = [

['part', 'Practice', 'Exercises in three levels, from single sentences to full texts. The chapter number after each item tells you where to look for help. The answers follow the exercises.'],

['ch', 'Level 1: Sentences'],
['h', 'A. Translate into Arabic (EN → AR)'],
['ol', [
  '_She paid a visit to her grandmother._ (Chapter 4)',
  '_The agreement has remained a dead letter._ (Chapter 6)',
  '_He is a heavy smoker._ (Chapter 3)',
  '_It’s raining cats and dogs._ (Chapter 4)',
  '_The Home Office issued a statement._ (Chapter 9)',
]],
['h', 'B. Translate into English (AR → EN)'],
['ol', [
  '{{رجع بخُفَّي حُنين.}} (Chapter 4)',
  '{{أثلجَ الخبرُ صدري.}} (Chapter 9)',
  '{{هو شجاعٌ مِغوار.}} (Chapter 5)',
  '{{يساورني القلق بشأن النتائج.}} (Chapter 4)',
  '{{قدّم الوزير استقالته أمس.}} (Chapter 5)',
]],
['h', 'C. Each translation has one mistake. Find it and correct it.'],
['ol', [
  '_Pay attention, please._ → {{ادفع الانتباه من فضلك.}} (Chapter 4)',
  '_The government announced new measures._ → {{الحكومة أعلنت إجراءاتٍ جديدة.}} (Chapter 5)',
  '_I have three brothers._ → {{لديّ ثلاث إخوة.}} (Chapter 5)',
  '{{الحياة جميلة.}} → _The life is beautiful._ (Chapter 11)',
  '{{تزوّج منها العام الماضي.}} → _He married from her last year._ (Chapter 11)',
]],

['ch', 'Level 2: Short texts'],
['p', 'For each text: (1) write the brief (client, purpose, audience), (2) translate the text, and (3) write two sentences explaining your main choice.'],
['h', 'Text 2a (EN → AR)'],
['ex', '_All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood._'],
['p', 'Source: Universal Declaration of Human Rights, Article 1 (United Nations, 1948). When you have finished, compare your version with the official Arabic text.'],
['h', 'Text 2b (AR → EN)'],
['ar', 'الخيلُ والليلُ والبيداءُ تعرفني ... والسيفُ والرمحُ والقرطاسُ والقلمُ'],
['p', 'Source: al-Mutanabbi (n.d.). Try to keep the rhythm of the list.'],
['h', 'Text 2c (EN → AR)'],
['ex', '_Shall I compare thee to a summer’s day? Thou art more lovely and more temperate._'],
['p', 'Source: Sonnet 18 (Shakespeare, 1609). Summer or spring? Explain your choice (Chapter 9).'],

['ch', 'Level 3: Full texts'],
['p', 'Work through all the steps, as a professional would: (1) answer the analysis questions in Chapter 2, (2) translate the text, (3) revise it using the checklists in this book, and (4) write a commentary of about 150 words (Chapter 14).'],
['h', 'Text 3a: News (EN → AR)'],
['ex', '_Health officials have urged residents to stay indoors between 11 a.m. and 4 p.m. as temperatures are expected to top 50°C this week. “Heatstroke is not something to take lightly,” a Ministry of Health spokesperson said, advising people to drink plenty of water and to check on elderly neighbours. Meanwhile, shopping malls are expected to be packed as families seek relief from the heat._'],
['p', 'Practice text written for this handbook.'],
['h', 'Text 3b: Cultural news (AR → EN)'],
['ar', 'احتفلت الجمعية الثقافية مساءَ أمس بتكريم نخبةٍ من المترجمين الشباب، وذلك في أمسيةٍ حضرها لفيفٌ من الأدباء والأكاديميين. وأكّد رئيس الجمعية في كلمته أنّ الترجمة جسرٌ يصل الشعوب بعضها ببعض، مشيراً إلى أنّ العناية بالمترجمين الشباب واجبٌ لا ترف. واختُتمت الأمسية بقراءاتٍ شعريةٍ مترجمة، وسط أجواءٍ سادها الودّ والتقدير.'],
['p', 'Practice text written for this handbook.'],

['ch', 'Answers'],
['p', 'These are suggested answers. There is often more than one good translation: any version that is accurate, natural and right for the reader is acceptable.'],
['h', 'Level 1'],
['ol', [
  '{{زارت جدّتها.}} “Pay a visit” simply means “visit”.',
  '{{ظلّت الاتفاقية حبراً على ورق.}} A functional equivalent.',
  '{{يدخّن بشراهة.}} The sentence is rebuilt around a verb.',
  '{{تمطر بغزارة.}} An idiom is never translated word by word.',
  '{{أصدرت وزارة الداخلية البريطانية بياناً.}} The Home Office is the UK interior ministry.',
  '_He came back empty-handed._ The meaning of the proverb, in natural English.',
  '_The news warmed my heart._ Arabic “cold” relief becomes English “warmth”.',
  '_He is very brave._ English does not need two synonyms.',
  '_I am growing worried about the results._ A natural English collocation.',
  '_The minister resigned yesterday._ Start with the subject; {{قدّم استقالته}} means “resigned”.',
  '{{انتبه من فضلك.}} “Pay attention” is a collocation.',
  '{{أعلنت الحكومة إجراءاتٍ جديدة.}} Start with the verb.',
  '{{لديّ ثلاثةُ إخوة.}} With 3 to 10, the number takes the opposite gender.',
  '_Life is beautiful._ No “the” before general ideas.',
  '_He married her last year._ No Arabic preposition in English.',
]],
['h', 'Level 2'],
['p', '**2a.** {{يُولد جميعُ الناس أحراراً ومتساوين في الكرامة والحقوق، وقد وُهبوا العقلَ والضمير، وعليهم أن يعامل بعضُهم بعضاً بروح الإخاء.}} Start with the verb and join the two sentences with {{و}}. Then compare your version with the official United Nations Arabic text.'],
['p', '**2b.** _The horses, the night and the desert know me, as do the sword, the spear, the paper and the pen._ Keep the list of seven nouns. Words such as _steed_ and _parchment_ would give a more classical tone.'],
['p', '**2c.** {{أأشبّهكِ بيومٍ من أيام الربيع؟ أنتِ أبهى منه وأكثرُ اعتدالاً.}} Spring gives Arab readers the pleasant feeling that summer gives English readers.'],
['h', 'Level 3: tips'],
['p', '**3a.** _top 50°C_ → {{تتجاوز 50 درجة مئوية}}; _not something to take lightly_ → {{أمرٌ خطير}} (modulation); _check on_ → {{الاطمئنان على}}; _packed_ → {{مكتظّة}}.'],
['p', '**3b.** A possible opening: _Last night, the Cultural Society honoured a group of outstanding young translators at an evening attended by writers and academics._ Split the long sentence, keep the image of translation as a bridge, and translate {{الودّ والتقدير}} as _a warm, appreciative atmosphere_.'],

['part', 'Checklists', 'Use these checklists with every translation. Tick each point as you go.'],
['ch', 'Before you translate'],
['ul', ['I know the client, the purpose and the audience.', 'I have read the whole text twice.', 'I know the type of text and its tone.', 'I have marked difficult words, idioms, names and numbers.', 'I have made a list of key terms.', 'I have my dictionaries and resources ready.']],
['h', 'While you translate'],
['ul', ['The meaning is the same as in the original.', 'The terms are the same all the way through.', 'The style suits the brief.', 'Collocations and idioms sound natural.', 'Cultural references are handled.']],
['h', 'After you translate'],
['ul', ['Nothing is missing, and nothing has been added.', 'Every “not” is in place.', 'Grammar, spelling and punctuation are correct.', 'Numbers, names, dates and captions are correct.', 'I have read the translation without the original.']],
['h', 'Your commentary'],
['ul', ['For each problem: problem → solution → procedure or strategy → resource → reason.', 'I quote examples from the original and the translation.', 'I write in the third person.']],
];
