// Contributions Report: what was added from each team member's material, what was edited, what was removed and why.
module.exports = [

['h1', '1. Summary'],
['p', 'This report records, for each member of the Translation Team, what was taken into the handbook, what was edited, and what was left out and why. The point-by-point record is in the Appendix: The Team’s Documents.'],
['table', ['Member', 'Material', 'Where it is used'], [
  ['Loulwah Bin Saeed', 'Audiovisual translation notes (Intro to AVT, AVT 2); idiom notes; the suggestion to include dictionaries', 'Chapters 3, 26 and 27'],
  ['Masooma Almesri', 'Terminology slides (182); the terminology material selected from them with Samiuallah Mohammad; idiom list; the idea of an opening chapter of tips', 'Chapters 2, 12, 17 and 21'],
  ['Samiuallah Mohammad', 'First draft; plan and recommendations; 180 course notes; Translation 1 notes; notes on Farghal & Shunnaq; Text Analysis Model; {{الترجمة: ماهيتها وكيفيتها}}; framework and main documents', 'Most chapters from 1 to 25, and the order of the book'],
  ['Shaikhah Alkhaledi', 'Editing and structure; study notes; terminology class notes; framework draft; covers, layout, QR code and website', 'The whole book; her notes in Chapters 1, 4, 6–9, 14, 17, 19, 21, 22 and 26'],
], [20, 50, 30]],

['h1', '2. How the decisions were made'],
['p', 'Every point was judged by the same two questions: does a beginner need this, and is it correct? In practice:'],
['ul', [
  'each idea is explained with an example before it is named, in numbered steps;',
  'each topic appears once, in the chapter where it belongs, even when several members covered it;',
  'anything that could not be checked was left out rather than printed;',
  'examples that took a political or religious position were rewritten or left out;',
  'history and specialist theory were kept to a minimum;',
  'every idea taken from a published work is cited, with the author’s name in brackets only.',
]],

['h1', '3. Samiuallah Mohammad'],
['h2', '3.1 Added to the handbook'],
['ul', [
  '**From the first draft**, rewritten for beginners: the definitions; the differences between English and Arabic (Chapter 4); form and meaning, types of meaning and context (Chapters 5–7); collocation and idioms (Chapters 8–9); equivalence, literal and free translation, metaphor and the strategies (Chapters 10–12 and 14); cultural approximation, descriptive translation and lexical creation (Chapters 15–17); text analysis with the KUNA example (Chapter 18); post-editing (Chapter 22); commentary (Chapter 25); and many exercise items.',
  '**From the plan and recommendations**: the order from easy to hard; the missing strategies and types of translation; the seven procedures; the tips at the start; and the chapters on analysis, commentary, dictionaries, terminology, machine translation, genres, common mistakes and the risk matrix.',
  '**From the 180 notes, Translation 1 notes and Farghal & Shunnaq notes**, which are the sources of the draft: the examples _weak coffee_, _a rough sea_ (Chapter 8) and _to be in the red_ (Chapter 9); and the citation of Farghal & Shunnaq in Chapters 4, 10, 12 and 15–17, in the 2011 edition the team used. The draft’s numbered exercises also come from this book.',
  '**From the Text Analysis Model**: the linguistic and external levels (Chapter 18, Step 3), the use of the analysis in the commentary (Chapter 25), and the model as a quality check (Chapter 18, linked to Chapter 23). Fairclough (2003), on which the model is based, was added to the References.',
  '**From {{الترجمة: ماهيتها وكيفيتها}}**: the idioms _He looks blue_ and _I will go bananas_ (Chapter 9).',
]],
['h2', '3.2 Edited'],
['p', 'Topics repeated in several places were merged, and the empty sections (terminology, machine translation, glossary, references) were written in full. Errors were corrected: the Arabic for “died”; “kick the bucket” (given with an insulting phrase); “mark my words”; “Bush’s puppy” (the press said “poodle”); the rule on Arabic word order; _the cake_ translated as {{التفاحة}}; and _the Home Office_ translated as a minister rather than a ministry. Colloquial Arabic was replaced with formal Arabic.'],
['h2', '3.3 Removed, and why'],
['table', ['Removed', 'Why'], [
  ['Unclear or wrong statements (“Principles = Foundations”, “mule” as a synonym of “horse”, “translation also means to politicize”)', 'They would confuse a beginner.'],
  ['The figure of “74 fields” for the Jordanian academy', 'No source confirms it.'],
  ['A news agency described as biased; a Qur’anic verse given as the equivalent of an English proverb; the Clinton impeachment example', 'Not neutral enough for a club publication.'],
  ['Invented words (tribocracy, puppycracy)', 'Not real English.'],
  ['Some exercise items (_a readable book_, _addled egg_)', 'Left out for space; they can form a later exercise set.'],
  ['The practice section and the answer key at the end', 'The book stays short; each chapter keeps its questions with answers.'],
  ['The abbreviations at the start of the book', 'Moved to the back, next to the glossary, so that the opening pages lead straight into the first lesson.'],
  ['Advanced parts of the Text Analysis Model (blending, frame-modification, re-modelling, Al-ta’reed, monitoring, intrinsic and extrinsic managing)', 'Too advanced for a first handbook.'],
  ['Citing {{الترجمة: ماهيتها وكيفيتها}}', 'No author is named on any page, so it cannot be listed in the References.'],
], [55, 45]],

['h1', '4. Masooma Almesri'],
['h2', '4.1 Added to the handbook'],
['ul', [
  '**From the terminology material selected with Samiuallah Mohammad**, the core of Chapter 21: the definition of terminology; the translator and the terminologist; why terms must be managed; short forms; what makes a good term; the Arabic language academies; how to translate a term; term lists; termbases; one term for one idea.',
  '**From her 182 slides**: {{عقارب الساعة}} and _a throbbing headache_ (Chapter 12); {{الاستمطار}}, {{قطار}}, and affixes such as _manageable_ and _antibiotic_ (Chapter 17); the redundant term {{التطرّف الراديكالي}} and the definition of a terminologist, who sometimes creates terms (Chapter 21).',
  '**Her suggestion** of an opening chapter that prepares students before they start: Chapter 2, “Tips, advice and preparation”.',
]],
['h2', '4.2 Edited'],
['p', 'The chapter was rewritten in plain English and reduced to what a beginner needs. The definition of a terminologist and some historical details were corrected. Sources were added, since the chapter cited none, together with UNTERM, Arabterm, a sample term list and medical examples.'],
['h2', '4.3 Removed, and why'],
['table', ['Removed', 'Why'], [
  ['The history and schools of terminology', 'History is not needed to use terms well.'],
  ['The categories of terms by function, meaning and origin; most of the nine naming rules', 'Too theoretical for beginners; the practical rules are kept.'],
  ['The standardisation bodies (ISO, IEC, ITU) and the academies’ approval procedures', 'Too detailed for a first handbook.'],
  ['The format for citing references', 'It belongs to the References style, not to the text.'],
  ['Most of the idiom list', 'Mostly American slang, and some items concern drinking; the common idioms are already in Chapter 9.'],
], [55, 45]],

['h1', '5. Loulwah Bin Saeed'],
['h2', '5.1 Added to the handbook'],
['ul', [
  '**From her audiovisual translation notes**, the core of Chapters 26 and 27: why the field matters; its main types; dubbing; purpose first (Skopos theory); subtitles; the link between words, images and sound; language variety; cultural references; subtitling strategies; taboo language.',
  '**Her suggestion** to include the dictionaries that helped the team, and how to use them: Chapter 3, “Printed and digital dictionaries”, now placed in Part 1 so that students learn to use a dictionary before anything else.',
]],
['h2', '5.2 Edited'],
['p', 'The two lists of subtitling strategies were merged into one. The spelling of Vermeer, Díaz Cintas and Remael was corrected, and the line length was corrected to about 37 to 39 characters (up to 42 on streaming platforms).'],
['h2', '5.3 Removed, and why'],
['table', ['Removed', 'Why'], [
  ['The history of the field and three of the four theories', 'Theory beyond what a beginner needs.'],
  ['The summary on audiovisual translation in the Arab world; several minor types', 'Kept short so that Part 9 stays practical.'],
  ['The YouTube links', 'Links stop working in a printed book.'],
  ['Her idiom notes', 'Several entries needed correcting (_my cup runneth over_, _rear-view mirror_, _just deserts_) or were incomplete; most equivalents are colloquial.'],
  ['The table of Kuwaiti expressions', 'The handbook uses formal Arabic; the table would suit the website.'],
], [55, 45]],
['p', 'Her other notes were lost, and her Principles of Translation notes did not reach the editor, so Chapters 3, 11, 14 and 22 were written from published sources.'],

['h1', '6. Shaikhah Alkhaledi'],
['p', 'Shaikhah Alkhaledi edited the handbook and coordinated the project. Her work on it was:'],
['ul', [
  '**Framework**: she compiled the first draft of the framework from the four members’ instructions and the team chat.',
  '**Structure**: she planned the 9 parts and 27 chapters in order from easy to hard, and moved the dictionaries chapter into Part 1.',
  '**Writing and editing**: she rewrote every chapter as a guided lesson (Where we are, numbered steps, Try it, Remember, Words to remember, Next), wrote **Start here** for complete beginners and the closing section, **Your journey continues**, and proofread the whole book.',
  '**Her study notes**, used in Chapters 1, 4, 6–9, 14, 17, 19, 21, 22 and 26: for example the three kinds of translation; the verbs _be_, _do_ and _have_; problems with single words; idioms; news headlines and the inverted pyramid; CAT tools and localisation; the Arabic dubbing of _The Simpsons_.',
  '**Her terminology class notes**, extracted by her from the terminology course she took: the practical steps of Chapter 21 (terms of several words; reading about a new field and asking a specialist; checking a term’s parts against its context; confirming an equivalent in an original Arabic text; writing a one-sentence definition; terms with two accepted names).',
  '**Additions from published sources**, where the team’s material had gaps: the seven procedures (Chapter 13); communicative translation (Chapter 11); explicitation and implicitation (Chapter 14); genres (Chapter 19); common mistakes (Chapter 23); the risk matrix (Chapter 24).',
  '**Her framework proposals now in the book**: the translation brief (Chapter 2); the terminology guide (Chapters 17 and 21); genre guidance (Chapter 19); common pitfalls (Chapter 23); the risk matrix (Chapter 24); UNTERM and digital tools (Chapters 21 and 22).',
  '**Design**: the two covers (Midnight and Light), the page layout, the QR code, and the Translation Team’s website.',
  '**The lasting edition**: she reworked the book so that it can be used year after year: nothing in it depends on a date, an event or a product; every chapter ends with the next step; ten “Did you know?” boxes show why translation matters; and the closing section shows students how to keep learning.',
]],
['table', ['Her proposal left out', 'Why'], [
  ['The parallel-texts step (“Intertextual Mapping Protocol”) and the ethics checklist (“Invisible Translator” audit)', 'Kept for a later stage: they need texts and practice that belong on the website.'],
  ['The practice section, the answer key and the checklists', 'Removed by her decision to keep the handbook short.'],
  ['The Practice Arena and the other website features', 'They belong on the website, which carries what changes; the book carries what lasts.'],
], [55, 45]],

['h1', '7. What was removed from the whole handbook, and why'],
['table', ['Removed', 'Why'], [
  ['The practice section and its answer key', 'Too long for a handbook; each chapter ends with questions and answers.'],
  ['The four checklists', 'They repeated the chapter summaries.'],
  ['The note on future editions', 'A printed book cannot keep being updated; the website carries later material.'],
  ['Scholars’ names in the text', 'Easier reading; every idea keeps its citation in brackets.'],
  ['References to the course and the lecturers', 'The handbook is meant to be used on its own.'],
  ['Part descriptions and about a third of the running text', 'Repetition and long explanations made the pages heavy.'],
  ['Examples tied to a date or event', 'So that the book stays valid every year.'],
  ['Placeholders, the empty checklist for the supervisor’s framework, unconfirmed reviewers and the Guild Season', 'Not final or not confirmed.'],
], [42, 58]],

['h1', '8. Assessment'],
['p', 'The team’s documents covered nearly everything the handbook needed. The draft followed the course closely, and the terminology and audiovisual notes were detailed. The work of editing was to correct, shorten and order this material, fill the gaps from published sources, and present it as one guided path for a reader who knows nothing about translation.'],
['p', 'The handbook is ready for a final read by a native Arabic specialist, and for the supervisor’s approval once the points below and in Section 7 of the Final Report are settled.'],

['h1', '9. Still to confirm'],
['redul', [
  'Whether to list the four contributors alphabetically, as the framework agreed, and whether to name the academic supervisor, Abdullah Bezea.',
  'The club’s official name: the handbook says “Guild Professional Club”; the team’s main document says “The Professional English Club: Guild”.',
  'The ten “Did you know?” facts: check each against a reference work before printing.',
  'Whether the material not yet received (Loulwah’s Principles of Translation notes, the Gamal article, Masooma’s Translation Texts, the sample analyses) should go into this edition.',
]],
];
