// Contributions Report: a working report by the editor on how each member's material was used in the draft handbook.
module.exports = [

['h1', '1. About this report'],
['ul', [
  'This is a working report by Shaikhah Alkhaledi, who edited the draft handbook. It explains how each team member’s material was used: what was taken, what was edited, what was left out, and why.',
  'The handbook it describes is a **draft for the team’s review**, not the final version. Every decision below can be discussed and changed.',
  'The report follows the current draft: two editions (Midnight and Light) with the same content, 102 pages, 9 parts and 27 chapters, an opening section (**Start here**) and a closing section (**Your journey continues**).',
  'Members are listed in alphabetical order. Chapter numbers refer to the current draft.',
  'The item-by-item record of every document is in the Appendix: The Team’s Documents.',
]],

['h1', '2. How material was chosen'],
['p', 'Every point was judged by two questions: does a beginner need it, and is it correct? This led to six working rules:'],
['ol', [
  'Each idea is explained with an example before it is named, in numbered steps.',
  'Each topic appears once, in the chapter where it belongs, even when several members covered it. Material that appeared in more than one member’s notes was kept first, as the framework agreed.',
  'Anything that could not be checked was left out rather than printed.',
  'Examples that took a political or religious position were rewritten or left out.',
  'History and specialist theory were kept to a minimum; they are available in other books.',
  'Every idea taken from a published work is cited in brackets, and listed in the References.',
]],

['h1', '3. Where each chapter comes from'],
['p', 'The table shows the main source of each part of the draft, and what else was added to it.'],
['table', ['Section', 'Main source', 'Also added'], [
  ['Start here', 'Written by Shaikhah Alkhaledi', 'The park-sign example; the House of Wisdom; the four steps'],
  ['1 Translation and the translator', 'Samiuallah Mohammad (draft)', 'Shaikhah’s notes: three kinds of translation, the translator as a reader; the Rosetta Stone'],
  ['2 Tips, advice and preparation', 'Masooma Almesri (idea); Samiuallah (draft tips and plan)', 'Shaikhah’s framework: the three questions (client, purpose, audience); a worked first translation'],
  ['3 Printed and digital dictionaries', 'Loulwah Bin Saeed (idea); Samiuallah (plan)', 'Written from published sources; {{كتاب العين}}'],
  ['4 English and Arabic: key differences', 'Samiuallah (draft, 180 and Translation 1 notes)', 'Shaikhah’s notes: _be_, _do_, _have_, the dual, gender of _I_ and _you_; Arabic numerals'],
  ['5 Form and meaning', 'Samiuallah (draft)', '—'],
  ['6 Types of meaning', 'Samiuallah (draft)', 'Shaikhah’s notes: lexical gaps, false equivalents, rare words'],
  ['7 Context', 'Samiuallah (draft)', 'Shaikhah’s notes: {{خط}}; the verb _run_'],
  ['8 Collocation', 'Samiuallah (draft)', 'Shaikhah’s notes: _deliver_; 180 notes: _weak coffee_, _a rough sea_'],
  ['9 Idioms, proverbs and fixed expressions', 'Samiuallah (draft)', 'Shaikhah’s notes: fixed expressions, spotting idioms, five ways to translate them; 180 notes and {{الترجمة: ماهيتها وكيفيتها}}: three idioms'],
  ['10 Equivalence', 'Samiuallah (draft)', 'Citation of Farghal & Shunnaq'],
  ['11 Literal and free translation', 'Samiuallah (draft)', 'Communicative translation (requested in the Teams chat)'],
  ['12 Metaphoric translation', 'Samiuallah (draft)', 'Masooma’s slides: {{عقارب الساعة}}, _a throbbing headache_'],
  ['13 The seven translation procedures', 'Samiuallah (plan); written from published sources', '—'],
  ['14 Translation strategies', 'Samiuallah (draft and Translation 1 notes)', 'Explicitation and implicitation (Teams chat); further strategies; Shaikhah’s notes: Arabic words in English'],
  ['15 Cultural approximation', 'Samiuallah (draft)', 'Citation of Farghal & Shunnaq'],
  ['16 Descriptive translation', 'Samiuallah (draft)', 'Citation of Farghal & Shunnaq'],
  ['17 Lexical creation', 'Samiuallah (draft)', 'Shaikhah’s notes: Arabicisation examples; Masooma’s slides: {{الاستمطار}}, {{قطار}}, affixes; the journey of _coffee_'],
  ['18 Text analysis', 'Samiuallah (draft and Text Analysis Model)', '—'],
  ['19 Text types and genres', 'Samiuallah (plan); Shaikhah (framework)', 'Shaikhah’s notes: news headlines, the inverted pyramid, technical and literary texts'],
  ['20 Words and points of view', 'Samiuallah (plan: the relational model)', 'Written from published sources'],
  ['21 Terminology', 'Masooma and Samiuallah (terminology material from Masooma’s slides)', 'Shaikhah’s terminology class notes: the research steps; Shaikhah’s notes: medical examples; UNTERM, Arabterm, a sample term list; the Damascus academy'],
  ['22 Machine translation and AI', 'Samiuallah (draft: post-editing; plan)', 'Shaikhah’s notes: translation memory, CAT tools, localisation; the 1954 demonstration'],
  ['23 Revision and common mistakes', 'Samiuallah (plan); Shaikhah (framework)', 'Written from published sources'],
  ['24 Interlingual risk assessment', 'Shaikhah (framework)', 'The _Mars Climate Orbiter_'],
  ['25 Translation commentary', 'Samiuallah (draft and Text Analysis Model)', '—'],
  ['26 Introduction to audiovisual translation', 'Loulwah (AVT notes)', 'Shaikhah’s notes: the Arabic dubbing of _The Simpsons_; silent-film intertitles'],
  ['27 Subtitling', 'Loulwah (AVT notes)', 'Subtitle timing, SDH, a five-step method, rules for Arabic subtitles'],
  ['Your journey continues', 'Written by Shaikhah Alkhaledi', '—'],
], [30, 32, 38]],

// ================= LOULWAH =================
['h1', '4. Loulwah Bin Saeed'],
['p', 'Material received: the audiovisual translation notes (Intro to AVT and AVT 2), idiom notes, and her suggestion to include dictionaries. Her Principles of Translation notes, the Gamal article and the AVT Theory file have not yet reached the editor, and her other notes were lost.'],
['h2', '4.1 Taken into the handbook'],
['table', ['What was taken', 'Where it is now'], [
  ['Why audiovisual translation matters, and what makes it different from other translation', 'Chapter 26, Step 1'],
  ['The main types: subtitling, dubbing, voice-over and others', 'Chapter 26, Step 2'],
  ['Dubbing, and dubbing in the Arab world', 'Chapter 26'],
  ['Purpose comes first (Skopos theory)', 'Chapter 26; linked from Chapter 2'],
  ['The challenges of the field', 'Chapter 26'],
  ['Subtitles and their kinds (open and closed)', 'Chapter 27'],
  ['Words, images and sound work together', 'Chapter 27, Step 3'],
  ['Language variety: sociolect, slang, idiolect', 'Chapter 27, Step 3'],
  ['Cultural references and the subtitling strategies for them', 'Chapter 27, Step 4'],
  ['Taboo language and censorship', 'Chapter 27, Step 5'],
  ['The suggestion to include the dictionaries that helped the team and how to use them', 'Chapter 3, now in Part 1'],
], [62, 38]],
['h2', '4.2 Edited'],
['ul', [
  'The two overlapping lists of subtitling strategies were merged into one list of eight.',
  'The spelling of Vermeer, Díaz Cintas and Remael was corrected.',
  '“32 to 41 characters per line” was corrected to about 37 to 39, and up to 42 on streaming platforms.',
  '“Relies 100% on technology” became “depends heavily on technology”.',
  'The description of dubbing in the Arab world was corrected.',
]],
['h2', '4.3 Not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['The history of the field', 'Not needed to start subtitling.'],
  ['Three of the four theories (descriptive translation studies, polysystem theory, reception studies)', 'Beyond a beginner’s level; Skopos theory is kept because it is practical.'],
  ['The summary on audiovisual translation in the Arab world', 'Kept short so that Part 9 stays practical.'],
  ['Minor types (free commentary, in-vision signing, fansubs, surtitles)', 'The list was kept to the main types.'],
  ['The YouTube links', 'Links stop working in a printed book.'],
  ['The quotation on “screen translation”', 'Not needed once the term was explained.'],
  ['The idiom notes', 'Several entries needed correcting (_my cup runneth over_, _rear-view mirror_, _just deserts_) or were incomplete, and most equivalents are colloquial.'],
  ['The table of Kuwaiti expressions (from her framework instructions)', 'The handbook uses formal Arabic; the table would suit the website.'],
], [45, 55]],
['h2', '4.4 Added by the editor to her chapters'],
['p', 'Subtitle display time and spotting, subtitles for the deaf and hard of hearing (SDH), a five-step subtitling method, a worked example of shortening a line, rules for Arabic subtitles, first steps for beginners, and the published sources that support the chapters (Díaz Cintas & Remael; Pedersen; Pérez-González; Gambier; Reiss & Vermeer).'],

// ================= MASOOMA =================
['h1', '5. Masooma Almesri'],
['p', 'Material received: the terminology slides (182), the terminology material selected from them with Samiuallah Mohammad, the TerminologyIdioms document, and her suggestion of an opening chapter of tips. Her Translation Texts document (180 and 386 texts) and her stylistics summary have not yet reached the editor.'],
['h2', '5.1 Taken into the handbook'],
['table', ['What was taken', 'Where it is now'], [
  ['The definition of terminology, and of a term', 'Chapter 21, Step 1'],
  ['The four short forms: initialisms, acronyms, abbreviations, clippings (with the same examples)', 'Chapter 21, Step 1'],
  ['The translator and the terminologist', 'Chapter 21, Step 2'],
  ['The Arabic language academies', 'Chapter 21, Step 2'],
  ['How to translate a term (meaning, origin, equivalent)', 'Chapter 21, Step 3'],
  ['What makes a good term; do not change an accepted term without good reason; avoid redundant terms ({{التطرّف الراديكالي}})', 'Chapter 21, Steps 3 and 5'],
  ['Termbases: what they are and what an entry contains', 'Chapter 21, Step 4'],
  ['Why terms must be managed; one term for one idea', 'Chapter 21, Step 5'],
  ['When dictionaries fail, think like a terminologist; a terminologist sometimes creates terms', 'Chapter 21, Step 3'],
  ['Metaphor in terms: {{عقارب الساعة}}; _a throbbing headache_', 'Chapter 12, Step 3'],
  ['Derivation and new meanings: {{الاستمطار}}, {{قطار}}; affix translation (_manageable_, _antibiotic_)', 'Chapter 17, Step 2'],
  ['The idea of an opening chapter that prepares students before they start', 'Chapter 2'],
], [62, 38]],
['h2', '5.2 Edited'],
['ul', [
  'The chapter was rewritten in plain English and reduced to what a beginner needs.',
  'The definition of a terminologist and some historical details were corrected.',
  'The chapter cited no sources, so sources were added (Cabré, 1999; UNTERM; Arabterm).',
]],
['h2', '5.3 Not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['The history of terminology, its schools and its periods', 'History is not needed to use terms well.'],
  ['Functions, points of view and user groups of terminology', 'Theory beyond a beginner’s level.'],
  ['Categories of terms by function, meaning and origin, and the types of borrowing', 'Too theoretical; the practical categories (short forms) are kept.'],
  ['Most of the nine rules for naming terms', 'The practical rules are kept in one sentence.'],
  ['The standardisation bodies (ISO, IEC, ITU) and types of standards', 'Too specialised for a first handbook.'],
  ['The academies’ detailed approval procedures', 'Too detailed; the academies themselves are kept.'],
  ['Terminography and the fields of a termbase entry', 'Reduced to one sentence on what an entry contains.'],
  ['The format for citing references', 'It belongs to the References style, not to the text.'],
  ['Most of the idiom list', 'Mostly American slang, some about drinking; the common idioms are already in Chapter 9.'],
], [45, 55]],
['h2', '5.4 Added by the editor to her chapter'],
['p', 'UNTERM and Arabterm, a sample term list, medical examples (_allergic_, _allergen_, _contact eczema_), the research steps from Shaikhah Alkhaledi’s terminology class notes (see Section 7), and the Damascus academy and the Coordination Bureau of Arabization in Rabat.'],

// ================= SAMIUALLAH =================
['h1', '6. Samiuallah Mohammad'],
['p', 'Material received: the first draft (Draft_one), the plan and recommendations (Latest updates and thoughts), the 180 course notes (typed and scanned), the Translation 1 notes, the notes on Farghal & Shunnaq, the Text Analysis Model, the text {{الترجمة: ماهيتها وكيفيتها}}, the framework document and the main document.'],
['h2', '6.1 The first draft: taken into the handbook'],
['p', 'The draft had 175 points. 8 were used as written, 148 were used after editing, and 19 were not used. Its 25 headings became the backbone of the handbook:'],
['table', ['Draft heading', 'Where it is now'], [
  ['Definitions and abbreviations', 'Key terms of each chapter; the Abbreviations list'],
  ['Objectives of the book', 'Preface'],
  ['Translation and the translator; qualities of a translator; commissioned and self-initiated translators', 'Chapter 1'],
  ['Tips on how to translate; titles', 'Chapters 2 and 22'],
  ['Arabic vs English', 'Chapter 4'],
  ['Form vs meaning', 'Chapter 5'],
  ['Types of meaning; sentence vs speaker meaning', 'Chapter 6'],
  ['Context; homonymy and polysemy', 'Chapter 7'],
  ['Collocation', 'Chapter 8'],
  ['Idioms', 'Chapter 9'],
  ['Equivalence', 'Chapter 10'],
  ['Literal and free translation', 'Chapter 11'],
  ['Metaphoric translation', 'Chapter 12'],
  ['Translation strategies (two headings)', 'Chapter 14, with part in Chapter 17'],
  ['Cultural approximation', 'Chapter 15'],
  ['Descriptive translation', 'Chapter 16'],
  ['Lexical creation', 'Chapter 17'],
  ['Analysing a text (with the KUNA example)', 'Chapter 18'],
  ['Post-editing', 'Chapter 22'],
  ['Commentary on translation', 'Chapter 25'],
  ['Terminology; AI and machine translation; glossary; references (empty headings)', 'Written in full: Chapters 21 and 22, the Glossary and the References'],
], [55, 45]],
['h2', '6.2 The first draft: edited'],
['ul', [
  'Every section was rewritten as guided steps, and topics repeated in several places were merged.',
  '“Died” had the Arabic for “killed”: corrected.',
  '“Kick the bucket” was given with an insulting phrase ({{يموت كالحقير}}): it is now used to show that the idiom is informal and humorous, not insulting (Chapter 6).',
  'A line said form is more important than meaning: reversed, since meaning comes first.',
  '“Bush’s puppy”: the press said “poodle”.',
  '“Mark my words” was translated as a promise: corrected to {{تذكّر كلامي}}.',
  'The rule that Arabic always starts with the verb: corrected (Arabic often starts with the verb, but not always).',
  'The Arabic equivalent of “is”: corrected.',
  '_Sam ate the cake_ had been translated with “the apple” ({{التفاحة}}): corrected.',
  '_The Home Office_ had been translated as a minister ({{وزير}}): corrected to a ministry ({{وزارة}}).',
  'Some “idiom” examples were really collocations: moved to Chapter 8.',
  'Colloquial Egyptian expressions were replaced with formal ones, and examples that took a political or religious position were rewritten to stay neutral.',
]],
['h2', '6.3 The first draft: not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['“Principles = Foundations”', 'Its meaning is unclear.'],
  ['“Arabic is compositional (derivational), English is compounding”', 'An oversimplification: both languages use derivation and compounding.'],
  ['“Translation also means to politicize (الدبلوماسية)”', 'The wrong word, and not a definition of translation.'],
  ['The communication model (sender, receiver, channel, noise)', 'Theory; the idea is kept in simple words.'],
  ['“Why is meaning complex? Because it is cognitive”', 'Theory a beginner cannot use.'],
  ['“Died = {{استشهد}}” as connotation', 'A religious and political word; replaced by {{تُوُفِّي}}.'],
  ['“Mule” as a synonym of “horse”', 'A mule is a different animal.'],
  ['_Kill_ vs _assassinated_', 'They differ in denotation, so they do not illustrate connotation.'],
  ['“Most of the time, literal translation fails”', 'The book shows many successful literal translations.'],
  ['“Kick the chair = انتحر”', 'Not an established English idiom.'],
  ['_She is a snake_ → {{إنها كالثعلب}}', 'Changes the image and contradicts the line before it.'],
  ['{{أول الغيث قطرة}} for “the tip of the iceberg”', 'It means that big things start small.'],
  ['The “74 fields” of the Jordanian academy', 'No source confirms the figure.'],
  ['“Death is the great leveller = كل نفس ذائقة الموت”', 'A Qur’anic verse should not be used as a translation equivalent.'],
  ['Colloquial register (“اتق الله يا شيخ”, “وحدوا الله”)', 'Not suitable for a general handbook.'],
  ['Zakat as “an Islamic taxation system”', 'Factually wrong: zakat is on wealth, not income.'],
  ['_Valentine’s Day_ = {{عيد الحب}} as a calque', 'It is not a loan translation.'],
  ['Invented words (tribocracy, dictatocracy, puppycracy, patriocracy)', 'Not established English words.'],
  ['“KUNA has biased views”', 'A handbook should not describe a named organisation this way.'],
  ['The Clinton impeachment examples', 'A political scandal involving a named person.'],
  ['Religious legal terms ({{الاستتابة}}, {{الخلوة الشرعية}}), Yin-Yang, _psychology_ vs _psychiatry_', 'They belong to other fields; left out for space.'],
  ['Some exercise items (_a readable book_, _a conceivable resolution_, _addled egg_, _Every Jack has his Jill_)', 'Left out for space; they could form an exercise set on the website.'],
], [45, 55]],
['h2', '6.4 The plan and recommendations'],
['p', 'The plan contained 38 requests once repeated ones are merged.'],
['table', ['Request', 'Status', 'Where it is now'], [
  ['Organise the material and remove repetition', 'Done', 'Whole book'],
  ['Add missing strategies and types of translation', 'Done', 'Chapters 1, 11, 14, 26'],
  ['A chapter on the seven procedures', 'Done', 'Chapter 13'],
  ['Define key concepts in every chapter', 'Done', 'Words to remember, every chapter'],
  ['A glossary of all terms', 'Partly done', 'Glossary of 113 terms; some terms used only in the text are not in it'],
  ['Chapters on machine translation, text analysis, commentary, dictionaries, terminology', 'Done', 'Chapters 22, 18, 25, 3, 21'],
  ['Tips and preparation at the beginning', 'Done', 'Chapter 2 and Start here'],
  ['The three questions: client, purpose, audience', 'Done', 'Chapter 2'],
  ['The main genres with examples; poetry examples', 'Done', 'Chapters 15 and 19'],
  ['An interlingual risk assessment matrix', 'Done', 'Chapter 24'],
  ['Common mistakes; an answer key with explanations', 'Done', 'Chapter 23; Try it in every chapter'],
  ['News texts as authentic material', 'Partly done', 'Chapters 2, 18 and 19 (headlines and a short report)'],
  ['Fairclough’s relational model', 'Partly done', 'Chapter 20, as three practical questions'],
  ['Collect examples from books, poetry, proverbs and idioms', 'Partly done', 'Chapters 9, 12, 15, 19'],
  ['A final practice section at three levels; checklists; a note on future editions and the Arabic version', 'Done, then removed', 'Removed to keep the handbook short; see Section 8'],
  ['Examples from “the book”', 'Not done', 'The book is not yet published'],
  ['Sentences from the Analysis and 386 texts', 'Not done', 'Not yet received'],
  ['Checklists based on the supervisor’s framework', 'Not done', 'The framework was not received'],
  ['References for the 180, 182 and other course materials', 'Partly done', 'Course materials cited as the Translation Team’s notes'],
], [44, 16, 40]],
['h2', '6.5 His course notes, the Text Analysis Model and {{الترجمة: ماهيتها وكيفيتها}}'],
['ul', [
  '**The 180 notes, the Translation 1 notes and the Farghal & Shunnaq notes** turned out to be the sources of the draft, so almost all of their content was already in the handbook. Added from them: _weak coffee_ and _a rough sea_ (Chapter 8); _to be in the red_ (Chapter 9); the citation of Farghal & Shunnaq in Chapters 4, 10, 12 and 15–17, in the 2011 edition the team used. The draft’s numbered exercises come from this book.',
  '**The Text Analysis Model** is used in full, in simpler words: the three steps (analysis, translation, commentary); the linguistic level, with its micro level (words, grammar, meaning, word forms, sound) and macro level (the text, other texts, point of view); and the external level (background, author, audience). It is in Chapter 18, Step 3, with its use in the commentary (Chapter 25) and as a quality check (Chapter 23). Fairclough (2003), on which it is based, was added to the References. Not taken: blending, clippings, infixation, frame-modification, re-modelling, Al-ta’reed, monitoring, and intrinsic and extrinsic managing, which are too advanced.',
  '**{{الترجمة: ماهيتها وكيفيتها}}**: two idioms were taken (_He looks blue_, _I will go bananas_; Chapter 9). The rest was not quoted, because no author is named on any page and the text cannot be cited. Two of its examples needed correcting: “She is in the clouds” (the English idiom is “her head is in the clouds”) and {{مهّد الطريق}} for “break the ice”.',
  '**His framework instructions**: the principles-then-examples pattern, simple language for beginners, and citation rules are followed throughout. The outline is the contents page. The abbreviations are at the back rather than the front, and the answer key is inside each chapter rather than at the end (see Section 8).',
]],

// ================= SHAIKHAH =================
['h1', '7. Shaikhah Alkhaledi'],
['p', 'Shaikhah Alkhaledi edited the handbook and coordinated the project. Her contribution:'],
['table', ['Contribution', 'Where it is now'], [
  ['Compiled the first draft of the framework from the four members’ instructions and the team chat', 'Framework document'],
  ['Planned the structure: 9 parts and 27 chapters from easy to hard; moved the dictionaries chapter into Part 1', 'Contents'],
  ['Rewrote every chapter as a guided lesson (Where we are, numbered steps, Try it, Remember, Words to remember, Next) and proofread the whole book', 'Every chapter'],
  ['Wrote the opening, Start here, and the closing section, Your journey continues', 'Front and end of the book'],
  ['Study notes: the three kinds of translation; the translator as a reader', 'Chapter 1'],
  ['Study notes: _be_, _do_ and _have_; the dual; the gender of _I_ and _you_', 'Chapter 4'],
  ['Study notes: lexical gaps ({{ثكلى}}), false equivalents, rare words', 'Chapter 6'],
  ['Study notes: {{خط}}, a word with several meanings', 'Chapter 7'],
  ['Study notes: one verb, many partners (_deliver a letter, a speech, a verdict_)', 'Chapter 8'],
  ['Study notes: fixed expressions; how to spot an idiom; five ways to translate one; three more idioms', 'Chapter 9'],
  ['Study notes: Arabic words borrowed into English (_algebra, algorithm_)', 'Chapter 14'],
  ['Study notes: Arabicisation ({{استراتيجية}}, {{تكنولوجيا}})', 'Chapter 17'],
  ['Study notes: news headlines, the inverted pyramid, hard and soft news, technical and literary texts', 'Chapter 19'],
  ['Study notes: medical terms (_allergic, allergen, contact eczema_)', 'Chapter 21'],
  ['Study notes: translation memory, termbases, CAT tools, the development of machine translation, localisation', 'Chapter 22'],
  ['Study notes: the Arabic dubbing of _The Simpsons_', 'Chapter 26'],
  ['Terminology class notes, extracted by her from the terminology course she took: terms of several words; reading about a new field and asking a specialist; checking a term’s parts against its context; confirming an equivalent in an original Arabic text; one-sentence definitions; terms with two accepted names', 'Chapter 21, Steps 1 and 3–5'],
  ['Framework proposals: the translation brief; the terminology guide; genre guidance; common pitfalls; the risk matrix; UNTERM and digital tools', 'Chapters 2, 17, 19, 21, 22, 23, 24'],
  ['Added from published sources where the team’s material had gaps: the seven procedures; communicative translation; explicitation and implicitation; genres; dictionaries; common mistakes', 'Chapters 3, 11, 13, 14, 19, 23'],
  ['Ten “Did you know?” boxes and a “Next” line at the end of every chapter', 'Chapters 1–4, 7, 17, 21, 22, 24, 26; every chapter'],
  ['Removed everything tied to a date, an event or a product, so that the book can be used every year', 'Whole book'],
  ['Designed the two covers (Midnight and Light), the page layout and the QR code; designed and developed the Translation Team’s website', 'Covers; inside pages; website'],
], [62, 38]],
['h2', '7.1 Her proposals not taken, and why'],
['table', ['Not taken', 'Why'], [
  ['The parallel-texts step (“Intertextual Mapping Protocol”) and the ethics checklist (“Invisible Translator” audit)', 'They need texts and practice; they suit the website or a later edition. Parallel texts are mentioned in Your journey continues.'],
  ['“Dynamic Syntactic Restructuring” as a separate module', 'Partly covered by word order and verb-first sentences in Chapter 4.'],
  ['The practice section, answer key and checklists', 'Written, then removed to keep the handbook short.'],
  ['The website’s Practice Arena and other features', 'They belong on the website, which carries what changes; the book carries what lasts.'],
], [45, 55]],

// ================= WHOLE BOOK =================
['h1', '8. Removed from the whole draft, and why'],
['table', ['Removed', 'Why'], [
  ['The practice section at three levels and its answer key', 'Too long for a handbook; each chapter keeps its Try it questions with answers.'],
  ['The four checklists at the end', 'They repeated the chapter summaries.'],
  ['The note on future editions and the Arabic version', 'A printed book cannot keep being updated; the website carries later material.'],
  ['Scholars’ names in the running text', 'Easier reading; every idea keeps its citation in brackets.'],
  ['References to the courses and the lecturers', 'The handbook is meant to be used on its own.'],
  ['Part descriptions and about a third of the running text', 'Repetition and long explanations made the pages heavy.'],
  ['Examples tied to a date or event', 'So that the book stays valid every year.'],
  ['Placeholders, unconfirmed reviewers’ names and mentions of the Guild Season', 'Not final or not confirmed.'],
], [42, 58]],

['h1', '9. Still open for the team'],
['p', 'Because this is a draft, the following need the team’s decision:'],
['redul', [
  'The order and titles on the Contributors page: the framework agreed that all four names appear equally.',
  'Whether to name the academic supervisor, Abdullah Bezea, in the handbook.',
  'The club’s official name: the draft says “Guild Professional Club”; the team’s main document says “The Professional English Club: Guild”.',
  'Whether the material not yet received should go into this edition: Loulwah’s Principles of Translation notes, the Gamal article and AVT Theory; Masooma’s Translation Texts and stylistics summary; the three sample analyses.',
  'The page size: B5 now; A5 was the size of the model book.',
  'Before printing: a full read by a native Arabic specialist; checking the ten Did you know? facts and the open reference points listed in the Final Report.',
]],
];
