// Handbook content as simple blocks. Inline marks: **bold**, _italic_, {{Arabic}}.
// Blocks: ['part', title, intro], ['ch', title], ['h', title], ['p', text], ['ol', [..]], ['ul', [..]],
//         ['ar', arabicParagraph], ['ex', text] (indented example line), ['try', [questions], [answers]]
module.exports = [

['front', 'How to use this handbook'],
['p', 'This handbook is for complete beginners. You do not need to know anything about translation to use it. It takes you, step by step, from your first sentence to a finished translation between English and Arabic.'],
['p', 'The chapters follow the order in which translators actually work:'],
['ol', [
  '**Get ready**: find out what the translation is for, and read the text carefully (Part 1).',
  '**Understand the text**: work out what it really means (Part 2).',
  '**Translate**: write your translation, using practical techniques (Part 3).',
  '**Check and explain**: correct your work and explain your choices (Part 4).',
]],
['p', 'Part 5 shows you where to go next. At the end of the book you will find exercises with answers, checklists, a glossary of all the key terms and the list of references.'],
['h', 'How to read each chapter'],
['p', 'Read the chapters in order. Each chapter explains one step in plain words and gives examples in both languages. Most chapters end with a short “Try it” exercise, followed by the answers so that you can check yourself.'],
['h', 'Signs used in this book'],
['ul', [
  '**EN → AR** means translating from English into Arabic. **AR → EN** means translating from Arabic into English.',
  'Words in **bold** are key terms. You will find all of them in the glossary.',
]],
['h', 'Sources'],
['p', 'The ideas in this handbook come from published works on translation. They are cited in the text, for example (Newmark, 1988), and listed in full in the References at the end of the book. Unless another source is given, the examples come from the Translation Team’s course materials (Translation Team, n.d.) or were written for this handbook.'],

// ================= PART 1 =================
['part', 'Part 1: Getting started', 'What translation is, and how to prepare before you translate.'],

['ch', 'Chapter 1: What is translation?'],
['p', 'Imagine a friend who only speaks Arabic asks you what an English sign says. You would not read the English words out one by one. You would tell your friend what the sign **means**, in good Arabic. That is translation.'],
['h', 'Meaning, not words'],
['p', 'Translation means carrying the meaning of a text from one language into another. Peter Newmark describes it as “rendering the meaning of a text into another language in the way that the author intended the text” (Newmark, 1988, p. 5).'],
['p', 'Beginners often replace each word with a word from the dictionary. This rarely works, because words in two languages do not match one to one. For example, English speakers say _Break a leg!_ to wish someone good luck:'],
['ex', 'Word by word: {{اكسر ساقاً!}}  ✗'],
['ex', 'By meaning: {{بالتوفيق!}}  ✓'],
['p', 'The word-by-word version sounds like a threat. The second version carries the real meaning.'],
['h', 'No perfect match'],
['p', 'No two languages divide the world in exactly the same way, so a translation can never be an exact copy. Your job is to get as close as possible to the original meaning. The writer Umberto Eco gave his book on translation the title _Dire quasi la stessa cosa_, “saying almost the same thing” (Eco, 2003).'],
['h', 'Four words you will meet'],
['ul', [
  '**Source text** ({{النص المصدر}}): the original text that you translate.',
  '**Target text** ({{النص الهدف}}): your translation.',
  '**Source language** ({{اللغة المصدر}}): the language of the original.',
  '**Target language** ({{اللغة الهدف}}): the language you translate into.',
]],
['p', 'Translating a written text is called **translation** ({{الترجمة التحريرية}}). Translating speech is called **interpreting** ({{الترجمة الشفهية}}). Roman Jakobson calls translation between two languages “interlingual translation” (Jakobson, 1959). This handbook is about written translation.'],
['h', 'What makes a good translator?'],
['p', 'You need more than two languages. A good translator has:'],
['ul', [
  '**Two languages**: you are fluent in both.',
  '**Two cultures**: knowing the culture is as important as knowing the language.',
  '**General knowledge**: texts can be about anything, so keep learning about the world.',
  '**A rich vocabulary** ({{الحصيلة اللغوية}}), including idioms and fixed expressions.',
  '**Practice**: your skill grows with every text you translate and revise.',
]],
['p', 'More than a thousand years ago, the Arab writer al-Jāḥiẓ made the same point: a translator should know the language he translates from and the language he translates into equally well (al-Jāḥiẓ, n.d.):'],
['ar', 'ولا بدَّ للتَّرجُمانِ من أن يكونَ بيانُه في نفسِ الترجمةِ في وزنِ علمِه في نفسِ المعرفة، وينبغي أن يكونَ أعلمَ الناسِ باللغةِ المنقولةِ والمنقولِ إليها، حتى يكونَ فيهما سواءً وغاية.'],
['h', 'Two ways of working'],
['p', 'Most translators are **commissioned** ({{مترجم بتكليف}}): a client asks them to translate a text, and they follow the client’s wishes. A freelancer, who works for different clients, is a commissioned translator. Other translators are **self-initiated** ({{مترجم بمبادرة ذاتية}}): they choose a text themselves, such as a poem they love.'],
['h', 'Your first translation, step by step'],
['p', 'Here is the whole process on one short sentence. Each step is explained in a later chapter.'],
['ex', '_It’s raining cats and dogs, so the match has been cancelled._'],
['ol', [
  '**Get ready** (Chapter 2). A school wants to tell Arabic-speaking parents about the match. The purpose is to inform, so the Arabic should be clear and simple.',
  '**Understand** (Chapters 3 and 4). _Raining cats and dogs_ is an idiom. It has nothing to do with animals: it means “raining heavily”.',
  '**Translate** (Chapters 5 to 10). A word-by-word version, {{إنها تمطر قططاً وكلاباً، لذلك تمّ إلغاء المباراة.}}, makes no sense. A translation of the meaning works: {{أُلغيت المباراة بسبب الأمطار الغزيرة.}}',
  '**Check** (Chapters 11 and 12). Read the Arabic without the English. The meaning is complete, and the sentence sounds natural.',
  '**Explain** (Chapter 14). “The idiom was translated by its meaning, because a word-for-word version would make no sense to Arab readers.”',
]],

['ch', 'Chapter 2: Before you translate'],
['p', 'The same text can be translated in different ways. A news report for experts and a leaflet for children need different words. So before you translate a single word, find out what the translation is for, and read the text carefully.'],
['h', 'Ask three questions'],
['p', 'Christiane Nord explains that the purpose of a translation decides how it should be translated (Nord, 1997). Before you start, ask:'],
['ol', [
  '**Who is the client?** ({{من هو العميل؟}}) The person or organisation asking for the translation. Clients often have their own style and rules.',
  '**What is the purpose?** ({{ما الغرض؟}}) To inform, to persuade, to instruct or to entertain?',
  '**Who will read it?** ({{من هو الجمهور؟}}) Experts or the general public? Adults or children?',
]],
['p', 'The answers are your **translation brief** ({{موجز الترجمة}}). If nobody gives you a brief, ask the client. If you chose the text yourself, answer the questions yourself.'],
['p', 'For example, you are asked to translate a short news report for KUNA, the Kuwait News Agency. Its purpose is to inform English readers who are interested in Kuwait. So your translation should be formal and neutral, with a short headline.'],
['h', 'Read the text twice'],
['ol', [
  'Read the whole text once, just to understand it.',
  'Read it again with a pen. Mark difficult words, idioms, names and numbers.',
  'Research the topic if you do not know it well.',
  'Make a list of the key terms (Chapter 10).',
]],
['h', 'Analyse the text'],
['p', 'Studying a text before you translate it is called **text analysis** ({{تحليل النص}}) (Nord, 2005). An analysis is not a summary. A summary says what a text is about; an analysis describes who wrote it, for whom, why and how. Newmark gives the same advice: begin “by reading the original for two purposes: first, to understand what it is about; second, to analyse it from a ‘translator’s’ point of view” (Newmark, 1988, p. 11). Answer these questions for every new text:'],
['ol', [
  'What type of text is it: a news report, a contract, a poem, an advert?',
  'What is it about: politics, health, law?',
  'What is the tone: neutral, critical, friendly?',
  'Which words and names must I check?',
  'Are there any cultural references?',
  'What will be difficult, and which dictionaries or resources will I need?',
]],
['try', ['A hospital asks you to translate a medicine leaflet for its patients. Who will read it, and what style should you use?', 'What is the purpose of an advert?'],
        ['Patients from the general public, so the style must be clear and simple, with exact words.', 'To persuade.']],

// ================= PART 2 =================
['part', 'Part 2: Understanding the text', 'You cannot translate what you do not understand. This part shows you how to find what a text really means.'],

['ch', 'Chapter 3: Finding the real meaning'],
['p', 'Many words have more than one meaning, and words with the same meaning can carry different feelings. If you always take the first meaning in the dictionary, you will often choose the wrong one.'],
['h', 'Let the context decide'],
['p', 'The words and the situation around a word are its **context** ({{السياق}}). The context tells you which meaning is correct. As the Arabic saying goes, {{لكلّ مقامٍ مقال}}.'],
['ul', [
  '_bank_: {{مصرف}} (for money) or {{ضفّة النهر}} (of a river).',
  '{{عين}}: an eye, a water spring or a spy.',
  '_case_: {{قضية}} (in court), {{حالة}} (in medicine) or {{علبة}} (a box).',
]],
['h', 'Check the feeling'],
['p', 'Some words share the same dictionary meaning, their **denotation** ({{المعنى المعجمي}}), but carry a different feeling, their **connotation** ({{المعنى الإيحائي}}) (Baker, 2018). Choose the word with the right feeling:'],
['ul', [
  '_die_ ({{مات}}) is neutral; _pass away_ ({{توفّي}}) is respectful.',
  '_kill_ ({{قتل}}) is general; _assassinate_ ({{اغتال}}) is political.',
]],
['h', 'Find what the speaker means'],
['p', 'Sometimes a speaker means more than the words say. _It’s freezing in here_ may really mean “Please close the window”, and {{أشعرُ بالحرّ}} may really mean “Please turn on the air conditioning”. Translate what the speaker means.'],
['h', 'Keep the meaning, change the form'],
['p', 'You may change the shape of a sentence, but never its meaning. _He is a heavy smoker_ becomes {{يدخّن بشراهة}}: the Arabic is built around a verb, and the meaning stays the same.'],
['p', 'In the same way, _Blair, Bush’s poodle_ describes Blair as someone who obediently follows Bush. The image of a poodle has no such meaning in Arabic, so the translator keeps the idea: {{بلير، تابعُ بوش}}. As Nida and Taber put it, “anything that can be said in one language can be said in another, unless the form is an essential element of the message” (Nida & Taber, 1969, p. 4).'],
['try', ['Translate _case_ in “The doctor examined the case.”', 'You are translating an obituary. Which word is better: {{مات}} or {{توفّي}}?'],
        ['{{حالة}}.', '{{توفّي}}, because it is respectful.']],

['ch', 'Chapter 4: Word partners, idioms and proverbs'],
['p', 'Some groups of words cannot be translated one word at a time. If you try, the result sounds strange or means something else. This chapter shows you how to recognise them.'],
['h', 'Word partners (collocations)'],
['p', 'A **collocation** ({{التلازم اللفظي}}) is a group of words that naturally go together (Baker, 2018). The linguist J. R. Firth summed this up: “You shall know a word by the company it keeps” (Firth, 1957, p. 11). Each language has its own partners:'],
['ul', [
  '_pay attention_ → {{ينتبه}} (not {{يدفع الانتباه}})',
  '_pay a visit_ → {{يقوم بزيارة}}',
  '_strong tea_ → {{شاي ثقيل}} (not {{شاي قوي}})',
  '_a fast colour_ → {{لون ثابت}} (not {{لون سريع}})',
  '{{قدّم استقالته}} → _he resigned_',
  '{{اتّخذ قراراً}} → _he made a decision_',
  '{{عقد اجتماعاً}} → _he held a meeting_',
]],
['h', 'Idioms'],
['p', 'An **idiom** ({{التعبير الاصطلاحي}}) is a fixed expression whose meaning you cannot guess from its words. Translate its meaning, or use an Arabic idiom with the same meaning:'],
['ul', [
  '_It’s raining cats and dogs._ → {{تمطر بغزارة}}',
  '_over the moon_ → {{يطير من الفرح}}',
  '_to spill the beans_ → {{أفشى السرّ}}',
  '_I’m all ears._ → {{كلّي آذانٌ صاغية}}',
]],
['h', 'Proverbs'],
['p', 'For a **proverb** ({{المثل}}), look for a proverb with the same meaning in the other language. If there is none, give the meaning in plain words:'],
['ul', [
  '{{كالمستجير من الرمضاء بالنار}} → _out of the frying pan into the fire_',
  '{{رجع بخُفَّي حُنين}} → _he came back empty-handed_',
  '{{عصفورٌ في اليد خيرٌ من عشرةٍ على الشجرة}} → _a bird in the hand is worth two in the bush_',
]],
['h', 'A simple test'],
['p', 'If a phrase sounds strange when you translate it word by word, it is probably a collocation or an idiom. But check first: sometimes the words really are meant literally. For many more Arabic–English examples, see Ghazala (2008).'],
['try', ['Translate: _heavy rain_', 'Translate: _a close friend_'],
        ['{{مطر غزير}} (not {{مطر ثقيل}}).', '{{صديق مقرّب}}.']],

// ================= PART 3 =================
['part', 'Part 3: Translating', 'Now you write. These chapters give you practical techniques for the problems every translator meets.'],

['ch', 'Chapter 5: Building English and Arabic sentences'],
['p', 'English and Arabic build sentences differently. If you keep the English order in Arabic, or the Arabic order in English, your translation will sound “translated” (Farghal & Shunnaq, 1999).'],
['h', 'From English into Arabic'],
['ol', [
  '**Start with the verb.** _The government announced new measures_ → {{أعلنت الحكومة إجراءاتٍ جديدة}}.',
  '**Join short sentences** with {{و}}, {{ف}} or {{ثمّ}}, or with linking words such as {{غير أنّ}} (however), {{لذلك}} (therefore) and {{بالإضافة إلى ذلك}} (in addition).',
  '**Use Arabic punctuation**: {{،}} and {{؛}} and {{؟}}.',
  '**Watch gender.** English _you_ is {{أنتَ}} or {{أنتِ}} in Arabic. With the numbers 3 to 10, the number takes the opposite gender to the noun: {{ثلاثةُ طلاب}} but {{ثلاثُ طالبات}}.',
]],
['p', 'Roman Jakobson observed that “languages differ essentially in what they must convey and not in what they may convey” (Jakobson, 1959, p. 236). Arabic, for example, must show whether “you” is a man or a woman; English does not have to.'],
['p', 'Example: _Translation is a fascinating field. Many students choose it._ The Arabic starts with a verb and joins the two sentences with {{و}}:'],
['ar', 'تُعدّ الترجمة مجالاً شائقاً، ويختاره كثيرٌ من الطلاب.'],
['h', 'From Arabic into English'],
['ol', [
  '**Start with the subject.** {{قدّم الوزير استقالته}} → _The minister resigned._',
  '**Split long sentences** with full stops.',
  '**Keep one of two synonyms.** Arabic often uses two words for emphasis: {{شجاعٌ مِغوار}} → _very brave_. Leaving out repeated words like this is called **omission** ({{الحذف}}).',
  '**Add “is” or “are”**, which Arabic often leaves out: {{الطالب في المكتبة}} → _The student is in the library._',
  '**Use capital letters** for names and titles: _the Minister of Health_.',
]],
['h', 'Which Arabic?'],
['p', 'Write in **Modern Standard Arabic** ({{الفصحى المعاصرة}}), the Arabic of newspapers, laws and education. Use a dialect only if the client asks for it, for example in film subtitles.'],
['try', ['Rewrite in natural Arabic: {{الطلاب حضروا المحاضرة.}}', 'Translate: {{الكتاب على الطاولة.}}'],
        ['{{حضر الطلابُ المحاضرة.}}', '_The book is on the table._']],

['ch', 'Chapter 6: How close to stay'],
['p', 'Every translator must decide how close to stay to the original words. Stay too close, and the translation sounds strange. Move too far, and you may change the message. Most good translations are somewhere in between.'],
['h', 'Literal and free translation'],
['p', '**Literal translation** ({{الترجمة الحرفية}}) keeps the original words and changes only what the grammar requires. **Free translation** ({{الترجمة الحرّة}}) keeps the message but not the form (Newmark, 1988).'],
['p', 'Literal translation is sometimes right: _The book is on the table_ → {{الكتاب على الطاولة}}; _to play a role_ → {{يلعب دوراً}}. But sometimes it is wrong: _a long day_ is not {{يوم طويل}} but {{يوم شاقّ}} (a tiring day).'],
['p', 'Free translation must not become invention. _We have had heavy rainfall this winter_ should not become {{سيكون لدينا موسم زراعي مبشّر}} (“we will have a promising farming season”), because that adds a new idea.'],
['h', 'Three kinds of equivalence'],
['p', 'An **equivalent** ({{المكافئ}}) is an expression in the target language that matches the original. Farghal and Shunnaq (1999) describe three kinds. Look at this sentence: _The agreement has remained a dead letter since then._ A “dead letter” is an agreement that exists on paper but is never applied.'],
['ol', [
  '**Formal equivalence** ({{التكافؤ الشكلي}}) keeps the words and the image: {{ظلّت الاتفاقية حرفاً ميتاً منذ ذلك الحين}}. The words are correct, but Arab readers will not understand the image.',
  '**Functional equivalence** ({{التكافؤ الوظيفي}}) uses a different expression that does the same job: {{ظلّت الاتفاقية حبراً على ورق منذ ذلك الحين}}. This familiar Arabic idiom is the best choice here.',
  '**Ideational equivalence** ({{التكافؤ الفكري}}) gives only the basic idea: {{لم تُطبَّق الاتفاقية منذ ذلك الحين}}. It is clear, but the colour of the idiom is lost.',
]],
['p', 'So try the close translation first. If it does not work, look for an expression that does the same job. If there is none, give the plain idea. Nida and Taber describe the goal as “the closest natural equivalent of the source-language message, first in terms of meaning and secondly in terms of style” (Nida & Taber, 1969, p. 12).'],
['h', 'An old question'],
['p', 'Translators have asked “words or meaning?” for centuries. St Jerome, who translated the Bible into Latin, wrote that he translated “not word for word but sense for sense” (Jerome, 395/2012). In the fourteenth century, al-Ṣafadī described two methods used by the translators of the Abbasid era: some, such as Yūḥannā ibn al-Biṭrīq, translated word by word, while others, such as Ḥunayn ibn Isḥāq, translated the meaning of the whole sentence. Al-Ṣafadī judged the second method to be better (Baker & Hanna, 2009).'],
['try', ['Which kind of equivalence is this? _Ali is second to none in poetry._ → {{عليٌّ لا يُشقّ له غبار في الشعر}}', 'And this? _Ali is second to none in poetry._ → {{عليٌّ شاعرٌ متميّز}}'],
        ['Functional equivalence: an Arabic idiom that does the same job.', 'Ideational equivalence: only the basic idea.']],

['ch', 'Chapter 7: The seven translation procedures'],
['p', 'When a word or phrase is difficult, you need a technique. Vinay and Darbelnet (1958/1995) described seven basic techniques, called **translation procedures** ({{إجراءات الترجمة}}). Newmark explains the difference between a method and a procedure: “while translation methods relate to whole texts, translation procedures are used for sentences and the smaller units of language” (Newmark, 1988, p. 81).'],
['p', 'Try the procedures in order. The first three stay close to the original; the last four move further away. Move down the list only when the result sounds wrong.'],
['ol', [
  '**Borrowing** ({{الاقتراض}}): take the word as it is. _computer_ → {{كمبيوتر}}',
  '**Calque** ({{النسخ}}): translate each part of an expression. _skyscraper_ → {{ناطحة سحاب}}',
  '**Literal translation** ({{الترجمة الحرفية}}): translate word for word, when the result is correct. _The book is on the table_ → {{الكتاب على الطاولة}}',
  '**Transposition** ({{الإبدال}}): change the word class, for example a noun into a verb. _after his arrival_ → {{بعد أن وصل}}',
  '**Modulation** ({{التحوير}}): say the same thing from another point of view. _It is not difficult_ → {{إنه سهل}}',
  '**Equivalence** ({{التكافؤ}}): use a completely different fixed expression. _Like father, like son_ → {{هذا الشبل من ذاك الأسد}}',
  '**Adaptation** ({{التكييف}}): replace a cultural reference with a familiar one. _like Romeo and Juliet_ → {{كقيسٍ وليلى}}',
]],
['h', 'The procedures at work'],
['p', 'One sentence often needs several procedures:'],
['ex', '_After his arrival in Kuwait, the minister held a press conference at the Sheraton and said the reforms were not impossible._'],
['ar', 'بعد أن وصل الوزير إلى الكويت، عقد مؤتمراً صحفياً في فندق شيراتون، وقال إنّ الإصلاحات ممكنة.'],
['ul', [
  '_after his arrival_ → {{بعد أن وصل}}: transposition',
  '_press conference_ → {{مؤتمر صحفي}}: calque',
  '_Sheraton_ → {{شيراتون}}: borrowing',
  '_not impossible_ → {{ممكنة}}: modulation',
]],
['p', 'Learn the names: you will use them when you explain your choices (Chapter 14).'],
['try', ['Which procedure? _email_ → {{إيميل}}', 'Which procedure? _honeymoon_ → {{شهر العسل}}'],
        ['Borrowing.', 'Calque.']],

['ch', 'Chapter 8: When there is no equivalent'],
['p', 'Sometimes the other language has no word for something in your text, because it does not exist in that culture. English has no single word for {{الزكاة}}, and Arabic once had no word for _blog_. Mona Baker calls this problem **non-equivalence** and describes the strategies translators use to solve it (Baker, 2018). Try them in this order:'],
['ol', [
  '**Search first.** An accepted term may already exist. Check UNTERM (United Nations, n.d.), Arabterm (Arabization Coordination Bureau & GIZ, n.d.) and the Arabic language academies: _greenwashing_ → {{التضليل البيئي}}; _cybersecurity_ → {{الأمن السيبراني}}.',
  '**Use a more general word** if it is enough: _prawns_ and _shrimps_ → {{روبيان}}.',
  '**Borrow the word and explain it.** Write the word in the other alphabet, which is called **transliteration** ({{النقل الصوتي}}), and explain it in brackets the first time it appears: {{الزكاة}} → _zakat_ (obligatory almsgiving in Islam). Adding an explanation like this is called **addition** ({{الإضافة}}).',
  '**Describe it.** This is **descriptive translation** ({{الترجمة الوصفية}}): _jet lag_ → {{إرهاق السفر}}. Use it as a last option, because it makes the text longer.',
  '**Create a new word**, only if nothing exists. This is **lexical creation** ({{النحت المعجمي}}): _blog_ → {{مدوّنة}}; _smartphone_ → {{الهاتف الذكي}}.',
]],
['h', 'An example'],
['p', 'An English text about Islam contains the word {{التيمّم}}. English has no word for it, and a general word such as “washing” would be wrong, because no water is used. So the translator borrows the word and explains it: _tayammum_ (ritual washing with clean earth when there is no water). After that, _tayammum_ is enough.'],
['p', 'Two more examples: {{البسملة}} → _the basmala_ (saying “In the name of God, the Most Gracious, the Most Merciful”); {{العِدّة}} → _ʿidda_ (the waiting period before a divorced or widowed woman may remarry).'],
['try', ['Translate for English readers: {{الوقف}}', 'Why is describing a word the last option?'],
        ['_waqf_ (a charitable endowment).', 'Because it makes the text longer.']],

['ch', 'Chapter 9: Translating culture'],
['p', 'Words carry culture. “Summer” sounds lovely to an English reader, but a Kuwaiti reader thinks of 50°C heat. When an image carries a different feeling in the other culture, translate the feeling, not the picture. The Translation Team’s course materials call this **cultural approximation** ({{التقريب الثقافي}}) (Translation Team, n.d.).'],
['h', 'Images and metaphors'],
['p', 'A **metaphor** ({{الاستعارة}}) describes something as if it were something else: _He is a rock._ A **simile** ({{التشبيه}}) makes the comparison with “like” or “as”. Newmark (1988) suggests these steps for translating a metaphor, in order:'],
['ol', [
  '**Keep the image** if both cultures share it: _She is a snake_ → {{إنها أفعى}}.',
  '**Use a local image** with the same meaning: _the tip of the iceberg_ → {{غيضٌ من فيض}}.',
  '**Turn it into a simile**: _He is a rock_ → {{إنه كالصخرة في ثباته}}.',
  '**Give the plain meaning**, as a last option: _He is a chicken_ → {{إنه جبان}}.',
]],
['h', 'When climate changes the meaning'],
['p', '_The news warmed my heart_ becomes {{أثلجَ الخبرُ صدري}}: in a hot climate, relief feels cold, not warm. For the same reason, translators of Shakespeare’s line “Shall I compare thee to a summer’s day?” (Shakespeare, 1609) may choose spring for Arab readers: {{أأشبّهكِ بيومٍ ربيعيّ؟}}'],
['h', 'Greetings, titles and cultural references'],
['p', 'For greetings, thanks and condolences, use what people actually say in the same situation:'],
['ul', [
  '_I’m sorry for your loss._ → {{عظّم الله أجركم}}',
  '_Thank you for your hard work._ → {{الله يعطيك العافية}}',
  '_Many happy returns!_ → {{عساكم من عُوّاده}} (a Gulf greeting)',
]],
['p', 'For official titles, translate the job, not the words: _the Secretary of State_ (US) → {{وزير الخارجية}}; _the Chancellor of the Exchequer_ (UK) → {{وزير المالية}}. For a cultural reference that readers would not know, you can use **cultural substitution** ({{الإبدال الثقافي}}): _Romeo and Juliet_ → {{قيس وليلى}} (Baker, 2018).'],
['h', 'Local or foreign?'],
['p', 'For the text as a whole, you can make it feel local to your reader, which Venuti (1995) calls **domestication** ({{التوطين}}), or keep its foreign flavour, which he calls **foreignisation** ({{التغريب}}). For example, _the diwaniya_ keeps a foreign flavour for English readers, while _a men’s evening gathering_ makes the idea familiar. The distinction goes back to Schleiermacher (1813/2012), who wrote that the translator either moves the reader towards the author or moves the author towards the reader. Let the brief decide (Chapter 2).'],
['try', ['Translate: _cut from the same cloth_', 'Translate: _a scapegoat_'],
        ['{{من طينةٍ واحدة}}.', '{{كبش الفداء}}.']],

['ch', 'Chapter 10: Terms and dictionaries'],
['p', 'In law, medicine and other special fields, some words have one exact meaning. These words are called **terms** ({{المصطلحات}}). One wrong term can change the meaning of a contract. Working carefully with terms is called **terminology management** ({{إدارة المصطلحات}}) (Cabré, 1999).'],
['h', 'Find, check, record, share'],
['ol', [
  '**Find** the key terms in the text.',
  '**Check** them in reliable sources: UNTERM, Arabterm, the Arabic language academies and the client’s glossary.',
  '**Record** each term, its translation and an example in a **term list** ({{قائمة المصطلحات}}).',
  '**Share** the list, so that everyone on the team uses the same terms.',
]],
['p', 'Use **one term for one idea** all the way through the text. If you translate _Article_ as {{مادّة}} in the first paragraph, do not change to {{بند}} later “for variety”: a new word makes the reader think of a new meaning. Two examples from legal texts: _governing law_ → {{القانون الواجب التطبيق}} (not {{القانون الحاكم}}); _provided that_ → {{شريطةَ أن}}.'],
['h', 'Using dictionaries'],
['p', 'A dictionary gives you options, not answers. Samuel Johnson, the author of one of the first great English dictionaries, remarked that “dictionaries are like watches; the worst is better than none, and the best cannot be expected to go quite true” (Piozzi, 1786). Use the three-check rule:'],
['ol', [
  'Find the options in a **bilingual dictionary** ({{معجم ثنائي اللغة}}).',
  'Confirm the meaning in a **monolingual dictionary** ({{معجم أحادي اللغة}}).',
  'See how the word is really used in a text written in the target language.',
]],
['p', 'For example, for _a fast colour_ a bilingual dictionary gives {{سريع}} and {{ثابت}}. An Arabic dictionary confirms that {{ثابت}} can mean “not fading”. So the answer is {{لون ثابت}}.'],
['h', 'Useful dictionaries'],
['ul', [
  '_Al-Mawrid_ (Baalbaki, n.d.): everyday words, English–Arabic and Arabic–English.',
  '_A Dictionary of Modern Written Arabic_ (Wehr, 1994): Arabic words, listed by root.',
  '_Al-Muʿjam al-Wasīṭ_ ({{المعجم الوسيط}}) (Academy of the Arabic Language, n.d.): Arabic meanings.',
  '_Oxford Collocations Dictionary for Students of English_ (2009): natural English word partners.',
  'UNTERM (United Nations, n.d.) and Arabterm: official and technical terms.',
]],
['p', 'Printed dictionaries are edited by experts, but they are slower to use and may not include new words. Digital dictionaries are fast and up to date, but their quality varies, so always check who publishes them.'],
['try', ['Which kind of dictionary do you use to confirm a meaning?', 'Why should you use the same term all the way through a text?'],
        ['A monolingual dictionary.', 'Because a new word makes the reader think of a new meaning.']],

// ================= PART 4 =================
['part', 'Part 4: Checking and explaining', 'A translation is not finished when you write the last word. This part shows you how to check your work and explain your choices.'],

['ch', 'Chapter 11: Revising your translation'],
['p', 'Your first version is a **draft** ({{المسوّدة}}). Every translator makes mistakes in a draft, even experts. **Revision** ({{المراجعة}}) is where you find and correct them (Mossop, 2014).'],
['h', 'Three readings'],
['ol', [
  '**With the original**: is anything missing, added or changed?',
  '**Without the original**: does it sound natural? If a sentence sounds translated, rewrite it.',
  '**The details**: numbers, names, spelling, punctuation, titles and captions.',
]],
['p', 'For example, the draft {{تمّ افتتاح المعرض من قِبَل الوزير}} is complete, but it copies the English passive (“was opened by”). Revised: {{افتتح الوزير المعرض}}.'],
['h', 'Common mistakes in Arabic (EN → AR)'],
['ul', [
  'Starting with the subject: {{الحكومة أعلنت}} → {{أعلنت الحكومة}}',
  'Overusing {{قام بـ}}: {{قام الوزير بزيارة الكويت}} → {{زار الوزير الكويت}}',
  'Numbers 3 to 10: {{ثلاث طلاب}} → {{ثلاثة طلاب}}',
  'Spelling of hamza and taa marbuta: {{انشاء، مدرسه، الى}} → {{إنشاء، مدرسة، إلى}}',
  'English punctuation: {{نعم, شكراً?}} → {{نعم، شكراً؟}}',
]],
['h', 'Common mistakes in English (AR → EN)'],
['ul', [
  'Very long sentences joined with “and”: split them with full stops.',
  'Repeated synonyms: _brave and daring_ → _very brave_',
  'An extra “the”: _The life is beautiful_ → _Life is beautiful_',
  'A missing “is”: _He in the office_ → _He is in the office_',
  'Arabic prepositions: _He married from her_ → _He married her_',
  'Missing capital letters: _the minister of health_ → _the Minister of Health_',
]],
['try', ['Improve: {{قام المدير بتوقيع العقد.}}', 'Improve: _She is a doctor in the hospital and she works hard and she likes her job._'],
        ['{{وقّع المديرُ العقد.}}', '_She is a doctor at the hospital. She works hard and likes her job._']],

['ch', 'Chapter 12: Spotting risks'],
['p', 'Some mistakes are small. Others can cause real harm, such as a wrong dose in a medicine leaflet or a missing “not” in a contract. Anthony Pym describes translating as a kind of **risk management** ({{إدارة المخاطر}}): the more serious the possible harm, the more care a text needs (Pym, 2015). Before you deliver a translation, check these places:'],
['ul', [
  '**Terms**: _governing law_ is {{القانون الواجب التطبيق}}, not {{القانون الحاكم}}. Check a specialised dictionary.',
  '**Negatives**: a lost “not” turns a sentence into its opposite. Compare sentence by sentence.',
  '**Legal words**: in a contract, _shall_ expresses an obligation, not the future, so use the Arabic present tense, not {{سوف}}.',
  '**Numbers and dates**: check every figure, and whether a date is Hijri or Gregorian.',
  '**Cultural images**: _warmed my heart_ is not {{أدفأ قلبي}} (Chapter 9).',
  '**Sensitive names**: _Persian Gulf_ or _Arabian Gulf_? Follow the client’s policy and mention your choice in your commentary.',
  '**Style**: a dialect word does not belong in a formal report.',
  '**Words with several meanings**: {{علم}} can mean a flag, knowledge or “taught”. Read the words around it.',
]],
['p', 'For example: _This Agreement shall be governed by the laws of the State of Kuwait._ → {{تخضع هذه الاتفاقية لقوانين دولة الكويت.}} (not {{سوف تخضع}}).'],
['p', 'For serious texts, such as legal and medical ones, ask a second person to check your translation.'],
['try', ['What is the main risk in _Take one tablet twice daily_?'],
        ['The dose: the numbers must be exactly right.']],

['ch', 'Chapter 13: Machine translation and AI'],
['p', '**Machine translation** ({{الترجمة الآلية}}) tools and AI chat tools can translate a text in seconds. They are useful helpers, but they make mistakes that beginners may not notice, and you, not the machine, are responsible for the final text (Kenny, 2022).'],
['h', 'Useful or risky?'],
['p', 'Machines can help with a first draft of a simple text or with checking your ideas. They are risky for legal, medical and religious texts, for idioms and poetry, and for any private or confidential text.'],
['h', 'Typical mistakes'],
['ul', [
  '_It’s raining cats and dogs_ → {{إنها تمطر قططاً وكلاباً}}: the idiom is translated word by word. Correct: {{تمطر بغزارة}}.',
  '_The doctor said she…_ → {{قال الطبيب…}}: the machine guessed a man. Correct: {{قالت الطبيبة…}}.',
  'AI tools sometimes add information that is not in the text at all. This is called **hallucination** ({{الهلوسة}}).',
]],
['h', 'Four rules'],
['ol', [
  'You are responsible for every word.',
  'Never put a client’s private text into a public AI tool.',
  'Check terms, names, numbers, idioms and every “not”.',
  'Tell the client if you used a machine or AI.',
]],
['p', 'Correcting machine output is called **post-editing** ({{التحرير اللاحق}}). It is now an important part of many translators’ work.'],
['try', ['May you paste a client’s confidential contract into a free AI tool?'],
        ['No, never.']],

['ch', 'Chapter 14: Writing a commentary'],
['p', 'Teachers and clients often ask why you translated something in a certain way. A **commentary** ({{التعليق على الترجمة}}) is your answer: a short text that explains the problems you met and justifies your solutions, like showing your working in a maths exam (Dickins et al., 2016).'],
['h', 'Five steps'],
['p', 'For each difficult point, write:'],
['ol', [
  '**The problem**: what was difficult?',
  '**The solution**: what did you write?',
  '**The procedure or strategy**: which technique did you use (Chapters 6 to 10)?',
  '**The resource**: which dictionary or source did you check?',
  '**The reason**: why is your choice right for the reader?',
]],
['p', 'Write in the third person (“The translator…”), quote your examples, and always explain why.'],
['h', 'An example'],
['ex', '_The source text says the agreement “remained a dead letter”. A literal translation, {{حرفاً ميتاً}}, would confuse Arab readers, so the translator chose {{حبراً على ورق}}, a functional equivalent. The expression was checked in Arabic newspapers. It is a familiar idiom and suits the formal style of a news report._'],
['try', ['Write one commentary sentence for _strong tea_ → {{شاي ثقيل}}.'],
        ['For example: “_Strong tea_ is a collocation, so it could not be translated word by word; the translator used the Arabic partner {{شاي ثقيل}}, which sounds natural to Arab readers.”']],

// ================= PART 5 =================
['part', 'Part 5: Going further', 'You now know the basics. These chapters open the next doors.'],

['ch', 'Chapter 15: Types of text'],
['p', 'A recipe, a news report and a poem are written in very different ways. Each type of text, or **genre** ({{الجنس النصّي}}), has its own rules, and your translation must follow the rules of the same genre in the target language. Katharina Reiss groups texts by their main function: to inform, to express, or to persuade (Reiss, 2000).'],
['ul', [
  '**News**: facts, a neutral tone and short headlines. _Oil prices rose sharply on Monday._ → {{ارتفعت أسعار النفط ارتفاعاً حادّاً يوم الاثنين.}}',
  '**Legal**: exact words; _shall_ expresses an obligation. _This Agreement shall be governed by the laws of the State of Kuwait._ → {{تخضع هذه الاتفاقية لقوانين دولة الكويت.}}',
  '**Political**: careful, sensitive words. _The two sides held frank and constructive talks._ → {{أجرى الجانبان محادثاتٍ صريحةً وبنّاءة.}}',
  '**Medical**: no ambiguity and exact doses. _Take one tablet twice daily._ → {{تناوَل قرصاً واحداً مرّتين يومياً.}}',
  '**Technical**: clear instructions and consistent terms. _Press and hold the power button._ → {{اضغط مطوّلاً على زرّ التشغيل.}}',
  '**Literary**: feeling, voice and natural dialogue. _It has been a long day._ → {{كان يوماً شاقّاً.}}',
  '**Poetry**: images and rhythm, with more freedom. {{الخيلُ والليلُ والبيداءُ تعرفني}} (al-Mutanabbi, n.d.) → _The horses, the night and the desert know me._',
  '**Advertising**: persuasion and rhythm. _Save more. Smile more._ → {{وفّر أكثر… وابتسم أكثر!}}',
]],

['ch', 'Chapter 16: Language and ideology'],
['p', 'The same event can be described in words that show different points of view. A set of beliefs that shapes how events are described is called an **ideology** ({{الأيديولوجيا}}). A translator must notice these choices, because a translation can keep, soften or strengthen them.'],
['ul', [
  '_regime_ or _government_ ({{نظام}} or {{حكومة}}): “regime” is negative.',
  '_Protesters were killed_ ({{قُتل متظاهرون}}): the passive hides who did it.',
  '_suicide bomber_: {{انتحاري}} or {{استشهادي}}? The choice depends on the client’s policy.',
]],
['h', 'Fairclough’s three levels'],
['p', 'Norman Fairclough treats language use “as a form of social practice” (Fairclough, 1992) and studies texts on three connected levels. His approach is known as **critical discourse analysis** ({{تحليل الخطاب النقدي}}) (Fairclough, 1989, 1992). For each text, ask:'],
['ol', [
  '**The text**: which words show judgement? Who is shown doing what?',
  '**Its production**: who wrote it, for which newspaper or organisation, and for which readers?',
  '**Society**: whose interests does it serve?',
]],
['p', 'Follow the client’s policy, and explain sensitive choices in your commentary (Chapter 14).'],

['ch', 'Future editions'],
['p', '[To be completed by the Translation Team: the audiences and materials planned for future editions of this handbook. Suggestions: authentic news texts for practice; a checklist based on Dr Abdullah’s framework; chapters on interpreting, subtitling, and legal and medical translation.]'],
];
