// Feedback report content (updated for the second Word version).
module.exports = [

['h1', '1. Summary'],
['p', 'This report explains how the Translation Handbook was produced from the team’s materials: what was taken from the original draft, what was changed and why, what was added, and what was left out. It checks every request in the professor’s notes and lists what must still be done before the handbook is published. It describes the **third Word version** of the handbook, which adds the second batch of materials (the terminology chapter and the audiovisual translation notes) and the Guild visual style.'],
['h3', 'The handbook in brief'],
['ul', [
  'An editable Word document (Translation-Handbook.docx), B5 size, about 93 pages, in a simple layout based on the style of Guild’s posts.',
  'Built on the professor’s instructions: **9 parts and 27 chapters**, ordered from easy to hard: getting started; meaning; words that go together; methods and techniques; culture and new words; whole texts; tools and resources; checking and explaining; and, last and most advanced, audiovisual translation.',
  'Every chapter has the same pattern: an introduction that links it to the previous chapter, **key terms with definitions**, explanation and examples, a short “Try it” exercise with answers, and a “Remember” summary.',
  'Front matter: title page, copyright page, contents, preface (with the objectives from the draft), acknowledgements, how to use the handbook, and abbreviations.',
  'Back matter: practice in three levels with an answer key, four checklists (including one based on Fairclough), future editions, a glossary of 102 terms built from the key terms of every chapter, the references and a back cover.',
]],
['h3', 'Overall verdict'],
['p', 'The handbook now follows the professor’s structure and is **close to publishable**. It can be used in Guild workshops after one careful review. Before public publication, the team must still: (1) check the quotations and references (Section 11 gives the results of an online check); (2) supply the missing materials and details marked in square brackets; (3) have the Arabic proofread by a qualified translator; and (4) take the decisions listed in Section 9.'],

['h1', '2. The materials used'],
['h3', 'Materials received'],
['table', ['Material', 'What it contained', 'How it was used'],
 [['**Draft_one.docx** (the original draft)', 'About 730 lines of notes: definitions, Arabic–English differences, equivalence, form and meaning, types of meaning, collocation, context, idioms, literal, metaphoric and free translation, strategies, cultural approximation, descriptive translation, lexical creation, text analysis, commentary, exercises 16 and 24–29. The Terminology, AI, Glossary and References headings were empty.', 'The main source of ideas and examples. Every chapter is built on it where it had content.'],
  ['**Latest_upades_and_thoughts.docx** (the professor’s notes)', '64 lines of instructions (several repeated two or three times) on structure, new chapters, checklists, exercises, references and team tasks.', 'Used as the list of requirements. Each request is checked in Section 4.'],
  ['**The Guild logo**', 'The club logo image.', 'Used for colours in the earlier PDF versions. The final Word version uses a plain text title page.']],
 [26, 44, 30]],
['h3', 'Second batch of materials'],
['table', ['Material', 'What it contained', 'How it was used'],
 [['**Terminology_chapter.docx**', 'Definition and history of terminology; how translators benefit; functions; how terminologists work; translator skills; categories of terms; rules for naming terms; the Arabic academies; how to translate a term; technical dictionaries; termbases; standardisation bodies.', 'Rewritten in plain English as Chapter 21, Terminology and terminology management. Nearly all points kept; repeated points merged; facts checked (Section 11).'],
  ['**Intro_to_AVT.pdf** and **AVT_2.pdf** (course notes)', 'Why AVT is growing and special; terminological progress; types of AVT; theories (Skopos, DTS, reception studies, polysystem); challenges; AVT in the Arab world; dubbing; subtitling (classifications, semiotics, linguistic variation, strategies of Díaz Cintas and Remael and of Pedersen); taboo language and censorship.', 'Rewritten as a new Part 9, Chapters 26 (Introduction to audiovisual translation) and 27 (Subtitling), placed last because it is the most advanced topic.'],
  ['**Guild post screenshots**', 'The club’s visual style.', 'Used as a reference: white pages, deep purple serif headings, one lavender box style for key terms and summaries, the Guild wordmark on the cover and back cover.'],
  ['**Draft_one.docx** and **the notes** (again)', 'The draft is identical to the first copy; the notes differ only in two typing corrections.', 'No change needed.']],
 [26, 44, 30]],
['h3', 'Materials mentioned in the notes but not received'],
['ul', [
  'The **180** textbook and the **182** course book (notes, lines 26 and 64).',
  'The **386** texts and the **Analysis** texts, from which example sentences were to be extracted (line 26).',
  'The text **«الترجمة: ماهيتها»** (line 39).',
  '**Loulwah’s notes** on machine translation and dictionaries (lines 6, 13 and 56).',
  '**Dr Abdullah’s PhD research or framework**, needed for one of the checklists (line 47).',
  '“**The book**” with useful examples (line 24): its title is not given.',
  'Contributions assigned to team members: Shaikha (organisation and examples), Masooma (practice texts; her terminology chapter has now been received and used), Loulwah (dictionary examples and machine translation notes).',
]],
['p', 'Anything that depended on these materials could not be done properly. In those places the handbook either has a placeholder in square brackets or uses standard published sources instead.'],


['h1', '3. How the work progressed'],
['table', ['Version', 'What changed', 'Why'],
 [['1. A5 designed PDF', 'First full layout, with a strong visual design.', 'Initial request for an A5 handbook with the logo’s theme.'],
  ['2. B5 designed PDF (35, then 44 pages)', 'New page size and a detailed design system.', 'Second specification: B5, workflow structure, design rules.'],
  ['3. Calm B5 PDF (48 pages)', 'Much simpler design, one layout for every chapter, cover without the square logo.', 'Feedback: “too complicated”, “not beginner-friendly”, “remove the square”.'],
  ['4. Beginner PDF with quotations (56 pages)', 'Added “In plain words” boxes, quotations from translation scholars, and a first-translation walkthrough.', 'Feedback: “simplify more”, “explain”, “add quotes related to translation”.'],
  ['5. Guided “toolkit” layout', 'Tried a stage-and-tool structure. Not delivered.', 'Feedback: “still too technical”. Stopped when the next instruction arrived.'],
  ['6. Word document, first version', 'Rewritten as plain text in Word; all visual elements removed; every idea cited; references at the end.', 'Feedback: “too many visual elements”, “cite and reference everything”, “I want a Word document to edit”.'],
  ['7. Word document, second version', 'Rebuilt on the professor’s chapter list: 8 parts and 25 chapters from easy to hard; every chapter introduced and linked to the previous one; key terms in every chapter; dropped draft material restored; risk matrix, checklists, copyright and acknowledgements pages added.', 'Instruction: follow the professor’s instructions, table of contents and chapters, in chronological order, step by step, and make it publishable.'],
  ['8. Word document, third version', 'Terminology chapter merged into Chapter 21; new Part 9 on audiovisual translation (Chapters 26 and 27); Guild visual style; back cover; 11 new references checked online.', 'New materials and Guild posts supplied, with full authority to edit, add and remove.'],
  ['9. Clarity pass', 'Chapter 21 and Part 9 rewritten in shorter, plainer sentences; the two overlapping subtitling strategy lists (Díaz Cintas and Remael; Pedersen) merged into one list of eight; every sentence of 30 words or more in the other chapters split or shortened; the Level 3 instructions turned into a numbered list.', 'Instruction: “simplicity is the key; make it as clear as possible.”'],
  ['10. Beginner pass (current)', 'Theory for specialists removed: the communication model (Ch. 1), the history section (Ch. 10), Schleiermacher (Ch. 13), Fairclough’s theory reduced to three simple questions (Ch. 19, now “Words and points of view”), the history of terminology, the standards bodies and the academies’ procedures (Ch. 21), the history of the AVT field and three of its four theories (Ch. 26); key terms reduced to what beginners need; ten references no longer cited removed.', 'Instruction: “you don’t have to go deep into theories; it is for beginners and should guide them.”']],
 [26, 40, 34]],
['p', 'An honest note: several rounds were needed because early versions put design before simplicity, and the first Word version removed too much of the draft. The second version corrects this: it follows the professor’s structure and restores the draft material (Section 8).'],


['h1', '4. The professor’s notes: request by request'],
['p', 'Status key: **Done**, **Partly done**, **Not done**. Repeated requests are listed once. Line numbers refer to the order of the paragraphs in the notes document.'],
['table', ['Request (notes line)', 'Status', 'Where in the handbook', 'Comment'],
 [['Organise the material, make it cohesive and remove repetition (1, 8, 17)', '**Done**', 'Whole book', 'Topics that the draft repeated two or three times (equivalence, denotation and connotation, collocation, idioms, descriptive translation) now appear once, each in its own chapter.'],
  ['Add missing translation strategies (2, 9, 18)', '**Done**', 'Chapter 13', 'The draft’s six strategies are kept; added: a more general word, a more neutral word, paraphrase, loan word plus explanation (Baker, 2018), compensation (Dickins et al., 2016), and domestication/foreignisation (Venuti, 1995).'],
  ['Add missing types of translation (2, 9, 18)', '**Done**', 'Chapter 1; Part 9', 'Written translation, interpreting, sight translation, audiovisual translation and localisation; Part 9 covers the types of AVT in detail.'],
  ['New chapter: the seven translation procedures (3, 10, 19, 44)', '**Done**', 'Chapter 12', 'Direct and oblique procedures, examples, and one sentence showing several procedures.'],
  ['Add to the cultural approximation chapter (4, 11, 20)', '**Done**', 'Chapter 14', 'Expanded with climate and meaning, titles, media and business terms, and social expressions.'],
  ['Definitions in every chapter; all terms in the glossary (5, 12, 21, 53)', '**Done**', 'Every chapter; Glossary', 'Each chapter opens with its key terms; the glossary is built automatically from them (97 terms).'],
  ['Chapter on machine translation and AI (6, 13, 22)', '**Done**', 'Chapter 22', 'Includes the draft’s point that post-editing is the new direction. Loulwah’s notes have still not been received.'],
  ['Final exercises in three levels, applying theories, genres and checklists (16)', '**Done**', 'Practice', 'Level 1 sentences, Level 2 short texts (legal, classical poetry, English poetry), Level 3 full texts (news), with instructions to apply the checklists and the risk matrix.'],
  ['Use examples from “the book” (24)', '**Not done**', '–', 'The book was not identified or supplied.'],
  ['Add authentic news texts (25, 59)', '**Not done**', 'Practice, Level 3', 'The two news texts were written for the handbook and are marked for replacement. Authentic texts could not be downloaded in the working environment.'],
  ['Extract sentences from the Analysis, 180 and 386 texts (26)', '**Not done**', '–', 'These texts were not supplied. Listed under Future editions.'],
  ['Include examples from poetry (27)', '**Done**', 'Chapters 11 and 18; Practice', 'Metaphors, al-Mutanabbi and Shakespeare’s Sonnet 18.'],
  ['Include the main genres, with at least one example each (28, 29)', '**Done**', 'Chapter 18', 'Eight genres, each with an English–Arabic example, grouped by Reiss’s three text types.'],
  ['Tips, advice, techniques and preparation at the beginning (30)', '**Done**', 'Chapter 2', 'The second chapter, straight after the basic definitions. Includes the draft’s tips and a worked first translation.'],
  ['Practical checklists (31)', '**Done**', 'Checklists', 'Translation process, analysis worksheet, critical discourse, and commentary.'],
  ['Who is the client? Purpose? Target audience? (32–35)', '**Done**', 'Chapter 2', 'The three questions form the translation brief.'],
  ['Chapter on terminology management and terminology guides (36, 62)', '**Done**', 'Chapter 21', 'A full chapter, now based on Masooma’s terminology chapter: definition, history, terminologists, types of terms, rules for good terms, the Arabic academies, termbases, terminology guides and standardisation bodies.'],
  ['Interlingual risk assessment matrix (37)', '**Done**', 'Chapter 24', 'A ten-row matrix: risk area, example, risk level and what to do.'],
  ['Audiences and materials for future editions (38)', '**Partly done**', 'Future editions', 'Mentions the planned Arabic version (line 50) and suggestions; the team must confirm its plans.'],
  ['Cite anything from «الترجمة ماهيتها» and attribute it to Dr Yusuf (39)', '**Partly done**', 'References', 'The text was not supplied, so nothing is quoted from it. The reference placeholder now records the notes’ attribution to Dr Yusuf and asks the team to confirm it.'],
  ['Chapter on text analysis (40)', '**Done**', 'Chapter 17', 'A separate chapter, the first of the three phases: analysis, translation, commentary.'],
  ['Chapter on translation commentary, including how to analyse a translation (41)', '**Done**', 'Chapter 25', 'Two parts, five steps, rules and an example.'],
  ['Chapter on printed and digital dictionaries (42)', '**Done**', 'Chapter 20', 'A separate chapter: types of dictionary, the three-check rule, printed vs digital, and a list of useful dictionaries.'],
  ['Fairclough’s relational model (45)', '**Done, simplified**', 'Chapter 19; Checklist 3', 'Kept at beginner level: three practical questions based on Fairclough (1992). The theory itself was left out, as you asked. An expert should confirm this is enough for the professor.'],
  ['Three checklists based on Dr Abdullah’s framework and Fairclough’s model (46–48)', '**Partly done**', 'Checklist 3', 'The Fairclough checklist is done. The Dr Abdullah checklist is left out of this edition because his framework was not among the materials received. It can be added in the next edition.'],
  ['Collect examples from books, poetry, proverbs, idioms and text types, with sources cited (52)', '**Partly done**', 'Chapters 8, 11, 14 and 18', 'Many examples added and cited; the sources of the draft’s own examples are still unknown (Section 9).'],
  ['Common grammatical and stylistic mistakes: in each chapter or a separate section? (60)', '**Done**', 'Chapter 23', 'Decision: one reference section, for both directions, inside the revision chapter.'],
  ['Answer key with explanations (61)', '**Done**', 'Answer key; “Try it” answers', 'Every answer has a short explanation.'],
  ['Table of contents and final structure (58)', '**Done**', 'Contents', 'Eight parts and 25 chapters; the contents page updates in Word.'],
  ['References for the 180 book, the 182 course book and all other sources (64)', '**Partly done**', 'References', 'All published sources are listed in APA style. The 180, 182 and 386 materials are placeholders.'],
  ['Keep the Arabic version for future use (50)', '**Noted**', 'Future editions', 'The planned Arabic version is mentioned.']],
 [29, 14, 18, 39]],

['h1', '5. The original draft: where each section is now'],
['p', 'Every section of the draft now has a home in the handbook, usually a chapter with the same name. The table shows where each section went, what changed, and what is still left out and why.'],
['table', ['Draft section', 'Now in', 'What changed', 'Still left out, and why'],
 [['Definitions and abbreviations', 'Abbreviations; key terms in each chapter', 'Every abbreviation kept (SL, TL, SLC, TLC, TS) and ST, TT, MT, AI, MSA added. Empty definitions filled in.', '“Principles = Foundations”: unclear.'],
  ['Arabic vs English', 'Chapter 3', 'All points kept: SVO/VSO, sentence length, synonyms, “is” → تُعدّ, small words (in bed, as, Roman ruins, shops stay open, eventually), types of Arabic, common challenges. Added: gender of “you”, numbers 3–10, linking words, punctuation.', '“Arabic is compositional, English is compounding”: an oversimplification. The note on قاضية/نائبة is kept but updated: these forms are now widely used.'],
  ['Objectives of the book', 'Preface', 'Kept as the aims of the handbook.', '–'],
  ['Translation, translator and how to translate', 'Chapters 1 and 2', 'Definitions, approximation, communication (sender, receiver, channel, message, noise), intralingual/interlingual, translator characteristics and skills, commissioned vs self-initiated, client ideology, tips (fidelity, rewriting, minefield, prose vs poetry, revise), and breaking a text into parts.', '“Translation also means to politicize”: wrong word. “Perceived value” as an element of communication: not a standard element.'],
  ['Equivalence', 'Chapter 9', 'Formal, functional and ideational, with all the draft examples (dead letter, think outside the box, second to none) and the treaty/agreement note. Cited to Farghal and Shunnaq (1999).', '–'],
  ['Form vs meaning', 'Chapter 4', 'Rule, “behind any form there is meaning”, meaning is cognitive, changing the form, the Blair example (“poodle”).', 'The Arabic alternatives with a typo (حروف أو غنمة).'],
  ['Types of meaning; sentence vs speaker meaning', 'Chapter 5', 'Denotation and connotation, die/pass away/kick the bucket (corrected), steed/horse, comrade, kill/assassinate; both air-conditioning examples.', '“Mule” as a negative synonym of horse: it is a different animal.'],
  ['Collocation', 'Chapter 7', 'Definition (Firth), pay money/attention/respect/visit, close cooperation/friend, strong tea, fast colour/friend, استلّ سيفه, يساورني القلق; break the law → خالف القانون.', '–'],
  ['Context; homonymy and polysemy', 'Chapter 6', 'Micro and macro context, the translation triangle, homonymy and polysemy with the draft’s examples (عين، تطهير، احتجاز، case، bank).', '–'],
  ['Idioms', 'Chapter 8', 'Definition, rule, piece of cake (literal vs idiomatic), cats and dogs, pull one’s socks up, over the moon, break a leg, hit the sack, don’t put words in my mouth, boys will be boys, business is business; proverbs.', 'Mocktail/cocktail moved to Chapter 14.'],
  ['Literal translation; free translation', 'Chapter 10', 'Modified literal translation, successful vs destructive, long day, biggest day; all four free-translation examples with the draft’s note on adaptation.', '–'],
  ['Metaphoric translation', 'Chapter 11', 'Metaphor, simile, figurative language, rhetoric; she is a snake, my thoughts evaporate, my paper will see light, tip of the iceberg (both Arabic versions), raises the brows. Steps follow Newmark (1988).', 'The inconsistent example “she is a snake → إنها كالثعلب”.'],
  ['Translation strategies (both sections)', 'Chapter 13; Chapters 16 and 21', 'All six strategies, key word, spill the beans, mark my words, addition and omission (with politeness), explanatory translation; terms and coinage moved to Chapters 16 and 21.', '“Kick the chair = انتحر”: not an established English idiom. “The Jordanian Academy has 74 fields”: could not be verified.'],
  ['Exercises 16 and 24–29', 'Chapters 7, 8 and 14', 'Many items used: fast colour, fast friend, break the law, hit the sack, Home Office, Chancellor, Secretary of the Treasury and of State, sheriff, watchdog/lapdog press, sleep like a log, God willing, welcome, condolences.', 'A readable book, a conceivable resolution, addled egg, plain, stormy sea, Every Jack has his Jill, what the hell…: could form an extra exercise set in a future edition.'],
  ['Cultural approximation', 'Chapter 14', 'Definition and all main examples: test in the bag, like mother like daughter, cut from the same cloth, scapegoat, busy as a bee (with the colloquial form labelled), jet lag, titles, product cannibalism.', '“Death is the great leveller = كل نفس ذائقة الموت”: uses a Qur’anic verse as an equivalent. “Big sins”: not a set phrase. Clinton example, intern, scandal: not needed.'],
  ['Descriptive translation', 'Chapter 15', 'Definition, steps, brackets or footnotes, last option; zakat, tayammum, basmala, hawqala, ʿidda, ʿatwa, sectioning.', 'القرقرة (doubtful meaning), Yin-Yang, psychology vs psychiatry.'],
  ['Lexical creation', 'Chapter 16', 'Definition, why it matters, five types, lexicalisation (التعجيم); blog, smartphone, shadow government, Valentine’s Day, Thanksgiving, waqf, sukuk, radio, greenwashing, cybersecurity, global warming, greenhouse effect, cancel culture.', 'Tribocracy, puppycracy, patriocracy: not established words. Co-wife, istitaba, CD: left out for space.'],
  ['Analysing a text', 'Chapter 17', 'All points: why analyse, highlight, analysis vs summary, the full checklist, three phases, characteristics of a good analyst, the KUNA example.', '“KUNA has biased views”: a public handbook should not call a named agency biased.'],
  ['Commentary on translation', 'Chapter 25', 'Two parts, third person, WH-questions, examples, omission note, strategies, dictionaries, justification.', '–'],
  ['Post-editing and titles notes', 'Chapters 2 and 22', 'Post-editing as the new direction; titles short, no additions, captions, quality + speed, reputation.', '–'],
  ['Terminology; AI and MT; Glossary; References (empty headings)', 'Chapters 21 and 22; Glossary; References', 'Written in full.', '–']],
 [17, 16, 37, 30]],

['h1', '6. Corrections to the draft'],
['p', 'These draft items were wrong, inconsistent or unsuitable for a published handbook. The handbook corrects or removes them.'],
['table', ['Draft says', 'Handbook says or does', 'Reason'],
 [['Died = قتل (denotative meaning)', 'die = مات', 'قتل means “killed”, not “died”.'],
  ['Kick the bucket = يموت كالحقير', 'Described as informal and humorous (Chapter 5)', '“Kick the bucket” is informal and humorous, not insulting. The Arabic adds an insult that is not in the English.'],
  ['“A clearer example that form is more important than meaning” (مثال أوضح على أن البناء أهم من المعنى)', 'Meaning is more important than form', 'The draft’s own rule is that meaning comes first. The line is a slip.'],
  ['she is a snake → إنها كالثعلب (as an unshared metaphor)', 'Replaced with “the tip of the iceberg → غيض من فيض”', 'The line before says the snake metaphor is shared (إنها أفعى), so the example contradicts itself.'],
  ['Idiom examples: pay a visit, strong tea, governing law', 'Moved to collocations and terms', 'These are collocations and a legal term, not idioms.'],
  ['Blair: Bush’s puppy', 'Blair, Bush’s poodle', '“Poodle” is the word actually used in the British press.'],
  ['Governing law → القانون المطبق', 'القانون الواجب التطبيق', 'Both are used; the term list now gives both forms.'],
  ['Jet lag → إعياء الطيران', 'إرهاق السفر', 'Both are possible. إرهاق السفر is more common. Optional change.'],
  ['mark my words = فل تتذكر وعدي / كلامي', 'تذكّر كلامي', 'Contains a typo, and “mark my words” means “remember what I said”, not a promise.'],
  ['Sorry to hear your loss = تعيش انت، شعبان مات; Welcome = أهلاً أهلاً زارنا النبي; What the hell are you talking = اتق الله يا شيخ', 'عظّم الله أجركم (formal), with the Egyptian البقية في حياتك as an alternative; أهلاً وسهلاً، شرّفتمونا', 'The draft forms are Egyptian colloquial; one mentions the Prophet in a casual way, and one does not match the English register. The replacements suit Gulf and formal use.'],
  ['UnIslamic ideology / Islamic ideology (suicide bomber example)', '“The choice depends on the client’s policy”', 'The original labels take a religious and political position. A public handbook should stay neutral and teach the principle.'],
  ['Publisher KUNA has biased views', 'Removed', 'A published handbook should not describe a named organisation as biased.'],
  ['“Translation also means to politicize (الدبلوماسية)”', 'Removed', '“Politicize” means to make something political. The idea (diplomatic wording) is not a definition of translation.'],
  ['Arabic is compositional (derivational), English is compounding', 'Removed', 'An oversimplification: both languages use derivation and compounding.'],
  ['Spelling errors: Freedome, phsycatery, vailate, Taxasion, imbedded/imbibed, hit the sac, Don’t put words on me, Matchful', 'Corrected or removed', 'Proofreading.']],
 [34, 26, 40]],


['h3', 'Corrections to the second batch of materials'],
['table', ['Source says', 'Handbook says or does', 'Reason'],
 [['“Evan Zohar” (AVT notes)', 'Itamar Even-Zohar', 'Spelling of the author’s name.'],
  ['“Hans J. Vermer”; “Diaz-Cintas/Rameal”; “explicatation”', 'Vermeer; Díaz Cintas and Remael; explicitation', 'Spelling.'],
  ['Subtitles have “32 to 41 characters per line”', 'Traditionally about 37–39 characters, up to 42 on streaming platforms; at most two lines', 'The figure in Díaz Cintas and Remael (2021), found in the online check.'],
  ['“Wüster (Vienna School)” in the 1930s', 'Wüster’s 1931 doctoral thesis founded the field; he is linked with the Vienna School', 'Wüster’s founding work was a 1931 thesis published in Berlin; the Vienna work came later.'],
  ['ISO “handles all technical specifications except electrical and electronic engineering”', 'ISO, with IEC for electrical and electronic standards and ITU for telecommunications', 'Telecommunications standards belong to the ITU.'],
  ['“over 150 countries” (ISO)', 'Not stated', 'The number changes over time; it was left out rather than risk an outdated figure.'],
  ['“foreign language/culture (informal) and target language/culture (formal)” (AVT notes)', 'Left out', 'Unclear, and not true in general.'],
  ['Dubbing “mainly used in Europe, America and Asia”', 'Common for cartoons, games and commercials, and widely used in the Arab world for children’s programmes and series', 'More accurate and more relevant for Arab readers.'],
  ['YouTube example links (AVT notes)', 'Left out', 'Links can stop working in a printed book; the team can add current examples in workshops.']],
 [32, 34, 34]],

['h1', '7. What was added that is not in the draft'],
['table', ['Added content', 'Where', 'Source or reason'],
 [['Front matter: copyright page, preface, acknowledgements, how to use, abbreviations', 'Front', 'Needed for publication. Names, copyright holder and ISBN are placeholders.'],
  ['Key terms, “Try it” and “Remember” in every chapter', 'Every chapter', 'The professor asked for definitions in every chapter; exercises and summaries help beginners.'],
  ['Quotations and citations', 'Throughout', 'Newmark (1988); Nida and Taber (1969); Jakobson (1959); Firth (1957); Eco (2003); Jerome; al-Jāḥiẓ; Shannon and Weaver (1949); Fairclough (1989, 1992, 2010); Nord (1997, 2005); Farghal and Shunnaq (1999); Baker (2018); Dickins et al. (2016); Venuti (1995); Schleiermacher; Reiss (2000); Cabré (1999); Mossop (2014); Pym (2015); Kenny (2022); Munday (2016). The citations for the draft’s ideas are my matches to standard sources, not the team’s original sources.'],
  ['Chapters requested in the notes but empty in the draft', 'Chapters 12, 18–24', 'Seven procedures, genres, Fairclough, dictionaries, terminology, MT and AI, revision and mistakes, risk matrix.'],
  ['New strategies', 'Chapter 13', 'More general word, more neutral word, paraphrase, loan word plus explanation, compensation.'],
  ['Types of translation', 'Chapter 1', 'Interpreting, sight translation, subtitling, localisation.'],
  ['“Putting it together: your first translation”', 'Chapter 2', 'A worked example of the whole process for beginners.'],
  ['New examples', 'Various', 'Break a leg (by meaning), heavy smoker, fast runner, prawns/shrimps, He is a rock, summer/spring, two Arabic proverbs, al-Ṣafadī and the Abbasid translators, shall in contracts, the doctor said she, genre examples, regime/government.'],
  ['Practice, answer key, four checklists, glossary, references', 'Back matter', 'Requested in the notes. The two news texts were written for the handbook.'],
  ['Explanations added to the AVT notes', 'Part 9', 'The notes were in short point form. Explanations were added for anchoring, redundancy, semiotic cohesion, subtitling “vulnerability” and the four channels of meaning; dubbing in the Arab world; and the link between Skopos theory and Nida’s dynamic equivalence (Nida, 1964).']],
 [30, 18, 52]],

['h1', '8. Draft material restored in the second version'],
['p', 'The first Word version left out useful draft material. The second version restores it:'],
['table', ['Item', 'Status', 'Where'],
 [['Fidelity (الأمانة); faithful, accurate and acceptable', '**Restored**', 'Chapter 2'],
  ['Translation as communication; communication elements', '**Restored**', 'Chapter 1'],
  ['Types of translation', '**Restored**', 'Chapter 1'],
  ['“A piece of cake”: idiomatic vs literal', '**Restored**', 'Chapter 8'],
  ['Small words: in bed, as an officer, Roman ruins, shops stay open, eventually', '**Restored**', 'Chapter 3'],
  ['Classical Arabic', '**Restored**', 'Chapter 3'],
  ['Break a text into sentences, phrases and words', '**Restored**', 'Chapter 2'],
  ['Micro and macro context; translation triangle; homonymy and polysemy', '**Restored**', 'Chapter 6'],
  ['“Biggest day” → يوم زفافك', '**Restored**', 'Chapter 10'],
  ['Test in the bag; like mother, like daughter; and more cultural examples', '**Restored**', 'Chapter 14'],
  ['Rules for titles and captions', '**Restored**', 'Chapter 2'],
  ['Two-part commentary; WH-questions', '**Restored**', 'Chapter 25'],
  ['A risk matrix', '**Added**', 'Chapter 24'],
  ['Unused exercise items (16, 24–29)', '**Partly restored**', 'Chapters 7, 8 and 14; the rest suggested for a future exercise set']],
 [52, 20, 28]],

['h1', '9. Points for the team to decide'],
['ol', [
  '**Dr Yusuf.** The professor’s notes (line 39) attribute «الترجمة: ماهيتها» to Dr Yusuf. Earlier in the work you said there is no Dr Yusuf. The reference placeholder records the notes’ attribution and asks for confirmation. Please confirm the correct author.',
  '**Sources of the draft’s examples.** The notes say the material was collected from more than one source. In the handbook these examples are credited to the team’s course materials. If any come from a textbook (for example the 180 or 182 books), that book must be credited instead.',
  '**Free translation.** Chapter 10 presents three of the draft’s four free-translation examples as “very free” and repeats the draft’s note that some specialists regard such adaptations as new texts. Please confirm this presentation.',
  '**Preferred Arabic forms.** Governing law: the term list gives {{القانون الواجب التطبيق}} and {{القانون المطبَّق}}. Jet lag: {{إرهاق السفر}} (the draft has {{إعياء الطيران}}).',
  '**Dialect in examples.** Some colloquial expressions are used and labelled (for example {{يعطيك العافية}}, {{البقية في حياتك}}, {{زي أم العروس}}). Keep them, or use only formal Arabic?',
  '**Fairclough.** Confirm that Chapter 19 and Checklist 3 match the “relational model” the professor intends.',
  '**Team contributions.** Merge the remaining work assigned to Shaikha (examples), Masooma (practice texts) and Loulwah (dictionary examples and machine translation). Masooma’s terminology chapter is already included.',
  '**Names and rights.** Fill in the copyright holder, editors, contributors, reviewers and acknowledgements.',
]],

['h1', '10. Before publishing: checklist'],
['ol', [
  'Check the quotations and references against the original books, especially the items in Section 11 that were not confirmed word for word or whose page is still to be checked.',
  'Confirm the sources of all draft examples, and credit them correctly.',
  'Add the full references for the 180, 182 and 386 materials and «الترجمة: ماهيتها».',
  'Add a checklist based on Dr Abdullah’s framework once the team has it (the professor’s notes, line 47).',
  'Replace the two written practice news texts with authentic news texts, with their sources.',
  'Have a qualified Arabic–English translator proofread every Arabic example.',
  'Open the file in Microsoft Word, update the contents page and check the layout (it was previewed in LibreOffice).',
  'Complete the copyright page and acknowledgements.',
  'Ask the supervisor and Dr Amin for feedback, as planned in the notes (line 57).',
  'Confirm the AI-assistance statement on the copyright page with the publisher’s and the university’s rules.',
]],

['h1', '11. Results of the online check of quotations and references'],
['p', 'The quotations and references were checked online through web search (search results only; the full texts of the books could not be opened). “Confirmed” means that several independent sources agreed on the wording, page or publication details. This check does not replace checking the books themselves. Some items below were later removed from the handbook in the beginner pass (for example Toury, Even-Zohar, O’Hagan and ISO 704), so they no longer need checking.'],
['table', ['Item', 'Result', 'Action taken in the handbook'],
 [['Newmark (1988, p. 5): definition of translation', '**Confirmed**', 'None needed.'],
  ['Newmark (1988): “by reading the original for two purposes…”', '**Wording confirmed**, page not seen', 'Cited as Chapter 2 instead of p. 11.'],
  ['Newmark (1988, p. 81): methods vs procedures', '**Confirmed**', 'None needed.'],
  ['Nida and Taber (1969, p. 4): “anything that can be said…”', '**Not confirmed** word for word', 'Changed from a quotation to a paraphrase.'],
  ['Nida and Taber (1969, p. 12): “the closest natural equivalent…”', '**Confirmed**', 'None needed.'],
  ['Jakobson (1959, p. 236): “Languages differ essentially…”', '**Confirmed**', 'None needed.'],
  ['Firth (1957, p. 11): “You shall know a word by the company it keeps”', '**Confirmed**', 'None needed.'],
  ['Jerome, Letter 57: “not word for word but sense for sense”', '**Confirmed**', 'None needed. The Translation Studies Reader (2012) edition confirmed.'],
  ['Samuel Johnson: “Dictionaries are like watches…”', '**Corrected**: the source is Johnson’s letter to Francesco Sastres (1784), not Piozzi (1786)', 'Citation and reference corrected (Johnsonian Miscellanies, 1897, vol. 2, p. 309).'],
  ['Fairclough (1992): language use “as a form of social practice”', '**Not confirmed** word for word', 'Changed to a paraphrase.'],
  ['Nord (1997): “function plus loyalty”', '**Confirmed** (a chapter title in the book)', 'None needed.'],
  ['al-Jāḥiẓ, Kitāb al-Ḥayawān: the passage on the translator', '**Wording confirmed**', 'Reference now gives Hārūn’s edition (2nd ed., 1965, vol. 1). The page (p. 76) comes from secondary sources and must be checked.'],
  ['al-Ṣafadī and the two Abbasid methods; Baker and Hanna (2009)', '**Confirmed**', 'Page range pp. 328–337 added.'],
  ['Farghal and Shunnaq (1999): formal, functional and ideational equivalence', '**Confirmed**', 'Publisher corrected to Dar Al-Hilal for Translation.'],
  ['Baker (2018): strategies for non-equivalence', '**Confirmed**', 'None needed.'],
  ['Newmark (1988): procedures for translating metaphors', '**Confirmed**', 'None needed.'],
  ['Fairclough (2010): “relational” approach', '**Confirmed** in general (his dialectical-relational approach)', 'None needed; an expert should still confirm Chapter 19.'],
  ['Arabterm', '**Corrected**: produced by ALECSO with GIZ', 'Citation and reference corrected.'],
  ['Pérez-González (2014); Díaz Cintas and Remael (2007, 2021); Pedersen (2011); Reiss and Vermeer (1984); Nida (1964); Toury (1995); Even-Zohar (1990); ISO 704:2022', '**Confirmed**', 'Details completed (full title of Nida, 1964).'],
  ['Gambier (2003): three relationships at the heart of AVT', '**Confirmed** through secondary sources; page not checked', 'Cited without a page number.'],
  ['O’Hagan (2007): “screen translation” thought too narrow by some', '**Not confirmed**: the reference exists, but the claim is taken from the course notes', 'Kept as cited in the course notes; please check the article.'],
  ['Díaz Cintas and Remael: subtitle line length', '**Corrected**', 'Changed to about 37–39 characters, up to 42 on streaming platforms.'],
  ['Wüster and the history of terminology (Cabré, 1999)', '**Corrected** in detail', 'Wüster’s 1931 thesis; Cabré’s four periods confirmed.'],
  ['ISO facts (1947, Geneva, English, French and Russian)', '**Confirmed**', 'None needed.'],
  ['The Arabic academies’ methods (terminology chapter)', '**Not checked** (no online source found in the time available)', 'Attributed to the team’s terminology chapter; please confirm the source Masooma used.'],
  ['All other references (Ghazala, Dickins et al., Kenny, Pym, Cabré, Mossop, Reiss, Nord 2005, Munday, Shannon and Weaver, Eco, Vinay and Darbelnet)', '**Confirmed**', 'Minor details added (full subtitle of Reiss; DOI for Pym).']],
 [34, 30, 36]],

];
