// Feedback report content. Blocks: ['h1'|'h2'|'h3', text], ['p', text], ['ul'|'ol', [..]], ['table', [headers], [[row]], [widths%]]
module.exports = [

['h1', '1. Summary'],
['p', 'This report explains how the Translation Handbook was produced from the team’s materials: what was taken from the original draft, what was changed and why, what was added, and what was left out. It also checks every request in the professor’s notes and lists what must still be done before the handbook is published.'],
['h3', 'The final handbook in brief'],
['ul', [
  'An editable Word document (Translation-Handbook.docx), about 46 pages, B5 size, in plain layout.',
  'Five parts in working order (Getting started, Understanding the text, Translating, Checking and explaining, Going further), 16 chapters, a Future editions section, practice in three levels with answers, checklists, a glossary of 57 terms, and 35 references.',
  'Written in simple English for complete beginners, with Arabic examples throughout and in-text citations in APA style.',
]],
['h3', 'Overall verdict'],
['p', 'The handbook is a **good second draft**. It can be used as an internal handout for Guild workshops after one careful review. It is **not yet ready for public publication**, for four main reasons:'],
['ol', [
  'The citations and quotations were written from memory and have not been checked against the books.',
  'The original draft does not name its sources, so some draft examples may come from a textbook that is not yet credited.',
  'Several items requested in the professor’s notes are missing or only partly done, mainly because the source materials were not supplied (see Section 4).',
  'Some good material from the draft was left out during simplification and should be reconsidered (see Section 8).',
]],

['h1', '2. The materials used'],
['h3', 'Materials received'],
['table', ['Material', 'What it contained', 'How it was used'],
 [['**Draft_one.docx** (the original draft)', 'About 730 lines of notes: definitions, Arabic–English differences, equivalence, form and meaning, types of meaning, collocation, context, idioms, literal, metaphoric and free translation, strategies, cultural approximation, descriptive translation, lexical creation, text analysis, commentary, exercises 16 and 24–29. The Terminology, AI, Glossary and References headings were empty.', 'The main source of ideas and examples. Every chapter is built on it where it had content.'],
  ['**Latest_upades_and_thoughts.docx** (the professor’s notes)', '64 lines of instructions (several repeated two or three times) on structure, new chapters, checklists, exercises, references and team tasks.', 'Used as the list of requirements. Each request is checked in Section 4.'],
  ['**The Guild logo**', 'The club logo image.', 'Used for colours in the earlier PDF versions. The final Word version uses a plain text title page.']],
 [26, 44, 30]],
['h3', 'Materials mentioned in the notes but not received'],
['ul', [
  'The **180** textbook and the **182** course book (notes, lines 26 and 64).',
  'The **386** texts and the **Analysis** texts, from which example sentences were to be extracted (line 26).',
  'The text **«الترجمة: ماهيتها»** (line 39).',
  '**Loulwah’s notes** on machine translation and dictionaries (lines 6, 13 and 56).',
  '**Dr Abdullah’s PhD research or framework**, needed for one of the checklists (line 47).',
  '“**The book**” with useful examples (line 24): its title is not given.',
  'Contributions assigned to team members: Shaikha (organisation and examples), Masooma (practice texts and the terminology chapter), Loulwah (dictionary examples).',
]],
['p', 'Anything that depended on these materials could not be done properly. In those places the handbook either has a placeholder in square brackets or uses standard published sources instead.'],

['h1', '3. How the work progressed'],
['table', ['Version', 'What changed', 'Why'],
 [['1. A5 designed PDF', 'First full layout, with a strong visual design.', 'Initial request for an A5 handbook with the logo’s theme.'],
  ['2. B5 designed PDF (35, then 44 pages)', 'New page size and a detailed design system.', 'Second specification: B5, workflow structure, design rules.'],
  ['3. Calm B5 PDF (48 pages)', 'Much simpler design, one layout for every chapter, cover without the square logo.', 'Feedback: “too complicated”, “not beginner-friendly”, “remove the square”.'],
  ['4. Beginner PDF with quotations (56 pages)', 'Added “In plain words” boxes, quotations from translation scholars, and a first-translation walkthrough.', 'Feedback: “simplify more”, “explain”, “add quotes related to translation”.'],
  ['5. Guided “toolkit” layout', 'Tried a stage-and-tool structure. Not delivered.', 'Feedback: “still too technical”. Stopped when the next instruction arrived.'],
  ['6. Word document (final)', 'Rewritten as plain text in Word; all visual elements removed; every idea cited; references at the end.', 'Feedback: “too many visual elements”, “cite and reference everything”, “I want a Word document to edit”.']],
 [26, 40, 34]],
['p', 'An honest note: several rounds were needed because early versions put design before simplicity. The final Word version follows the latest instructions, but in simplifying the text some useful draft material was removed (Section 8).'],

['h1', '4. The professor’s notes: request by request'],
['p', 'Status key: **Done**, **Partly done**, **Not done**. Repeated requests are listed once. Line numbers refer to the order of the paragraphs in the notes document.'],
['table', ['Request (notes line)', 'Status', 'Where in the handbook', 'Comment'],
 [['Organise the material, make it cohesive and remove repetition (1, 8, 17)', '**Done**', 'Whole book', 'The draft repeated several topics two or three times (equivalence, denotation and connotation, collocation, idioms, descriptive translation). Each now appears once.'],
  ['Add missing translation strategies (2, 9, 18)', '**Done**', 'Chapters 8 and 9', 'Added: search for an existing term, a more general word, borrowing with explanation (Baker), domestication and foreignisation (Venuti). The draft’s strategies were kept.'],
  ['Add missing types of translation (2, 9, 18)', '**Partly done**', 'Chapter 1', 'Translation vs interpreting is covered. Sight translation, subtitling and localisation were in the PDF versions but were removed from the Word version. They should be restored (Section 8).'],
  ['New chapter: the seven translation procedures (3, 10, 19, 44)', '**Done**', 'Chapter 7', 'Vinay and Darbelnet’s seven procedures, with examples and one sentence showing several procedures.'],
  ['Add to the cultural approximation chapter (4, 11, 20)', '**Done**', 'Chapter 9', 'Expanded with metaphor steps, climate and meaning, greetings, titles and domestication/foreignisation.'],
  ['Definitions in every chapter; all terms in the glossary (5, 12, 21, 53)', '**Done**', 'All chapters; Glossary', 'Every key term is in bold, defined in its chapter and listed in the glossary (57 terms). Some minor terms from the draft are not in the glossary.'],
  ['Chapter on machine translation and AI (6, 13, 22)', '**Done**', 'Chapter 13', 'Written from general knowledge and Kenny (2022). Loulwah’s notes were not received.'],
  ['Final section of exercises in three levels, applying theories, genres and checklists (16)', '**Done**', 'Practice', 'Level 1 sentences, Level 2 short texts, Level 3 full texts, with answers. Not all genres are practised.'],
  ['Use examples from “the book” (24)', '**Not done**', '–', 'The book was not identified or supplied.'],
  ['Add authentic news texts (25, 59)', '**Not done**', 'Practice, Level 3', 'The two news texts were written for the handbook and are labelled as such. Authentic texts could not be downloaded (news websites were blocked in the working environment). The team should replace them.'],
  ['Extract sentences from the Analysis, 180 and 386 texts (26)', '**Not done**', '–', 'These texts were not supplied.'],
  ['Include examples from poetry (27)', '**Done**', 'Chapter 15; Practice 2b and 2c', 'al-Mutanabbi and Shakespeare’s Sonnet 18.'],
  ['Include the main genres, with at least one example each (28, 29)', '**Done**', 'Chapter 15', 'Eight genres, each with an English–Arabic example.'],
  ['Tips, advice, techniques and preparation at the start (30)', '**Done**', 'Chapters 1 and 2', 'Includes a step-by-step first translation.'],
  ['Practical checklists (31)', '**Done**', 'Checklists section', 'Before, while and after translating, and for the commentary.'],
  ['Who is the client? Purpose? Target audience? (32–35)', '**Done**', 'Chapter 2', 'The three questions form the translation brief.'],
  ['Chapter on terminology management and terminology guides (36, 62)', '**Partly done**', 'Chapter 10', 'Combined with dictionaries. Note: line 62 assigns this chapter to Masooma, so her work should be merged in.'],
  ['Interlingual risk assessment matrix (37)', '**Partly done**', 'Chapter 12', 'Given as a list of eight risk areas with advice. It is not laid out as a matrix, because tables were removed in the final simplification. A simple matrix could be added back.'],
  ['Audiences and materials for future editions (38)', '**Not done**', 'Future editions', 'A placeholder with suggestions. Only the team knows its plans.'],
  ['Cite anything from «الترجمة ماهيتها» and attribute it to Dr Yusuf (39)', '**Not done**', 'References (placeholder)', 'The text was not supplied, so nothing in the handbook is taken from it. See Section 9: the notes name Dr Yusuf, but the name was removed on your instruction.'],
  ['Chapter on text analysis (40)', '**Done**', 'Chapter 2', 'Merged with preparation, because analysis is part of getting ready.'],
  ['Chapter on translation commentary, including how to analyse a translation (41)', '**Done**', 'Chapter 14', 'Five steps and an example. The draft’s two-part structure was not kept (Section 8).'],
  ['Chapter on printed and digital dictionaries (42)', '**Partly done**', 'Chapter 10', 'A short section inside Chapter 10, not a full chapter.'],
  ['Fairclough’s relational model (45)', '**Partly done**', 'Chapter 16', 'Explained as three levels (text, production, society). An expert should confirm this matches the “relational” version the professor means.'],
  ['Three checklists based on Dr Abdullah’s framework and Fairclough’s model (46–48)', '**Not done**', '–', 'Dr Abdullah’s framework was not supplied. A Fairclough checklist was not made as a separate list.'],
  ['Collect examples from books, poetry, proverbs, idioms and text types, with sources cited (52)', '**Partly done**', 'Chapters 4, 9 and 15', 'Examples were added, but some come from the draft without a known source (Section 9).'],
  ['Common grammatical and stylistic mistakes: in each chapter or a separate section? (60)', '**Done**', 'Chapter 11', 'Decision taken: one section inside the revision chapter, for both directions.'],
  ['Answer key with explanations (61)', '**Done**', 'Answers; “Try it” sections', 'Every answer has a short explanation.'],
  ['Table of contents and final structure (58)', '**Done**', 'Contents page', 'The contents page updates in Word (right-click, “Update Field”).'],
  ['References for the 180 book, the 182 course book and all other sources (64)', '**Partly done**', 'References', '35 published sources are listed. The 180 and 182 books are placeholders because their details were not supplied.'],
  ['Keep the Arabic version for future use (50)', '**Not applicable**', '–', 'This handbook is in English with Arabic examples. No separate Arabic version was produced.']],
 [29, 14, 18, 39]],

['h1', '5. The original draft: section by section'],
['p', 'For each section of the draft: what was kept, what was changed, what was left out, and why.'],
['table', ['Draft section', 'Kept', 'Changed', 'Left out, and why'],
 [['Definitions and abbreviations', 'SL, TL, translation, interpretation, idiom, literal translation.', 'Empty definitions (form, meaning, interpretation, interlingual) were filled in. “SL/TL” became “source/target language”, which beginners understand more easily.', 'SLC, TLC and TS: not used anywhere else. “Principles = Foundations”: unclear. Intralingual: not needed for beginners.'],
  ['Arabic vs English', 'SVO vs VSO (start with the verb), sentence length, repeated synonyms, تُعدّ for “is”, formal vs dialect.', 'Moved to Chapter 5 and rewritten as two simple step lists (EN → AR and AR → EN). Added gender of “you”, numbers 3–10, linking words and capital letters.', '“Arabic is compositional, English is compounding”: an oversimplification. قاضي/قاضية and نائب/نائبة: قاضية and نائبة are now normal in Modern Standard Arabic, so the rule could mislead. “He is in bed”, “As an officer”, “Roman ruins”, “Shops stay open”, “Eventually”: removed in the final simplification (they were in the PDF versions; see Section 8). Classical Arabic: removed for simplicity.'],
  ['Objectives of the book', 'The aims (rules, differences, difficulties, solutions).', 'Turned into “How to use this handbook”.', '–'],
  ['Translation, translator and how to translate', 'Translation as transferring meaning; approximation; commissioned vs self-initiated translator; client ideology and policy; walking encyclopedia; linguistic repertoire; bilingual and bicultural; always revise; translation is rewriting.', 'Definition now quoted and cited (Newmark, 1988). A freelancer is explained as a commissioned translator.', '“Translation also means to politicize”: “politicize” is the wrong word and the idea is unclear. Communication elements (sender, receiver, channel, noise…): theory-heavy for beginners. Breaking a paragraph into sentences, phrases and words: removed for space, but it is useful (Section 8). “Minefield” image, fidelity (الأمانة), “faithful, accurate and acceptable”: removed in the Word version and should be restored (Section 8).'],
  ['Equivalence', 'Formal, functional and ideational equivalence, with the “dead letter” and “second to none” examples.', 'Repetition removed (the draft explained it three times). Attributed to Farghal and Shunnaq (1999). Formal/functional/ideational now given in a clear order of choice.', '“Think outside the box” examples: removed for space.'],
  ['Form vs meaning', 'Meaning over form; you may change the form but never the meaning; the Blair example.', '“Bush’s puppy” changed to “Bush’s poodle”, the phrase actually used in the British press. The draft line “a clearer example that form is more important than meaning” contradicts the rule and was corrected.', 'Arabic alternatives “حروف أو غنمة” (a typo for خروف): not suitable for a formal handbook.'],
  ['Types of meaning', 'Denotation and connotation; die / pass away; kill / assassinate.', 'The draft’s example “Died = قتل” is wrong (قتل means “killed”); corrected to مات.', 'Steed/horse/mule and comrade: removed for space. “Kick the bucket”: see Section 6.'],
  ['Sentence vs speaker meaning', 'أشعر بالحر = “turn on the air conditioning”.', 'Added an English example: “It’s freezing in here.”', '–'],
  ['Collocation', 'Definition (“the company a word keeps”), pay attention, pay a visit, close friend, يساورني القلق, strong tea, fast colour.', 'The definition is Firth’s famous line and is now cited (Firth, 1957). “Pay attention” is translated as ينتبه instead of أعرني انتباهك.', 'Pay money, pay respect, close cooperation, استل سيفه: removed for space.'],
  ['Context; homonymy and polysemy', 'Context decides meaning; لكل مقام مقال; bank, عين, case.', '–', 'Micro vs macro context, the translation triangle, and the terms homonymy and polysemy: removed as too technical for beginners. Micro/macro context could be restored in simple words (Section 8).'],
  ['Idioms', 'Definition; raining cats and dogs; over the moon; spill the beans; I’m all ears; break a leg; كالمستجير من الرمضاء بالنار; warmed my heart.', 'Examples that are really collocations or terms (pay a visit, strong tea, governing law) were moved to the collocation and terminology chapters. Two Arabic proverbs were added.', '“A piece of cake” (idiomatic vs literal meaning): a very good example, removed by mistake; should be restored. Pull one’s socks up, mocktail/cocktail, boys are boys, business is business, hit the sack: removed for space.'],
  ['Literal translation', '“It has been a long day”, pay a visit, play a role; literal translation can succeed or fail.', 'Combined with free translation in Chapter 6.', '“What are you wearing on your biggest day?” → يوم زفافك: a good cultural example, removed for space.'],
  ['Metaphoric translation', 'Metaphor vs simile; she is a snake → إنها أفعى; tip of the iceberg → غيض من فيض; plain meaning as the last option.', 'The steps now follow Newmark (1988): keep the image, use a local image, turn it into a simile, give the plain meaning. The draft’s example “she is a snake → إنها كالثعلب” contradicts its own previous line and was replaced.', 'My thoughts evaporate, my paper will see light, raises the brows, rhetoric keywords: removed for space.'],
  ['Free translation', '“Equal opportunity” → بعيداً عن المحسوبية والواسطة; “heavy rainfall” example.', 'The handbook presents the heavy-rainfall example as **too free**, because it adds a new idea. The draft seems to present it as an ordinary example. The professor should decide (Section 9).', 'Examples 1 (Covid) and 4 (parents): they add meaning that is not in the source, which could confuse beginners.'],
  ['Translation strategies', 'Literal/idiomatic, functional, cultural substitution (Romeo and Juliet → قيس وليلى), addition (EN → AR), omission (AR → EN), explanatory translation as the last option.', 'Spread across the chapters where each is used (5, 6, 8 and 9) and cited to Baker (2018).', '“Kick the bucket”, “kick the chair”, “mark my words”, “key word”: see Section 6. Omission “when we want to be polite”: dropped for simplicity.'],
  ['Second strategies section (terms, Arabicization)', 'Terms convey complex concepts; translators sometimes coin words.', 'Moved to Chapters 8 and 10.', '“The Jordanian Academy has 74 specialised fields”: could not be verified.'],
  ['Exercises 16 and 24–29', 'Fast colour → لون ثابت; the Home Office; Chancellor of the Exchequer; Secretary of State; scapegoat; cut from the same cloth; break a leg.', 'The Home Office: the draft first says وزير الداخلية (minister) and then corrects it to وزارة الداخلية (ministry) in Exercise 28; the handbook uses the ministry.', 'Most exercise items (readable book, addled egg, sheriff, watchdog press, sleep like a log…): not used. They are good practice material and could form an extra exercise section. Social expressions: see Section 6.'],
  ['Cultural approximation', 'Definition; warmed my heart; titles; scapegoat; cut from the same cloth.', 'Expanded into Chapter 9.', '“Test in the bag” and “like mother, like daughter”: in the PDF versions, removed from the Word version; should be restored. “As busy as a bee = زي أم العروس”: colloquial. “Death is the great leveller = كل نفس ذائقة الموت”: uses a Qur’anic verse as an equivalent, which is sensitive and not an exact match. “Big sins = الكبائر”: “big sins” is not a set English phrase. Every Jack has his Jill, intern, scandal, Clinton example: removed for space.'],
  ['Descriptive translation', 'Definition; zakat; tayammum; the basmala; ʿidda; transliterate first, then describe; brackets or footnotes; last option.', 'Merged into Chapter 8 with lexical creation, because both solve the same problem.', 'Sectioning, Atwah (Jordan), Yin-Yang, القرقرة, الحوقلة: removed for space. The draft’s meaning for القرقرة (“the loudest laughter”) is doubtful.'],
  ['Lexical creation', 'Definition; calque, neologism, transliteration, hybrid; smartphone, blog, cybersecurity, greenwashing, cancel culture, waqf.', 'Presented as the last step after searching for an existing term.', 'Shadow government, co-wife, Valentine’s Day, Thanksgiving, sukuk, istitaba, CD: removed for space. Tribocracy, puppycracy, patriocracy: not established words.'],
  ['Analysing a text', 'Why analyse; highlight difficult words; analysis vs summary; the checklist (author, terms, field, publisher, tone, style, strategies, audience); the KUNA example; analysis → translation → commentary.', 'The checklist became six plain questions. Cited to Nord (2005) and Newmark (1988).', '“KUNA has biased views”: a public handbook should not say that a named agency is biased. “Australia” purpose, “Government Rents”, “Linguistic Applications”: unclear. “Titles as short as possible, no addition in titles”, “quality + speed = productivity”, “protect your reputation”: removed in the Word version; the title rules should be restored.'],
  ['Commentary on translation', 'State the problem and the solution; use examples; write in the third person; name the strategies; mention dictionaries; justify decisions.', 'Organised into five steps with a worked example. Cited to Dickins et al. (2016).', 'The two-part structure (reflect on the analysis, then on the translation) and the WH-questions tip: should be restored (Section 8).'],
  ['Terminology; AI and machine translation; Glossary; References', 'Nothing (empty headings).', 'Written in full: Chapters 10 and 13, the glossary and the references.', '–']],
 [16, 24, 28, 32]],

['h1', '6. Corrections to the draft'],
['p', 'These draft items were wrong, inconsistent or unsuitable for a published handbook. The handbook corrects or removes them.'],
['table', ['Draft says', 'Handbook says or does', 'Reason'],
 [['Died = قتل (denotative meaning)', 'die = مات', 'قتل means “killed”, not “died”.'],
  ['Kick the bucket = يموت كالحقير', 'Removed', '“Kick the bucket” is informal and humorous, not insulting. The Arabic adds an insult that is not in the English.'],
  ['“A clearer example that form is more important than meaning” (مثال أوضح على أن البناء أهم من المعنى)', 'Meaning is more important than form', 'The draft’s own rule is that meaning comes first. The line is a slip.'],
  ['she is a snake → إنها كالثعلب (as an unshared metaphor)', 'Replaced with “the tip of the iceberg → غيض من فيض”', 'The line before says the snake metaphor is shared (إنها أفعى), so the example contradicts itself.'],
  ['Idiom examples: pay a visit, strong tea, governing law', 'Moved to collocations and terms', 'These are collocations and a legal term, not idioms.'],
  ['Blair: Bush’s puppy', 'Blair, Bush’s poodle', '“Poodle” is the word actually used in the British press.'],
  ['Governing law → القانون المطبق', 'القانون الواجب التطبيق', 'Both are used. The handbook form is the one most common in Arabic contracts. The team may prefer to keep the draft’s form.'],
  ['Jet lag → إعياء الطيران', 'إرهاق السفر', 'Both are possible. إرهاق السفر is more common. Optional change.'],
  ['mark my words = فل تتذكر وعدي / كلامي', 'Removed', 'Contains a typo, and “mark my words” means “remember what I said”, not a promise.'],
  ['Sorry to hear your loss = تعيش انت، شعبان مات; Welcome = أهلاً أهلاً زارنا النبي; What the hell are you talking = اتق الله يا شيخ', 'Replaced with عظّم الله أجركم and أهلاً وسهلاً، شرّفتمونا', 'The draft forms are Egyptian colloquial; one mentions the Prophet in a casual way, and one does not match the English register. The replacements suit Gulf and formal use.'],
  ['UnIslamic ideology / Islamic ideology (suicide bomber example)', '“The choice depends on the client’s policy”', 'The original labels take a religious and political position. A public handbook should stay neutral and teach the principle.'],
  ['Publisher KUNA has biased views', 'Removed', 'A published handbook should not describe a named organisation as biased.'],
  ['“Translation also means to politicize (الدبلوماسية)”', 'Removed', '“Politicize” means to make something political. The idea (diplomatic wording) is not a definition of translation.'],
  ['Arabic is compositional (derivational), English is compounding', 'Removed', 'An oversimplification: both languages use derivation and compounding.'],
  ['Spelling errors: Freedome, phsycatery, vailate, Taxasion, imbedded/imbibed, hit the sac, Don’t put words on me, Matchful', 'Corrected or removed', 'Proofreading.']],
 [34, 26, 40]],

['h1', '7. What was added that is not in the draft'],
['table', ['Added content', 'Where', 'Source or reason'],
 [['Quotations and definitions from translation scholars', 'Chapters 1–7, 10, 16', 'Newmark (1988); Nida and Taber (1969); Jakobson (1959); Firth (1957); Eco (2003); Jerome; al-Jāḥiẓ. Added because you asked for quotations related to translation.'],
  ['Citations for the draft’s ideas', 'Throughout', 'Formal/functional/ideational equivalence: Farghal and Shunnaq (1999). Strategies and connotation: Baker (2018). Metaphor steps: Newmark (1988). Brief and text analysis: Nord (1997, 2005). Commentary: Dickins et al. (2016). These are standard sources, but they are my matches, not the team’s original sources.'],
  ['Chapter 7: the seven procedures', 'Chapter 7', 'Requested in the notes. Vinay and Darbelnet (1958/1995). Examples mostly mine (computer, skyscraper, after his arrival, it is not difficult, like father like son); Romeo and Juliet is from the draft.'],
  ['Chapter 10: terms and dictionaries', 'Chapter 10', 'Requested in the notes. Cabré (1999); Samuel Johnson via Piozzi (1786). Dictionary list is mine.'],
  ['Chapter 11: revision and common mistakes', 'Chapter 11', 'Requested in the notes (common mistakes). Mossop (2014). The mistakes list is mine, based on the draft’s rules.'],
  ['Chapter 12: spotting risks', 'Chapter 12', 'Requested in the notes (risk matrix). Pym (2015). The eight risk areas are mine; Persian/Arabian Gulf and governing law come from the draft.'],
  ['Chapter 13: machine translation and AI', 'Chapter 13', 'Requested in the notes. Kenny (2022). The draft’s point that post-editing is the new direction for translators is reflected in the chapter.'],
  ['Chapter 15: types of text', 'Chapter 15', 'Requested in the notes (genres). Reiss (2000). All eight examples are mine except al-Mutanabbi and “a long day”.'],
  ['Chapter 16: language and ideology', 'Chapter 16', 'Requested in the notes (Fairclough). Fairclough (1989, 1992). The suicide-bomber example is from the draft; regime/government and the passive example are mine.'],
  ['“Your first translation, step by step”', 'Chapter 1', 'Added to show a beginner the whole process on one sentence.'],
  ['“Try it” exercises with answers', 'Most chapters', 'Added so that readers can check their understanding.'],
  ['New examples', 'Various', 'He is a heavy smoker; It’s freezing in here; prawns/shrimps; He is a rock; He is a chicken; the summer/spring Shakespeare example; عظّم الله أجركم and other greetings; the doctor said she; shall in contracts; two Arabic proverbs; al-Ṣafadī and the Abbasid translators.'],
  ['Practice section', 'Practice', 'UN Declaration Article 1 (United Nations, 1948), al-Mutanabbi, Shakespeare, and two practice texts written for the handbook. Level 1 sentences use draft examples.'],
  ['Checklists, glossary and references', 'End of the book', 'Requested in the notes.'],
  ['Future editions placeholder', 'After Chapter 16', 'Requested in the notes; content must come from the team.']],
 [28, 18, 54]],

['h1', '8. Content left out that should be reconsidered'],
['p', 'While simplifying the text for the Word version, some useful material was removed. Most of it was present in the earlier PDF versions. I recommend restoring the items marked “Restore”.'],
['table', ['Item', 'Recommendation', 'Where it would fit'],
 [['Fidelity (الأمانة) and the goal “faithful, accurate and acceptable”', '**Restore**', 'Chapter 1, “What makes a good translator?”'],
  ['Translation as communication (understanding and being understood)', '**Restore** (one sentence)', 'Chapter 1'],
  ['Types of translation work: sight translation, subtitling, localisation', '**Restore**', 'Chapter 1 or Chapter 15'],
  ['“A piece of cake”: idiomatic vs literal meaning depends on context', '**Restore**', 'Chapter 4, “A simple test”'],
  ['Small words: He is in bed → نائم; As an officer → بصفتي ضابطاً; to see the Roman ruins → لزيارة', '**Restore**', 'Chapter 5'],
  ['Classical Arabic as a third type of Arabic', '**Restore** (one line)', 'Chapter 5, “Which Arabic?”'],
  ['Break the text into sentences, phrases and words', '**Restore**', 'Chapter 2'],
  ['Micro and macro context, in simple words', 'Consider', 'Chapter 3'],
  ['“What are you wearing on your biggest day?” → يوم زفافك', 'Consider', 'Chapter 6'],
  ['“Test in the bag” and “like mother, like daughter”', '**Restore**', 'Chapter 9'],
  ['Titles: keep them short; no additions in titles; translate captions', '**Restore**', 'Chapter 11 or 12'],
  ['Commentary in two parts: reflect on the analysis, then on the translation', '**Restore**', 'Chapter 14'],
  ['Unused exercise items from the draft (exercises 16, 24–29)', 'Consider', 'An extra practice section'],
  ['A simple risk matrix (risk × how serious × what to do)', 'Consider', 'Chapter 12']],
 [44, 23, 33]],

['h1', '9. Points for the team to decide'],
['ol', [
  '**Dr Yusuf.** The professor’s notes (line 39) say that anything from «الترجمة: ماهيتها» should be attributed to Dr Yusuf. During the work you told me that there is no Dr Yusuf, so the name was removed. Please confirm the correct author, because a wrong or missing attribution is a serious problem in a published book.',
  '**Sources of the draft’s examples.** The draft does not say where its material came from, and the professor’s notes mention material “collected from more than one source”. In the handbook these examples are credited to the “Translation Team course materials”. If any come from a textbook (for example the 180 or 182 books), that book must be credited instead.',
  '**Free translation.** Should “We have had heavy rainfall this winter → سيكون لدينا موسم زراعي مبشر” be shown as acceptable free translation or as too free? The handbook currently says it is too free.',
  '**Preferred Arabic forms.** Governing law: القانون المطبق (draft) or القانون الواجب التطبيق (handbook)? Jet lag: إعياء الطيران or إرهاق السفر?',
  '**Dialect in examples.** Some Gulf expressions are used (الله يعطيك العافية، عساكم من عُوّاده). Keep them, label them as Gulf spoken Arabic, or replace them with formal Arabic?',
  '**Fairclough.** Confirm whether the three levels in Chapter 16 match the “relational model” the professor means.',
  '**Team contributions.** Merge the work assigned to Shaikha, Masooma and Loulwah, especially the terminology chapter and the practice texts.',
]],

['h1', '10. Before publishing: checklist'],
['ol', [
  'Check every quotation, page number and reference against the original book.',
  'Confirm the sources of all draft examples, and credit them correctly.',
  'Add the full references for the 180 and 182 books and «الترجمة: ماهيتها».',
  'Add Dr Abdullah’s framework and the checklist based on it.',
  'Replace the two written practice news texts with authentic news texts, with their sources.',
  'Restore the items marked “Restore” in Section 8.',
  'Have a qualified Arabic–English translator proofread every Arabic example.',
  'Open the file in Microsoft Word, update the contents page and check the layout (it was previewed in LibreOffice).',
  'Add a copyright page, the names of the editors and contributors, and acknowledgements.',
  'Ask the supervisor and Dr Amin for feedback, as planned in the notes (line 57).',
  'Check the publisher’s and the university’s rules on declaring AI assistance, and add a statement if required.',
]],
];
