// Final report on the Translation Handbook: what was changed, what was added, the reference check, and what must be verified.
module.exports = [

['h1', '1. About this report'],
['ul', [
  'This report summarises the final state of the Translation Handbook ({{دليل الترجمة}}) before publication.',
  'It lists what was changed and edited, what was added that was not in the team’s Word documents, the result of the reference check, and the points the team must verify before publication.',
  'Points that must still be verified are printed in **red** in Section 6.',
  'The full detail of every correction is in the Correction Log; the full account of editorial decisions is in the Editorial Report.',
]],

['h1', '2. The handbook today'],
['ul', [
  'A guide for complete beginners in English–Arabic translation, written in English with examples in both languages.',
  '96 pages, B5 size, in two editions with identical content: the **Midnight** edition (dark cover) and the **Light** edition (pale cover), each as an editable Word file and a PDF.',
  '9 parts and 27 chapters, ordered from the basics to the most specialised topic (audiovisual translation).',
  'Back matter: abbreviations, further reading, a glossary of 110 terms, 38 references, and a page with the QR code of the team’s website.',
  'Every chapter follows the same guided pattern: **Where we are** → numbered **steps** (problem first, then solution) → **Try it** with answers → **Remember** and **Words to remember**.',
]],

['h1', '3. What was changed and edited'],
['h2', '3.1 Structure'],
['ul', [
  'The chapters follow the professor’s chapter list, ordered from easy to hard in 9 parts.',
  'Material that the draft repeated in several places was merged, so that each topic appears once.',
  'A new opening, **Start here**, explains to a complete beginner what a translator does, the four steps of every translation and the journey through the book.',
  'Every chapter was rewritten as a step-by-step guide. Each idea is explained with an example before its technical name is given.',
  'The key terms moved from the start to the end of each chapter (**Words to remember**).',
  'The abbreviations moved to the back of the book; the acknowledgements now close the preface.',
]],
['h2', '3.2 Content removed'],
['ul', [
  'The practice section (three levels of practice texts) and its answer key. Every chapter keeps its **Try it** exercise with answers.',
  'The four checklists at the end of the book, and the note on future editions.',
  'Scholars’ names in the running text. Each borrowed idea keeps its short citation in brackets, and all sources remain in the References.',
  'The italic descriptions under each part heading, and about a third of the running text (repetitions, filler and long explanations), to make the pages lighter.',
  'Specialist theory not needed by beginners (for example, the history of terminology and most audiovisual translation theories).',
  'All placeholders in square brackets, the empty checklist for Dr Abdullah’s framework, the names of reviewers who had not yet reviewed the book, and all mentions of the Guild Season.',
  'Draft examples that were wrong, unclear or not neutral (listed in the Editorial Report, Section 7).',
]],
['h2', '3.3 Corrections'],
['ul', [
  'Two full expert reviews in English and Arabic: **192 corrections** in the first review and **102** in the final review, after the guided rewrite.',
  'Main areas: definitions and concepts, Arabic grammar and terminology, examples that did not illustrate their point, consistency between chapters, cross-references, English, neutrality and citations.',
  'Examples of important corrections: commissioned vs self-initiated translators; the rule on Arabic word order; how to translate the verb _is_; the explanations of zakat and tayammum; the Arabic terms for lexical creation, form and modulation; the definition of a terminologist; the presentation of {{انتحاري}} and {{استشهادي}}; the definition of spotting in subtitling.',
  'After each review, every Arabic example and every citation was checked automatically: none were lost, every citation matches a reference, and every reference is cited.',
]],
['h2', '3.4 Design and layout'],
['ul', [
  'Two cover designs chosen by the team (Midnight and Light), with the club’s own logo taken from the logo file.',
  'The website QR code was rebuilt at high resolution with the club logo in the centre, printed on both back covers and on the last page inside the book. It was test-scanned on the final PDFs.',
  'Inside pages: generous spacing, roman page numbers for the front pages, a running head with the book title and the current part, and each chapter on a new page.',
]],

['h1', '4. What was added that was not in the team’s Word documents'],
['p', 'The team’s Word documents are the original draft (Draft_one), the professor’s notes (Latest updates and thoughts), the terminology chapter and the audiovisual translation notes. The items below were not in any of them.'],
['h2', '4.1 Added from Shaikha’s notes'],
['p', 'These additions come from Shaikha’s study notes. Where an idea comes from a published work, it is credited to that work in the text.'],
['ul', [
  '**Chapter 1:** the three kinds of translation (within one language, between languages, into another medium) (Jakobson, 1959); the translator as a reader before being a writer.',
  '**Chapter 3:** how to translate the English verbs _be_, _do_ and _have_; the Arabic dual; how to find the gender of _I_ and _you_ from clues in the text.',
  '**Chapter 5:** problems with single words: lexical gaps ({{ثكلى}}), false equivalents ({{الهنود الحمر}}) and rare words ({{شبر}}) (Baker, 2018).',
  '**Chapter 6:** the example {{خط}} for a word with several meanings.',
  '**Chapter 7:** one English verb with several Arabic equivalents (_deliver a letter, a speech, the news, a blow, a verdict_).',
  '**Chapter 8:** fixed expressions, how to spot an idiom, five ways to translate an idiom (Baker, 2018), and three more idioms (_bury the hatchet, in a nutshell, the long and the short of it_).',
  '**Chapter 13:** Arabic words borrowed into English (_algebra, algorithm, hijab_).',
  '**Chapter 16:** more examples of Arabicisation ({{استراتيجية}}, {{تكنولوجيا}}).',
  '**Chapter 18:** translating news headlines, the structure of news stories (the inverted pyramid, hard and soft news), and technical and literary texts.',
  '**Chapter 21:** medical examples of specialised terms (_allergic, allergen, contact eczema_).',
  '**Chapter 22:** translation memory, termbases and CAT tools, how machine translation has developed, and localisation.',
  '**Chapter 26:** the Arabic dubbing of _The Simpsons_ as an example of cultural adaptation.',
]],
['h2', '4.2 Written for the handbook'],
['p', 'These parts were written for the handbook, using the published sources in the References. Some cover topics that the professor’s notes asked for but that the Word documents did not contain.'],
['ul', [
  '**Front and back matter:** the copyright page, **Start here**, the further reading list, the glossary, the references and the website page.',
  '**In every chapter:** **Where we are**, the numbered steps, **Try it** with answers, **Remember** and **Words to remember**.',
  '**Chapter 1:** sight translation and localisation as types of translation.',
  '**Chapter 2:** the worked example of a first translation, step by step.',
  '**Chapter 3:** the gender and number of _you_, numbers from three to ten, linking words and Arabic punctuation.',
  '**Chapter 12:** the seven translation procedures, with examples (requested in the notes; the draft had no content).',
  '**Chapter 13:** further strategies (a more general word, a more neutral word, paraphrase, loan word with explanation, compensation, domestication and foreignisation) (requested in the notes).',
  '**Chapter 18:** eight genres, each with an example (requested in the notes).',
  '**Chapter 19:** words and points of view, with three practical questions (requested in the notes).',
  '**Chapter 20:** printed and digital dictionaries (requested in the notes).',
  '**Chapter 22:** a worked post-editing example and advice on using AI tools well.',
  '**Chapter 23:** the lists of common mistakes in both directions (requested in the notes).',
  '**Chapter 24:** the interlingual risk matrix (requested in the notes).',
  '**Chapter 26:** first steps for beginners in audiovisual translation.',
  '**Chapter 27:** a step-by-step subtitling method, a worked example of condensing a line, rules for Arabic subtitles, and subtitle timing.',
]],

['h1', '5. References: what was checked'],
['p', 'All 38 references and every direct quotation were checked twice against published information found online: once in the first review and again in the final review. The printed books themselves could not be consulted, so some points still need the books.'],
['table', ['Reference', 'First check', 'Double check', 'Result'], [
  ['Baker (2018); Baker & Hanna (2009)', 'Checked', 'Checked', 'Confirmed; page range of Baker & Hanna added'],
  ['Cabré (1999)', 'Checked', 'Checked', 'Confirmed'],
  ['Dickins et al. (2016)', 'Checked', 'Checked', 'Confirmed'],
  ['Eco (2003)', 'Checked', 'Checked', 'Confirmed; the quoted phrase is the book’s title'],
  ['Fairclough (1992)', 'Checked', 'Checked', 'Confirmed; quotation changed to a paraphrase'],
  ['Farghal & Shunnaq (1999)', 'Checked', 'Checked', 'Confirmed; publisher corrected'],
  ['Firth (1957, p. 11)', 'Checked', 'Checked', 'Confirmed'],
  ['Ghazala (2008)', 'Checked', 'Checked', 'Confirmed'],
  ['Jakobson (1959, p. 236)', 'Checked', 'Checked', 'Confirmed'],
  ['Mossop (2014); Nord (1997); Nord (2005)', 'Checked', 'Checked', 'Confirmed; the Nord (2005) citation moved to the idea it supports'],
  ['Newmark (1988)', 'Checked', 'Checked', 'Confirmed; one quotation now cited with its page (p. 11)'],
  ['Nida & Taber (1969, p. 12)', 'Checked', 'Checked', 'Confirmed; one paraphrase has no page'],
  ['Pym (2015); Venuti (1995); Wehr (1994)', 'Checked', 'Checked', 'Confirmed'],
  ['Reiss (1971/2000)', 'Checked', 'Checked', 'Confirmed; original date added'],
  ['Reiss & Vermeer (1984)', 'Checked', 'Checked', 'Confirmed'],
  ['Díaz Cintas & Remael (2007, 2021); Pedersen (2011); Pérez-González (2014)', 'Checked', 'Checked', 'Confirmed; both editions of Díaz Cintas & Remael are cited'],
  ['Gambier (2003)', 'Checked', 'Checked', 'Confirmed; DOI added; no page number'],
  ['Kenny (2022)', 'Checked', 'Checked', 'Confirmed; DOI added'],
  ['Vinay & Darbelnet (1958/1995)', 'Checked', 'Checked', 'Corrected: “Eds. & Trans.”'],
  ['Shakespeare (1609)', 'Checked', 'Checked', 'Corrected: original title of the 1609 edition'],
  ['Jerome (395/2012)', 'Checked', 'Checked', 'Corrected: page range of the chapter added; the page of the quotation is still needed'],
  ['Johnson (1784/1897, p. 309)', 'Corrected', 'Checked', 'Needs more work: confirm the page and the section of the book'],
  ['al-Jāḥiẓ (1965)', 'Checked', 'Checked', 'Needs more work: page number of the quotation'],
  ['al-Mutanabbi (n.d.)', 'Checked', 'Checked', 'Needs more work: edition, editor, publisher and year'],
  ['Academy of the Arabic Language in Cairo (n.d.)', 'Checked', 'Corrected', 'Needs more work: edition and year of al-Muʿjam al-Wasīṭ'],
  ['Baalbaki (n.d.)', 'Checked', 'Checked', 'Needs more work: edition and year of Al-Mawrid'],
  ['Oxford collocations dictionary (2009)', 'Checked', 'Checked', 'Needs more work: the editor could be named first'],
  ['ALECSO & GIZ (n.d.)', 'Corrected', 'Checked', 'Needs more work: confirm GIZ or BMZ as co-publisher'],
  ['United Nations (n.d.), UNTERM', 'Checked', 'Checked', 'Confirmed'],
  ['Translation Team (n.d.)', 'Checked', 'Corrected', 'Needs more work: unpublished course materials; confirm the wording of quoted definitions'],
], [34, 13, 14, 39]],

['h1', '6. To verify before publication'],
['p', 'The team should check the following points before the handbook is published.'],
['h2', '6.1 Language'],
['redul', [
  'A native Arabic-speaking specialist must read the final PDF from beginning to end, with special attention to Chapters 3, 5, 18, 22 and 27, where new material was added.',
  'Confirm the preferred Arabic forms: “governing law” ({{القانون الواجب التطبيق}} or {{القانون المطبَّق}}) and “jet lag”.',
  'Decide whether to keep the few colloquial expressions, which are labelled as colloquial, or use only formal Arabic.',
]],
['h2', '6.2 Sources'],
['redul', [
  'Check the 30 points in Section 5 of the Correction Log against the printed books.',
  'Add the page numbers of the al-Jāḥiẓ and Jerome quotations, and of the Nida & Taber paraphrase (usually p. 4).',
  'Confirm the page and section of the Johnson letter in _Johnsonian miscellanies_ (vol. 2).',
  'Give the edition and year of al-Muʿjam al-Wasīṭ, Al-Mawrid and the Dīwān of al-Mutanabbi used by the team.',
  'Confirm whether the chapters citing Díaz Cintas & Remael (2007) should cite the 2021 edition instead.',
  'Confirm the wording of the definitions quoted from the team’s course materials (Translation Team, n.d.).',
  'Confirm the original sources of the draft’s own examples. If any come from a published book (for example the 180 or 182 textbooks), that book must be credited.',
]],
['h2', '6.3 Decisions and details'],
['redul', [
  'Confirm the club’s official name: it appears in three slightly different forms (title page, copyright line and reference entry).',
  'Confirm the copyright line and that the statement on AI assistance meets the university’s and the publisher’s rules.',
  'Decide the final English title (“Translation Handbook” or “Translator’s Equipment”) and whether to publish one edition or both.',
  'Decide whether the three practical questions in Chapter 19 are enough for the professor’s “relational model”.',
  'Materials not received: Dr Abdullah’s framework, the text {{الترجمة: ماهيتها}} and its author, the 180, 182, 386 and Analysis texts, and Loulwah’s notes. Decide whether they belong in this edition or a later one.',
  'Before printing: open the Word file in Microsoft Word and update the contents page; then print a test copy and scan the QR code with several phones, including the light-on-dark code on the Midnight edition.',
]],
];
