// Final report on the Translation Handbook: what was changed, what was added, the reference check, and what must be verified.
module.exports = [

['h1', '1. About this report'],
['ul', [
  'This report summarises the final state of the Translation Handbook ({{دليل الترجمة}}) before publication.',
  'It lists what was changed and edited, what was added that was not in the team’s Word documents, the result of the reference check, and the points the team must verify before publication.',
  'Section 5 goes through the team’s own documents (the draft, the professor’s notes, the terminology chapter, the audiovisual translation notes, the Text Analysis Model and the requests made in the Teams chat): what was used, what was edited and what was not used.',
  'Points that must still be verified are printed in **red** in Section 7.',
  'Every point of every team document is listed in the separate Appendix: The Team’s Documents.',
  'The full detail of every correction is in the Correction Log; the full account of editorial decisions is in the Editorial Report.',
]],

['h1', '2. The handbook today'],
['ul', [
  'A guide for complete beginners in English–Arabic translation, written in English with examples in both languages.',
  '98 pages, B5 size, in two editions with identical content: the **Midnight** edition (dark cover) and the **Light** edition (pale cover), each as an editable Word file and a PDF.',
  '9 parts and 27 chapters, ordered from the basics to the most specialised topic (audiovisual translation).',
  'Back matter: abbreviations, further reading, a glossary of 113 terms, 39 references, and a page with the QR code of the team’s website.',
  'Every chapter follows the same guided pattern: **Where we are** → numbered **steps** (problem first, then solution) → **Try it** with answers → **Remember** and **Words to remember**.',
]],

['h1', '3. What was changed and edited'],
['h2', '3.1 Structure'],
['ul', [
  'The chapters follow the professor’s chapter list, ordered from easy to hard in 9 parts.',
  'Material that the draft repeated in several places was merged, so that each topic appears once.',
  'A new opening, **Start here**, explains to a complete beginner what a translator does, the four steps of every translation and the journey through the book.',
  'Every chapter was rewritten as a step-by-step guide. Each idea is explained with an example before its technical name is given.',
  'The key terms moved from the start to the end of each chapter (**Words to remember**).',
  'The abbreviations moved to the back of the book; the acknowledgements now close the preface.',
]],
['h2', '3.2 Content removed'],
['ul', [
  'The practice section (three levels of practice texts) and its answer key. Every chapter keeps its **Try it** exercise with answers.',
  'The four checklists at the end of the book, and the note on future editions.',
  'Scholars’ names in the running text. Each borrowed idea keeps its short citation in brackets, and all sources remain in the References.',
  'The italic descriptions under each part heading, and about a third of the running text (repetitions, filler and long explanations), to make the pages lighter.',
  'Specialist theory not needed by beginners (for example, the history of terminology and most audiovisual translation theories).',
  'All placeholders in square brackets, the empty checklist for Dr Abdullah’s framework, the names of reviewers who had not yet reviewed the book, and all mentions of the Guild Season.',
  'Draft examples that were wrong, unclear or not neutral (listed in the Editorial Report, Section 7).',
]],
['h2', '3.3 Corrections'],
['ul', [
  'Two full expert reviews in English and Arabic: **192 corrections** in the first review and **102** in the final review, after the guided rewrite.',
  'Main areas: definitions and concepts, Arabic grammar and terminology, examples that did not illustrate their point, consistency between chapters, cross-references, English, neutrality and citations.',
  'Examples of important corrections: commissioned vs self-initiated translators; the rule on Arabic word order; how to translate the verb _is_; the explanations of zakat and tayammum; the Arabic terms for lexical creation, form and modulation; the definition of a terminologist; the presentation of {{انتحاري}} and {{استشهادي}}; the definition of spotting in subtitling.',
  'After each review, every Arabic example and every citation was checked automatically: none were lost, every citation matches a reference, and every reference is cited.',
]],
['h2', '3.4 Design and layout'],
['ul', [
  'Two cover designs chosen by the team (Midnight and Light), with the club’s own logo taken from the logo file.',
  'The website QR code was rebuilt at high resolution with the club logo in the centre, printed on both back covers and on the last page inside the book. It was test-scanned on the final PDFs.',
  'Inside pages: generous spacing, roman page numbers for the front pages, a running head with the book title and the current part, and each chapter on a new page.',
]],

['h1', '4. What was added that was not in the team’s Word documents'],
['p', 'The team’s Word documents are the original draft (Draft_one), the professor’s notes (Latest updates and thoughts), the terminology chapter and the audiovisual translation notes. The items below were not in any of them.'],
['h2', '4.1 Added from Shaikha’s notes'],
['p', 'These additions come from Shaikha’s study notes. Where an idea comes from a published work, it is credited to that work in the text.'],
['ul', [
  '**Chapter 1:** the three kinds of translation (within one language, between languages, into another medium) (Jakobson, 1959); the translator as a reader before being a writer.',
  '**Chapter 3:** how to translate the English verbs _be_, _do_ and _have_; the Arabic dual; how to find the gender of _I_ and _you_ from clues in the text.',
  '**Chapter 5:** problems with single words: lexical gaps ({{ثكلى}}), false equivalents ({{الهنود الحمر}}) and rare words ({{شبر}}) (Baker, 2018).',
  '**Chapter 6:** the example {{خط}} for a word with several meanings.',
  '**Chapter 7:** one English verb with several Arabic equivalents (_deliver a letter, a speech, the news, a blow, a verdict_).',
  '**Chapter 8:** fixed expressions, how to spot an idiom, five ways to translate an idiom (Baker, 2018), and three more idioms (_bury the hatchet, in a nutshell, the long and the short of it_).',
  '**Chapter 13:** Arabic words borrowed into English (_algebra, algorithm, hijab_).',
  '**Chapter 16:** more examples of Arabicisation ({{استراتيجية}}, {{تكنولوجيا}}).',
  '**Chapter 18:** translating news headlines, the structure of news stories (the inverted pyramid, hard and soft news), and technical and literary texts.',
  '**Chapter 21:** medical examples of specialised terms (_allergic, allergen, contact eczema_).',
  '**Chapter 22:** translation memory, termbases and CAT tools, how machine translation has developed, and localisation.',
  '**Chapter 26:** the Arabic dubbing of _The Simpsons_ as an example of cultural adaptation.',
]],
['h2', '4.2 Written for the handbook'],
['p', 'These parts were written for the handbook, using the published sources in the References. Some cover topics that the professor’s notes asked for but that the Word documents did not contain.'],
['ul', [
  '**Front and back matter:** the copyright page, **Start here**, the further reading list, the glossary, the references and the website page.',
  '**In every chapter:** **Where we are**, the numbered steps, **Try it** with answers, **Remember** and **Words to remember**.',
  '**Chapter 1:** sight translation and localisation as types of translation.',
  '**Chapter 2:** the worked example of a first translation, step by step.',
  '**Chapter 3:** the gender and number of _you_, numbers from three to ten, linking words and Arabic punctuation.',
  '**Chapter 10:** communicative translation, the “middle way” between literal and free translation, with two examples of public notices (requested in the Teams chat, from the Principles of Translation notes, which were not received).',
  '**Chapter 12:** the seven translation procedures, with examples (requested in the notes; the draft had no content).',
  '**Chapter 13:** explicitation and implicitation, with three English–Arabic examples (requested in the Teams chat, from the Principles of Translation notes, which were not received).',
  '**Chapter 13:** further strategies (a more general word, a more neutral word, paraphrase, loan word with explanation, compensation, domestication and foreignisation) (requested in the notes).',
  '**Chapter 18:** eight genres, each with an example (requested in the notes).',
  '**Chapter 19:** words and points of view, with three practical questions (requested in the notes).',
  '**Chapter 20:** printed and digital dictionaries (requested in the notes).',
  '**Chapter 22:** a worked post-editing example and advice on using AI tools well.',
  '**Chapter 23:** the lists of common mistakes in both directions (requested in the notes).',
  '**Chapter 24:** the interlingual risk matrix (requested in the notes).',
  '**Chapter 26:** first steps for beginners in audiovisual translation.',
  '**Chapter 27:** a step-by-step subtitling method, a worked example of condensing a line, rules for Arabic subtitles, and subtitle timing.',
]],

['h1', '5. The team’s documents: what was used, edited and not used'],
['p', 'Each document was compared point by point with the finished handbook. The full list, with the reason for every decision, is in the Appendix: The Team’s Documents.'],
['table', ['Document', 'Points traced', 'Used as written', 'Used and edited', 'Not used'], [
  ['Original draft (Draft_one)', '175', '8', '148', '19'],
  ['Terminology chapter', '43', '1', '24', '18'],
  ['Intro to AVT notes', '16', '0', '8', '8'],
  ['AVT 2 notes', '46', '4', '31', '11'],
], [40, 15, 15, 15, 15]],
['p', '“Used and edited” is the largest group because almost every point was rewritten in plain English for beginners, and many were also corrected, shortened or merged.'],

['h2', '5.1 The original draft (Draft_one)'],
['p', '**Used** (rewritten for beginners, and placed in the chapter with the same topic):'],
['ul', [
  'Definitions and abbreviations (now in the key terms of each chapter and in the Abbreviations).',
  'The differences between Arabic and English (Chapter 3).',
  'The objectives of the book (Preface).',
  'Translation and the translator, the translator’s qualities, commissioned and self-initiated translators, and the tips on how to translate (Chapters 1 and 2).',
  'Equivalence (Chapter 9); form and meaning (Chapter 4); types of meaning (Chapter 5); context, homonymy and polysemy (Chapter 6).',
  'Collocation (Chapter 7); idioms and proverbs (Chapter 8); literal and free translation (Chapter 10); metaphoric translation (Chapter 11).',
  'Translation strategies (Chapter 13); cultural approximation (Chapter 14); descriptive translation (Chapter 15); lexical creation (Chapter 16).',
  'Text analysis, including the KUNA example (Chapter 17); commentary on translation (Chapter 25); post-editing and the rules for titles (Chapters 2 and 22).',
  'Many items from the draft’s exercises 16 and 24–29 (Chapters 7, 8 and 14).',
]],
['p', '**Edited:**'],
['ul', [
  'Every section was rewritten as guided steps, and topics repeated in several places were merged so that each appears once.',
  'Errors were corrected, for example: “died” given with the Arabic for “killed”; “kick the bucket” given with an insulting Arabic phrase; a line saying form is more important than meaning; idiom examples that were really collocations; “Bush’s puppy” (the press said “poodle”); “mark my words” translated as a promise; the rule that Arabic always starts with the verb; the Arabic equivalent of “is”.',
  'Two draft examples were also corrected without being recorded before: _Sam ate the cake_ had been translated with “the apple” ({{التفاحة}}), and _the Home Office_ had been translated as a minister ({{وزير}}) instead of a ministry ({{وزارة}}).',
  'Colloquial Egyptian expressions were replaced with formal ones, and examples that took a political or religious position were rewritten to stay neutral.',
  'The empty headings in the draft (terminology, AI and machine translation, glossary, references) were written in full as Chapters 21 and 22, the Glossary and the References.',
]],
['p', '**Not used** (51 items; each is listed with its reason in the Appendix), for example:'],
['ul', [
  'Statements that were wrong or unclear: “Principles = Foundations”, “Arabic is compositional, English is compounding”, “translation also means to politicize”, “mule” as a synonym of “horse”, “kick the chair” as an English idiom.',
  'A figure that could not be verified: the number of fields attributed to the Jordanian academy.',
  'Examples that were not neutral or not suitable: the remark that a named news agency is biased, the Clinton impeachment example, and a Qur’anic verse used as an equivalent of an English proverb.',
  'Invented words (tribocracy, puppycracy, patriocracy) and some examples left out for space.',
  'Some exercise items (for example _a readable book_, _addled egg_, _Every Jack has his Jill_), which could form an extra exercise set later.',
]],

['h2', '5.2 The professor’s notes'],
['ul', [
  '**38 requests** once repeated requests are merged: 21 done, 7 partly done, 4 done and then removed at the team’s request, and 6 not done.',
  '**Done**, for example: the chapter order from easy to hard; missing strategies and types of translation; the seven procedures; tips and preparation at the beginning; the three questions (client, purpose, audience); chapters on text analysis, commentary, dictionaries, terminology, and machine translation and AI; the risk matrix; the main genres with examples; poetry examples; common mistakes; answers with explanations.',
  '**Done, then removed at the team’s request**: the practice section at three levels, the checklists, the note on future editions (with the planned Arabic version).',
  '**Partly done**: the glossary contains the terms of every “Words to remember” box, but some terms explained only in the text (for example sight translation, spotting, SDH, the inverted pyramid) are not in it; news is taught through examples and headlines, but no authentic article is used; Fairclough’s model is given as three practical questions; the Dr Abdullah checklist was not written; references for the 180, 182 and 386 materials could not be added.',
  '**Not done**, because the material was not received: examples from “the book”; sentences from the Analysis, 180 and 386 texts; the text {{الترجمة: ماهيتها}} and its author; practice texts from Masooma; dictionary examples from Loulwah. Feedback from the supervisor and Dr Amin is still to come.',
]],

['h2', '5.3 The terminology chapter'],
['ul', [
  '**Used and edited** as Chapter 21: the definition of terminology; the translator and the terminologist; why terms must be managed; short forms; what makes a good term; the Arabic language academies; how to translate a term; term lists; termbases; one term for one idea. Everything was rewritten in plain English and reduced to what a beginner needs.',
  '**Corrected**: the definition of a terminologist (who collects and records terms, often in several languages, rather than creating terms in one language); the history of the field (Wüster’s 1931 thesis); the roles of ISO, IEC and ITU; a few smaller points.',
  '**Not used** (removed in the beginner revision): the history of terminology and its schools, the categories of terms by meaning and origin, the detailed methods of the academies, most of the nine rules for naming terms, and all the standardisation bodies.',
  '**Added** to Chapter 21 that was not in the chapter: the tools (UNTERM, Arabterm and termbases), a sample term list, the medical examples, and the Damascus academy and the Coordination Bureau of Arabization in Rabat.',
  'The terminology chapter cites no sources. All sources now used in Chapter 21 were added during editing.',
]],

['h2', '5.4 The audiovisual translation notes'],
['ul', [
  '**Used and edited** as Chapters 26 and 27: why audiovisual translation matters and what makes it different; the main types; dubbing; the idea that purpose comes first (Skopos theory); the challenges; subtitles and their kinds; the relation between words, images and sound; language variety; cultural references; subtitling strategies; taboo language and censorship.',
  '**Edited**: the two overlapping lists of subtitling strategies were merged into one list of eight; the names Vermeer, Díaz Cintas and Remael were corrected; “32 to 41 characters per line” was corrected to about 37 to 39, and up to 42 on streaming platforms; dubbing in the Arab world was described correctly; “relies 100% on technology” became “depends heavily on technology”.',
  '**Not used**: the history of the field; three of the four theories (descriptive translation studies, polysystem theory and reception studies); the summary box on audiovisual translation in the Arab world; the YouTube links; the quotation on “screen translation”; and several minor types of audiovisual translation (for example free commentary, in-vision signing, fansubs and surtitles), removed in the last revision to keep the list short.',
  '**Added** to Part 9 that was not in the notes: subtitle display times and spotting, subtitles for the deaf and hard of hearing (SDH), a five-step subtitling method, a worked example of condensing a line, rules for Arabic subtitles, and first steps for beginners. The Arabic dubbing of _The Simpsons_ comes from Shaikha’s notes.',
]],

['h2', '5.5 The Text Analysis Model (V2-2)'],
['p', 'All four pages were seen in screenshots. The model was shared in the Teams chat with notes from the Text Analysis and Translation course and three sample analyses.'],
['ul', [
  '**Used as written**: the three-step process (analysis, translation, post-translation activity), which matches the three phases already in Chapters 17 and 25.',
  '**Used and edited** in Chapter 17, Step 3 (“look at two levels”), in plain English: the **linguistic level**, with its **micro level** (lexical, syntactic, semantic, morphological and phonological aspects, given as words, grammar, meaning, word forms and sound) and its **macro level** (textual, intertextual, and political or ideological aspects, given as the text, other texts, and point of view, linked to Chapters 18 and 19); and the **external level** (the background event, the author, and the effect of the target culture and audience), given as three questions.',
  '**Used and edited** in Chapter 25: the post-translation commentary should consult the analysis and explain how the problems were solved. One sentence added to Step 2.',
  '**Used and edited** in Chapter 17, Step 5: the model can also be used to assess the quality of a translation (which elements were transferred and which were omitted). One sentence added, linked to Chapter 23.',
  '**Added to the References**: Fairclough (2003), _Analysing discourse: Textual analysis for social research_ (Routledge), which the model names as its basis.',
  '**Not used**, as too advanced for beginners: blending, clippings and infixation; frame-modification, re-modelling and Al-ta’reed; politicization and ideologization as named terms; monitoring, intrinsic managing and extrinsic managing in the commentary.',
  '**Not received**: the course notes and the three sample analyses (the News text, the Speech text and the Climate change text). They could give Chapters 17 and 25 authentic worked examples.',
]],

['h2', '5.6 Requests in the Teams chat'],
['p', 'The messages in the team’s Teams chat were compared with the handbook.'],
['ul', [
  '**Terminology chapter**: the chat says that the material was selected from the terminology part by Samiuallah and Masooma. The handbook does not name individual contributors; the acknowledgement thanks every team member (see Section 7).',
  '**Audiovisual translation notes** (AVT 2 and Intro to AVT): the chat asks Loulwah to prepare the audiovisual chapter “from her notes specifically”, which suggests these are Loulwah’s notes. They were used for Chapters 26 and 27 (Section 5.4). The chat also asks for a background and an introduction to audiovisual translation, suitable for beginners: **done** (Chapter 26, Steps 1 and 2).',
  '**Principles of Translation notes** (a PDF of 59.5 MB): **not received**. The chat asks for four sections from it:',
]],
['table', ['Requested in the chat', 'In the handbook', 'Status'], [
  ['Machine translation', 'Chapter 22', 'Done, from the draft and the published sources; the notes themselves were not received'],
  ['English–Arabic communicative translation strategy', 'Chapter 10, Step 4', 'Added now, from Newmark (1988); to be compared with the notes'],
  ['Explicitation and implicitation', 'Chapter 13, Step 3', 'Added now, from Vinay & Darbelnet (1958/1995); to be compared with the notes'],
  ['The margin notes', 'Not in the handbook', 'Not done: the notes were not received'],
  ['Examples for practice', 'Removed', 'Done, then removed at the team’s request (practice section); the “Try it” questions remain'],
], [34, 22, 44]],

['h2', '5.7 Sources named in the team’s documents'],
['table', ['Source named in the documents', 'In the References?', 'Status'], [
  ['The 180 textbook, the 182 course book, the 386 texts and the Analysis texts', 'No', 'Not received: to be supplied and cited'],
  ['“The book” with useful examples', 'No', 'Not identified'],
  ['{{الترجمة: ماهيتها}} (attributed to Dr Yusuf)', 'No', 'Not received: text and author to be confirmed'],
  ['Dr Abdullah’s PhD research or framework', 'No', 'Not received'],
  ['Loulwah’s notes on machine translation and dictionaries', 'No', 'Not received; her audiovisual notes appear to be the AVT notes used in Chapters 26 and 27 (to be confirmed)'],
  ['The Principles of Translation notes, with the margin notes', 'No', 'Not received: to be supplied and compared with Chapters 10, 13 and 22'],
  ['Text Analysis Model V2-2: Fairclough (2003)', 'Yes (added)', 'Checked twice (confirmed): author, year, title and publisher match the model’s footnote'],
  ['Text Analysis Model V2-2 itself', 'Yes, as Translation Team (n.d.)', 'Checked: all four pages seen; the author is to be confirmed'],
  ['Sample analyses (News, Speech and Climate change texts) and the Text Analysis and Translation course notes', 'No', 'Not received'],
  ['The book behind the draft’s numbered exercises (16, 24–29)', 'No', 'To be verified: credited to the course materials until the source is known'],
  ['The team’s course materials (the draft and notes)', 'Yes, as Translation Team (n.d.)', 'Checked: the wording of quoted definitions to be confirmed'],
  ['Jordanian academy (“74 fields”)', 'No', 'Checked: could not be verified; removed'],
  ['Wüster; ISO, IEC and ITU (terminology chapter)', 'No', 'Checked and corrected; then removed in the beginner revision'],
  ['Methods of the Arabic academies (terminology chapter)', 'No', 'Not verified (no source found); removed'],
  ['UNTERM, Arabterm, Cabré (1999) (added to Chapter 21)', 'Yes', 'Checked twice; the co-publisher of Arabterm (GIZ or BMZ) to be confirmed'],
  ['Pérez-González (2014) (AVT notes)', 'Yes', 'Checked twice (confirmed)'],
  ['Reiss & Vermeer (1984) (AVT notes)', 'Yes', 'Checked twice (confirmed); spelling of Vermeer corrected'],
  ['Díaz Cintas & Remael (AVT notes)', 'Yes (2007 and 2021)', 'Checked; line length corrected; which edition each point should cite to be confirmed'],
  ['Pedersen (2011) (AVT notes)', 'Yes', 'Checked twice (confirmed)'],
  ['Gambier (2003) (AVT notes)', 'Yes', 'Checked twice (confirmed); page number not checked'],
  ['O’Hagan (2007); Even-Zohar; descriptive translation studies (AVT notes)', 'No', 'Not used'],
  ['YouTube links (AVT notes)', 'No', 'Not used: links can stop working in a printed book'],
], [44, 20, 36]],

['h1', '6. References: what was checked'],
['p', 'All 39 references and every direct quotation were checked twice against published information found online: once in the first review and again in the final review. The printed books themselves could not be consulted, so some points still need the books.'],
['table', ['Reference', 'First check', 'Double check', 'Result'], [
  ['Baker (2018); Baker & Hanna (2009)', 'Checked', 'Checked', 'Confirmed; page range of Baker & Hanna added'],
  ['Cabré (1999)', 'Checked', 'Checked', 'Confirmed'],
  ['Dickins et al. (2016)', 'Checked', 'Checked', 'Confirmed'],
  ['Eco (2003)', 'Checked', 'Checked', 'Confirmed; the quoted phrase is the book’s title'],
  ['Fairclough (1992)', 'Checked', 'Checked', 'Confirmed; quotation changed to a paraphrase'],
  ['Fairclough (2003) (new)', 'Checked', 'Checked', 'Confirmed; added from the team’s Text Analysis Model'],
  ['Farghal & Shunnaq (1999)', 'Checked', 'Checked', 'Confirmed; publisher corrected'],
  ['Firth (1957, p. 11)', 'Checked', 'Checked', 'Confirmed'],
  ['Ghazala (2008)', 'Checked', 'Checked', 'Confirmed'],
  ['Jakobson (1959, p. 236)', 'Checked', 'Checked', 'Confirmed'],
  ['Mossop (2014); Nord (1997); Nord (2005)', 'Checked', 'Checked', 'Confirmed; the Nord (2005) citation moved to the idea it supports'],
  ['Newmark (1988)', 'Checked', 'Checked', 'Confirmed; one quotation cited with its page (p. 11). New quotation on communicative translation (p. 47): needs more work, confirm the page in the book'],
  ['Nida & Taber (1969, p. 12)', 'Checked', 'Checked', 'Confirmed; one paraphrase has no page'],
  ['Pym (2015); Venuti (1995); Wehr (1994)', 'Checked', 'Checked', 'Confirmed'],
  ['Reiss (1971/2000)', 'Checked', 'Checked', 'Confirmed; original date added'],
  ['Reiss & Vermeer (1984)', 'Checked', 'Checked', 'Confirmed'],
  ['Díaz Cintas & Remael (2007, 2021); Pedersen (2011); Pérez-González (2014)', 'Checked', 'Checked', 'Confirmed; both editions of Díaz Cintas & Remael are cited'],
  ['Gambier (2003)', 'Checked', 'Checked', 'Confirmed; DOI added; no page number'],
  ['Kenny (2022)', 'Checked', 'Checked', 'Confirmed; DOI added'],
  ['Vinay & Darbelnet (1958/1995)', 'Checked', 'Checked', 'Corrected: “Eds. & Trans.” New definition of explicitation (p. 342, the book’s glossary): needs more work, confirm the page in the book'],
  ['Shakespeare (1609)', 'Checked', 'Checked', 'Corrected: original title of the 1609 edition'],
  ['Jerome (395/2012)', 'Checked', 'Checked', 'Corrected: page range of the chapter added; the page of the quotation is still needed'],
  ['Johnson (1784/1897, p. 309)', 'Corrected', 'Checked', 'Needs more work: confirm the page and the section of the book'],
  ['al-Jāḥiẓ (1965)', 'Checked', 'Checked', 'Needs more work: page number of the quotation'],
  ['al-Mutanabbi (n.d.)', 'Checked', 'Checked', 'Needs more work: edition, editor, publisher and year'],
  ['Academy of the Arabic Language in Cairo (n.d.)', 'Checked', 'Corrected', 'Needs more work: edition and year of al-Muʿjam al-Wasīṭ'],
  ['Baalbaki (n.d.)', 'Checked', 'Checked', 'Needs more work: edition and year of Al-Mawrid'],
  ['Oxford collocations dictionary (2009)', 'Checked', 'Checked', 'Needs more work: the editor could be named first'],
  ['ALECSO & GIZ (n.d.)', 'Corrected', 'Checked', 'Needs more work: confirm GIZ or BMZ as co-publisher'],
  ['United Nations (n.d.), UNTERM', 'Checked', 'Checked', 'Confirmed'],
  ['Translation Team (n.d.)', 'Checked', 'Corrected', 'Needs more work: unpublished course materials; confirm the wording of quoted definitions'],
], [34, 13, 14, 39]],

['h1', '7. To verify before publication'],
['p', 'The team should check the following points before the handbook is published.'],
['h2', '7.1 Language'],
['redul', [
  'A native Arabic-speaking specialist must read the final PDF from beginning to end, with special attention to Chapters 3, 5, 18, 22 and 27, where new material was added.',
  'Confirm the preferred Arabic forms: “governing law” ({{القانون الواجب التطبيق}} or {{القانون المطبَّق}}) and “jet lag”.',
  'Confirm the Arabic terms chosen for **explicitation** ({{التصريح}}) and **implicitation** ({{الإضمار}}) in Chapter 13, and the examples in Chapters 10 and 13 ({{ممنوع التدخين}}, {{انتبه، الطلاء لم يجفّ}}, {{ركب قطار الأنفاق في لندن}}, {{مجلس الأمة}}).',
  'Decide whether to keep the few colloquial expressions, which are labelled as colloquial, or use only formal Arabic.',
]],
['h2', '7.2 Sources'],
['redul', [
  'Check the 30 points in Section 5 of the Correction Log against the printed books.',
  'Add the page numbers of the al-Jāḥiẓ and Jerome quotations, and of the Nida & Taber paraphrase (usually p. 4).',
  'Confirm the page and section of the Johnson letter in _Johnsonian miscellanies_ (vol. 2).',
  'Give the edition and year of al-Muʿjam al-Wasīṭ, Al-Mawrid and the Dīwān of al-Mutanabbi used by the team.',
  'Confirm whether the chapters citing Díaz Cintas & Remael (2007) should cite the 2021 edition instead.',
  'Confirm the wording of the definitions quoted from the team’s course materials (Translation Team, n.d.).',
  'Confirm the original sources of the draft’s own examples and of its numbered exercises (16, 24–29). If any come from a published book (for example the 180 or 182 textbooks), that book must be credited.',
  'Add a source for the Damascus academy and the Coordination Bureau of Arabization in Rabat (Chapter 21), which are not in the terminology chapter.',
  'Confirm the page of the Newmark quotation on communicative translation (1988, p. 47) and of the Vinay & Darbelnet definition of explicitation (1958/1995, p. 342).',
  'Name the author of the Text Analysis Model V2-2, so that it can be credited correctly (it is now cited as the team’s course materials, with Fairclough, 2003).',
  'Send the three sample analyses (News, Speech and Climate change texts) if they should be used as worked examples in Chapters 17 and 25.',
  'Send the Principles of Translation notes (with the margin notes), so that Chapters 10, 13 and 22 can be compared with them.',
  'Confirm the source of the Arabic dubbing of _The Simpsons_ (Chapter 26), which comes from Shaikha’s notes and is credited to the course materials.',
]],
['h2', '7.3 Decisions and details'],
['redul', [
  'Credit the team members’ contributions: the Teams chat shows that Samiuallah and Masooma selected the terminology material, and that the audiovisual notes appear to be Loulwah’s. The handbook currently thanks all team members without names.',
  'Decide whether to add to the glossary the terms explained only in the text (for example sight translation, spotting, SDH and the inverted pyramid).',
  'Confirm the club’s official name: it appears in three slightly different forms (title page, copyright line and reference entry).',
  'Confirm the copyright line and that the statement on AI assistance meets the university’s and the publisher’s rules.',
  'Decide the final English title (“Translation Handbook” or “Translator’s Equipment”) and whether to publish one edition or both.',
  'Decide whether the three practical questions in Chapter 19 are enough for the professor’s “relational model”.',
  'Materials not received: Dr Abdullah’s framework, the text {{الترجمة: ماهيتها}} and its author, the 180, 182, 386 and Analysis texts, Loulwah’s notes on machine translation and dictionaries, and the Principles of Translation notes. Decide whether they belong in this edition or a later one.',
  'Before printing: open the Word file in Microsoft Word and update the contents page; then print a test copy and scan the QR code with several phones, including the light-on-dark code on the Midnight edition.',
]],
];
