// Editorial report on the Translation Handbook, for the supervisor. Plain content; report.js lays it out.
module.exports = [

['h1', '1. Purpose of this report'],
['p', 'This report describes how the first edition of the Translation Handbook ({{دليل الترجمة}}) was prepared from the Translation Team’s materials. It records what was taken from each source, what was changed, what was added, what was removed, and the reason for each decision. It also lists the work that remains before the handbook can be published.'],
['p', 'The editor was given full authority to organise, revise, rewrite, add, explain and remove material. Because of this, every significant editorial decision is recorded here so that the supervisor can review it before publication.'],
['p', 'The report does not reproduce the handbook’s examples. It identifies them by name or by chapter so that each decision can be checked against the handbook.'],

['h1', '2. Summary'],
['h2', '2.1 The finished handbook'],
['ul', [
  'A handbook for complete beginners on translating between English and Arabic. The text is in English and every example is given in both languages.',
  '92 pages, B5 page size (176 × 250 mm), with 9 parts and 27 chapters, followed by practice texts at three levels with an answer key, four checklists, a note on future editions, a glossary of 102 terms and a list of 39 references.',
  'Two editions, which are identical inside and differ only in the cover design: the Midnight edition (dark indigo cover) and the Light edition (pale lavender cover). Each edition is available as an editable Word file and as a PDF.',
]],
['h2', '2.2 The main editorial decisions'],
['ol', [
  'The structure follows the professor’s notes: every chapter requested in the notes is included, and the chapters are ordered from the simplest topics to the most demanding.',
  'The level is kept at beginner level throughout. Theory intended for specialists was removed, and each idea is explained in short, plain sentences.',
  'Every chapter follows the same pattern, so that a reader always knows what to expect.',
  'Material that the draft repeated in several places was merged, so that each topic appears once.',
  'Errors in the draft and in the course notes were corrected, and examples that were inaccurate, unclear or not neutral were replaced or removed.',
  'Every idea taken from a published work is cited in the text and listed in the references in APA style. Quotations and references were checked against published information.',
  'Nothing was invented. Where material was missing, the gap is recorded in this report rather than filled with unsupported content.',
]],
['h2', '2.3 What is still needed'],
['p', 'The handbook is complete in structure and content. Before publication, the Arabic must be proofread by a qualified translator, and several items that depend on materials not yet received must be decided. These are listed in Section 12.'],

['h1', '3. Source materials'],
['h2', '3.1 Materials received'],
['table', ['Material', 'Content', 'How it was used'],
 [['Draft_one.docx (the original draft)', 'About 730 lines of notes: definitions and abbreviations, differences between Arabic and English, equivalence, form and meaning, types of meaning, collocation, context, idioms, literal, metaphoric and free translation, strategies, cultural approximation, descriptive translation, lexical creation, text analysis, commentary, and exercises 16 and 24–29. The headings for terminology, machine translation and AI, the glossary and the references had no content.', 'The main source of the handbook’s ideas and examples. Every chapter that the draft covers is built on it.'],
  ['Latest_upades_and_thoughts.docx (the professor’s notes), received twice', '64 paragraphs of instructions on structure, new chapters, checklists, exercises, references and the team’s tasks. Several instructions appear two or three times. The second copy differs from the first only in two typing corrections.', 'Used as the list of requirements. Each request is checked in Section 5.'],
  ['Terminology_chapter.docx (Masooma’s chapter)', 'Definition and history of terminology, the translator and the terminologist, functions of terminology, types of terms, rules for forming terms, the Arabic language academies, how to translate a term, technical dictionaries, termbases and standardisation bodies.', 'The basis of Chapter 21. Rewritten in plain English and reduced to what a beginner needs (see Section 8).'],
  ['Intro_to_AVT.pdf and AVT_2.pdf (course notes on audiovisual translation; the second is a 12-page scan)', 'Growth of audiovisual translation, its types, four theories, its challenges, audiovisual translation in the Arab world, dubbing, and subtitling: classifications, the relation between words, image and sound, language variation, strategies, taboo language and censorship.', 'The basis of Part 9 (Chapters 26 and 27), placed at the end of the book as the most advanced topic.'],
  ['The Guild Translation Team logo', 'The club’s logo on a purple background.', 'The wordmark was cut from this file and used on the title page and both covers (see Section 10).'],
  ['Four screenshots of Guild posts', 'The club’s published visual style.', 'Used as a reference for colours and for the clear, simple presentation of text.']],
 [28, 40, 32]],
['h2', '3.2 Materials mentioned in the notes but not received'],
['ul', [
  'The 180 textbook and the 182 course book (notes, paragraphs 26 and 64).',
  'The 386 texts and the Analysis texts, from which example sentences were to be taken (paragraph 26).',
  'The text {{الترجمة: ماهيتها}} (paragraph 39).',
  'Loulwah’s notes on machine translation and on dictionaries (paragraphs 6, 13 and 56).',
  'Dr Abdullah’s PhD research or framework, on which one checklist was to be based (paragraph 47).',
  '“The book” with useful examples (paragraph 24). Its title is not given in the notes.',
  'Practice texts from Masooma and examples from Shaikha (paragraphs 51, 52 and 55).',
]],
['p', 'Work that depended on these materials could not be completed. Section 5 shows which requests are affected, and Section 12 lists what the team needs to supply or decide.'],
['h2', '3.3 Published sources'],
['p', 'Published works on translation, linguistics and terminology were used to provide definitions, to support the draft’s ideas with recognised sources, and to check facts. All 39 works are cited in the text and listed in the references. No text from websites was copied into the handbook. Two online terminology databases (UNTERM and Arabterm) are recommended to readers as tools and are cited as such.'],

['h1', '4. Editorial principles'],
['ol', [
  '**Follow the professor’s instructions.** The chapter list, the checklists, the practice section and the glossary all come from the notes.',
  '**Order from easy to hard.** The book starts with what translation is and how to prepare, moves through meaning, words and methods, then to whole texts, tools and checking, and ends with audiovisual translation.',
  '**Write for beginners.** Sentences are short. Each technical term is defined when it first appears. Theory is included only when a beginner can use it directly.',
  '**Keep the structure simple.** Every chapter has the same five elements, and the layout inside the book uses one heading style, one box style and one list style.',
  '**Keep what is correct in the draft.** Draft material was rewritten for clarity but kept wherever it was accurate and useful.',
  '**Correct what is wrong.** Errors of fact, language or logic were corrected, and each correction is recorded in Section 7.',
  '**Stay neutral.** The handbook does not take political or religious positions and does not describe named organisations negatively.',
  '**Cite everything.** Every quotation and every idea taken from a published work is credited. Examples from the team’s materials are credited to the Translation Team’s course materials.',
  '**Do not invent.** No sources, figures, names or quotations were created. Where information was missing, it was left out and recorded here.',
]],

['h1', '5. The professor’s notes: request by request'],
['p', 'Status: Done, Partly done or Not done. Requests that appear more than once in the notes are listed once, with all their paragraph numbers.'],
['table', ['Request (paragraphs)', 'Status', 'Where', 'Comment'],
 [['Organise the material, make it consistent and remove repetition (1, 8, 17)', 'Done', 'Whole book', 'Topics that the draft repeated in two or three places (equivalence, denotation and connotation, collocation, idioms, descriptive translation) now appear once, each in its own chapter.'],
  ['Add missing translation strategies (2, 9, 18)', 'Done', 'Chapter 13', 'The draft’s strategies are kept. Added: more general word, more neutral word, paraphrase, loan word with explanation (Baker, 2018), compensation (Dickins et al., 2016), and domestication and foreignisation (Venuti, 1995).'],
  ['Add missing types of translation (2, 9, 18)', 'Done', 'Chapter 1; Chapter 26', 'Written translation, interpreting, sight translation, audiovisual translation and localisation. Chapter 26 describes the types of audiovisual translation.'],
  ['New chapter on the seven translation procedures (3, 10, 19, 44)', 'Done', 'Chapter 12', 'Vinay and Darbelnet’s direct and oblique procedures, each with an example, and one sentence that shows several procedures at work.'],
  ['Add material to the cultural approximation chapter (4, 11, 20)', 'Done', 'Chapter 14', 'Added sections on climate and meaning, titles and institutions, culture in the media and business, and social expressions.'],
  ['Definitions of key concepts in every chapter, and all terms in the glossary (5, 12, 21, 53)', 'Done', 'Every chapter; Glossary', 'Every chapter opens with a list of key terms, each with its Arabic equivalent and a short definition. The glossary is compiled from these lists and has 102 terms, each with the chapter where it is explained.'],
  ['Chapter on machine translation and AI (6, 13, 22)', 'Done', 'Chapter 22', 'Uses the draft’s point that post-editing is the new direction of the profession. Loulwah’s notes were not received.'],
  ['Final exercises at three levels of length, applying the theories, the genres and the checklists (16)', 'Done', 'Practice', 'Level 1: sentences in both directions and error correction. Level 2: a legal and human-rights text, classical Arabic poetry and English poetry. Level 3: two news texts, with instructions to use the checklists and the risk matrix.'],
  ['Use examples from “the book” (24)', 'Not done', '–', 'The book was not identified or supplied.'],
  ['Add news texts as authentic material (25, 59)', 'Not done', 'Practice, Level 3', 'The two news texts were written for the handbook and are labelled as such. Authentic texts need permission from their publishers.'],
  ['Extract sentences from the Analysis, 180 and 386 texts (26)', 'Not done', '–', 'These texts were not supplied.'],
  ['Include examples from poetry (27)', 'Done', 'Chapters 11 and 18; Practice', 'Examples from al-Mutanabbi and Shakespeare’s Sonnet 18, and poetic metaphors.'],
  ['Include the main genres, with at least one example of each (28, 29)', 'Done', 'Chapter 18', 'Eight genres, each with an English and Arabic example, grouped under Reiss’s three text functions.'],
  ['A section on tips, techniques and preparation at the beginning (30)', 'Done', 'Chapter 2', 'Placed second, directly after the basic definitions. Includes the draft’s tips and a worked first translation.'],
  ['Practical checklists (31)', 'Done', 'Checklists', 'The translation process, an analysis worksheet, words and points of view, and the commentary.'],
  ['Who is the client? What is the purpose? Who is the audience? (32–35)', 'Done', 'Chapter 2', 'The three questions form the translation brief and are used again in the practice section.'],
  ['Chapter on terminology management and terminology guides (36, 62)', 'Done', 'Chapter 21', 'Based on Masooma’s chapter.'],
  ['Interlingual risk assessment matrix (37)', 'Done', 'Chapter 24', 'A matrix of ten risk areas, each with an example, a risk level and the action to take.'],
  ['Audiences and materials for future editions (38)', 'Partly done', 'Future editions', 'Lists the planned Arabic version, more authentic news texts, subtitling exercises with film clips, and chapters on interpreting and on legal and medical translation. The notes do not specify the audiences, so none are named.'],
  ['Cite anything taken from {{الترجمة ماهيتها}} and attribute it to Dr Yusuf (39)', 'Not done', '–', 'The text was not supplied, so nothing is taken from it and it is not in the references. The author’s name also needs to be confirmed (Section 12).'],
  ['Chapter on text analysis (40)', 'Done', 'Chapter 17', 'Presented as the first of three phases: analysis, translation and commentary.'],
  ['Chapter on translation commentary, including how to analyse a translation (41)', 'Done', 'Chapter 25', 'Two parts, five steps for each problem, rules for writing, and an example.'],
  ['Chapter on printed and digital dictionaries (42)', 'Done', 'Chapter 20', 'Types of dictionary, a three-step method for checking a meaning, printed and digital dictionaries compared, and a list of recommended dictionaries.'],
  ['Fairclough’s relational model (45)', 'Done, at beginner level', 'Chapter 19; Checklist 3', 'Presented as three practical questions based on Fairclough (1992). The theory itself is not explained, in line with the instruction to keep the book at beginner level.'],
  ['Three checklists based on Dr Abdullah’s framework and on Fairclough’s model (46–48)', 'Partly done', 'Checklist 3', 'The Fairclough checklist is included. The checklist based on Dr Abdullah’s framework is not included because the framework was not received.'],
  ['Collect examples from books, poetry, proverbs, idioms and text types, with sources (52)', 'Partly done', 'Chapters 8, 11, 14 and 18', 'Examples were added and cited. The original sources of the draft’s own examples are not known (Section 12).'],
  ['Discuss common grammatical and stylistic mistakes: in each chapter or in a separate section (60)', 'Done', 'Chapter 23', 'Placed in one section inside the revision chapter, with separate lists for each direction, so that readers can find them in one place.'],
  ['Answer key with explanations (61)', 'Done', 'Answer key; every chapter', 'Every “Try it” exercise and every practice item has an answer with a short explanation. Level 3 has guidance instead of a single model answer.'],
  ['Table of contents and final structure (58)', 'Done', 'Contents', 'Nine parts and 27 chapters, with the placement of the tips, the practice section and the glossary decided as described in Section 6.'],
  ['References for the 180 book, the 182 course book and all other sources (64)', 'Partly done', 'References', 'All published sources are listed. The 180, 182 and 386 materials were not received and are not listed. The course materials are credited as the Translation Team’s course materials.'],
  ['Keep the Arabic version for future use (50)', 'Done', 'Future editions', 'The planned Arabic version is listed.']],
 [30, 12, 16, 42]],

['h1', '6. Structure of the handbook'],
['h2', '6.1 Order of the book'],
['table', ['Section', 'Content', 'Reason for its place'],
 [['Front matter', 'Title page, copyright page, contents, preface, acknowledgements, how to use this handbook, abbreviations.', 'Standard order for an academic book. Front pages are numbered i, ii, iii.'],
  ['Part 1: Getting started (Chapters 1–3)', 'What translation is and what a translator needs; tips and preparation; the main differences between English and Arabic.', 'The notes ask for tips at the beginning. A reader needs these basics before anything else.'],
  ['Part 2: Understanding meaning (Chapters 4–6)', 'Form and meaning; types of meaning; context.', 'Meaning is the basis of every later chapter.'],
  ['Part 3: Words that go together (Chapters 7–8)', 'Collocation; idioms, proverbs and fixed expressions.', 'Moves from single words to fixed groups of words.'],
  ['Part 4: Methods and techniques (Chapters 9–13)', 'Equivalence; literal and free translation; metaphor; the seven procedures; strategies.', 'The main methods, once the reader understands meaning and word groups.'],
  ['Part 5: Culture and new words (Chapters 14–16)', 'Cultural approximation; descriptive translation; lexical creation.', 'Applies the methods to items that have no direct equivalent.'],
  ['Part 6: Working with whole texts (Chapters 17–19)', 'Text analysis; text types and genres; words and points of view.', 'Moves from words and sentences to complete texts.'],
  ['Part 7: Tools and resources (Chapters 20–22)', 'Dictionaries; terminology; machine translation and AI.', 'Tools are more useful once the reader can judge a translation.'],
  ['Part 8: Checking and explaining (Chapters 23–25)', 'Revision and common mistakes; risk assessment; commentary.', 'The last stage of every translation.'],
  ['Part 9: Audiovisual translation (Chapters 26–27)', 'Introduction to audiovisual translation; subtitling.', 'The most specialised topic, so it comes last.'],
  ['Back matter', 'Practice (three levels and answer key), four checklists, future editions, glossary, references.', 'Exercises and reference material that draw on the whole book.']],
 [26, 42, 32]],
['p', 'Main text pages are numbered from 1, starting at Part 1. Each page carries a running head with the title of the book and the current part.'],
['h2', '6.2 The pattern of every chapter'],
['ol', [
  '**Introduction:** what the chapter is about and how it follows from the previous one.',
  '**Key terms:** each term with its Arabic equivalent and a one-line definition.',
  '**Explanation and examples:** short sections, with examples in both languages.',
  '**Try it:** two or three questions, with answers straight after.',
  '**Remember:** the main points of the chapter in a short list.',
]],

['h1', '7. Corrections'],
['h2', '7.1 Corrections to the draft'],
['table', ['Item in the draft', 'Problem', 'Action'],
 [['The denotative meaning of “died” given with the Arabic verb for “killed”', 'Wrong meaning.', 'Corrected to the Arabic verb for “died”.'],
  ['“Kick the bucket” translated with an insulting Arabic phrase', 'The English is informal and humorous, not insulting.', 'Described as informal and humorous.'],
  ['A line stating that form is more important than meaning', 'Contradicts the draft’s own rule that meaning comes first.', 'Corrected.'],
  ['“She is a snake” given as a metaphor that is not shared by the two languages', 'The line before it says that the same metaphor exists in Arabic.', 'Replaced with an example that fits the rule (“the tip of the iceberg”).'],
  ['Collocations and a legal term listed as idioms', 'They are not idioms.', 'Moved to the collocation chapter and the term list.'],
  ['Blair described as Bush’s “puppy”', 'The word used in the British press was “poodle”.', 'Corrected.'],
  ['“Mark my words” translated as a promise, with a typing error', 'The phrase means “remember what I said”.', 'Corrected.'],
  ['Three Egyptian colloquial expressions used as equivalents for condolences, a welcome and an exclamation', 'Unsuitable register for a general handbook; one refers to the Prophet in a casual way.', 'Replaced with formal equivalents. Where a colloquial form is useful, it is labelled as colloquial.'],
  ['A suicide-bombing example that labels one translation as Islamic and another as un-Islamic', 'Takes a religious and political position.', 'Rewritten to teach the principle: the choice depends on the client’s policy.'],
  ['The statement that a named news agency has biased views', 'A published handbook should not describe a named organisation in this way.', 'Removed. The news-analysis example itself is kept.'],
  ['“Translation also means to politicize”', 'Wrong word; the intended idea (diplomatic wording) is not a definition of translation.', 'Removed.'],
  ['“Arabic is compositional, English is compounding”', 'An oversimplification: both languages use derivation and compounding.', 'Removed.'],
  ['“Mule” given as a negative synonym of “horse”', 'A mule is a different animal.', 'Removed.'],
  ['“Kick the chair” given as an English idiom', 'Not an established English idiom.', 'Removed.'],
  ['A number of fields attributed to the Jordanian academy', 'Could not be verified.', 'Removed.'],
  ['A proverb about death given with a Qur’anic verse as its equivalent', 'Using a sacred text as a translation equivalent is not appropriate in this context.', 'Removed.'],
  ['Invented words (tribocracy, puppycracy, patriocracy) used as examples of lexical creation', 'Not established words.', 'Removed; established examples are used instead.'],
  ['Arabic alternatives containing a typing error in the form and meaning section', 'Typing error.', 'Removed.'],
  ['Spelling errors in English words and phrases throughout the draft', 'Proofreading.', 'Corrected.']],
 [36, 32, 32]],
['p', 'Two Arabic equivalents were changed to the more common form. For “governing law”, the handbook gives the more common form and lists the draft’s form as an alternative. For “jet lag”, the handbook uses the more common form only. The team may prefer the draft’s forms (Section 12). The same Arabic form for “governing law” is now used in every chapter.'],
['h2', '7.2 Corrections to the terminology chapter and the audiovisual translation notes'],
['table', ['Item in the source', 'Problem', 'Action'],
 [['Spelling of the names Vermeer, Díaz Cintas and Remael, and of the term “explicitation”', 'Misspelled in the notes.', 'Corrected.'],
  ['Subtitles described as having 32 to 41 characters per line', 'Differs from the published standard.', 'Changed to about 37 to 39 characters, and up to 42 on streaming platforms, with at most two lines (Díaz Cintas & Remael, 2021).'],
  ['Dubbing described as used mainly in Europe, America and Asia', 'Incomplete for an Arab readership.', 'Rewritten: dubbing is common for cartoons, games and advertisements, and widely used in the Arab world for children’s programmes and series.'],
  ['A contrast between “informal” foreign culture and “formal” target culture', 'Unclear and not true in general.', 'Removed.'],
  ['Links to online video examples', 'Links can stop working in a printed book.', 'Removed. Current examples can be shown in workshops.'],
  ['Historical claims about the founding of terminology and figures about standardisation bodies', 'Partly inaccurate or likely to become outdated.', 'Checked and corrected, then removed in the beginner revision (Section 8.2).']],
 [36, 32, 32]],

['h1', '8. What was removed, and why'],
['h2', '8.1 Removed from the draft'],
['p', 'Besides the corrections in Section 7.1, the following draft material was not used. One further item was updated rather than removed: the draft’s note that Arabic avoids the feminine titles for a woman judge and a woman deputy now also states that these titles are widely used today.'],
['ul', [
  'Examples about a political scandal involving a named person, and an example about an intern. They were not needed to explain the point.',
  'Some examples in descriptive translation whose meaning is doubtful, or which belong to other fields (a Chinese philosophical term, and the difference between psychology and psychiatry).',
  'Some examples in lexical creation (co-wife, a religious legal term, and CD), left out for space.',
  'Unused items from exercises 16 and 24–29. Many items from these exercises are used in Chapters 7, 8 and 14. The rest could form an extra exercise set in a future edition.',
  'The line “Principles = Foundations” in the definitions section, whose meaning is unclear.',
]],
['h2', '8.2 Removed in the beginner revision'],
['p', 'After the instruction that the book is for beginners and should not go deeply into theory, the following were removed:'],
['ul', [
  'The communication model with its technical elements (Chapter 1). The idea that translation is communication is kept in simple words.',
  'The history of translation methods (Chapter 10) and the history of the Abbasid translators, apart from one sentence.',
  'A historical note on Schleiermacher (Chapter 13). Domestication and foreignisation are kept.',
  'The theory behind Fairclough’s model (Chapter 19). It is replaced by three practical questions, and the chapter is now called “Words and points of view”.',
  'From the terminology chapter (Chapter 21): the history of terminology, the list of standardisation bodies and the detailed procedures of the Arabic academies. What remains is what a translator needs to work with terms.',
  'From the audiovisual translation notes (Chapter 26): the history of the field and three of its four theories. One idea is kept, that the purpose of a translation guides its choices (Reiss & Vermeer, 1984).',
  'The two overlapping lists of subtitling strategies (Díaz Cintas and Remael; Pedersen). They were merged into one list of eight strategies.',
  'Key terms that a beginner does not need, and ten references that were no longer cited after these changes.',
]],
['h2', '8.3 Removed before publication'],
['ul', [
  'All placeholders in square brackets: the copyright holder, editors, ISBN, the empty checklist for Dr Abdullah’s framework, the list of references still to be added, and the notes asking for confirmation in the references and the practice texts. The acknowledgements were written in full.',
  'The names of the supervisor and Dr Amin from the acknowledgements. The notes mention them only as future reviewers, so they are not thanked for feedback they have not yet given.',
  'All mentions of the Guild Season, from the preface, the copyright page and the back cover, because the handbook may also be given as a gift outside the workshops.',
  'The subtitle lines and the label “A beginner’s guide” from the front cover, at the team’s request.',
]],

['h1', '9. What was added'],
['table', ['Addition', 'Where', 'Reason or source'],
 [['Front matter: copyright page, preface, acknowledgements, how to use the handbook, abbreviations', 'Front', 'Needed for a published book. The preface uses the objectives from the draft.'],
  ['Key terms, “Try it” exercises and “Remember” summaries', 'Every chapter', 'The notes ask for definitions in every chapter. The exercises and summaries help beginners check their understanding.'],
  ['Chapters that had no content in the draft', 'Chapters 12, 18–24', 'The seven procedures, genres, words and points of view, dictionaries, terminology, machine translation and AI, revision and common mistakes, and the risk matrix, all requested in the notes.'],
  ['Added strategies and types of translation', 'Chapters 1 and 13', 'Requested in the notes (see Section 5).'],
  ['A worked first translation', 'Chapter 2', 'Shows the whole process on one sentence, so that beginners see how the chapters connect.'],
  ['Additional differences between English and Arabic', 'Chapter 3', 'Gender of “you”, numbers from three to ten, linking words and punctuation, which are common problems for beginners.'],
  ['Explanations for the audiovisual translation notes', 'Part 9', 'The notes were in short point form. Full explanations were written for each point that was kept.'],
  ['Quotations and definitions from published works', 'Throughout', 'To give beginners recognised definitions and to credit the ideas in the draft. The citations for the draft’s ideas match them to standard published sources; they are not the draft’s original sources, which are unknown.'],
  ['Additional examples', 'Various chapters', 'Where the draft had no example or an unsuitable one. Each added example is either cited or was written for the handbook.'],
  ['Practice section, answer key, four checklists, glossary and references', 'Back matter', 'Requested in the notes.'],
  ['Future editions', 'Back matter', 'Requested in the notes (paragraph 38).']],
 [30, 18, 52]],

['h1', '10. Design and production'],
['h2', '10.1 Layout inside the book'],
['ul', [
  'White pages with dark text. Headings are in a serif typeface and the body text in a sans-serif typeface. Arabic is set right to left in an Arabic typeface.',
  'One shaded box style is used, for key terms and for chapter summaries. There are no images inside the book.',
  'The layout follows the conventions of academic coursebooks: roman page numbers for the front matter, arabic numbers from Part 1, a running head on every main page, and each chapter starting on a new page.',
  'The contents page is generated automatically from the headings and updates in Word.',
]],
['h2', '10.2 The logo'],
['p', 'Earlier versions showed the Guild name as typed text with the three dots in a row. This did not match the logo, in which the dots are stacked vertically beside the letter “d” and the wordmark uses its own typeface. The wordmark is now taken directly from the club’s logo file, with the three dots redrawn in the logo’s exact colours. It appears on the title page and on both covers.'],
['h2', '10.3 The covers'],
['p', 'The covers follow the practice of academic publishers such as Routledge for translation coursebooks: a single strong colour field, large title type, the publisher’s mark in a band, and a back cover with a short description and a list of key features. Six complete designs were prepared. The team chose two, which became the two editions:'],
['ul', [
  '**Midnight edition:** a dark indigo cover with three stripes in the logo’s colours along the spine edge and the logo in white.',
  '**Light edition:** a pale lavender cover with three large circles in the logo’s colours and the titles in dark purple.',
]],
['p', 'Both front covers show only the English title “Translation Handbook”, the Arabic title {{دليل الترجمة}}, the logo, and “First edition 2026”. Both back covers carry the quotation “Words travel worlds. Translators do the driving.” by the translator Anna Rusconi, a one-sentence description, three key features and the logo. The middle of the back cover is left free for the QR code of the team’s website.'],
['h2', '10.4 Production'],
['ul', [
  'The handbook was organised, drafted, edited and laid out with the help of an AI tool (Claude, by Anthropic), under the direction of the Translation Team, and reviewed by the team. This is stated on the copyright page.',
  'The Word files and the PDFs are produced from the same source, so the two formats have the same content. The PDFs embed their fonts.',
  'The layout was checked in LibreOffice. It should also be checked once in Microsoft Word before printing (Section 12).',
]],

['h1', '11. Checking of quotations and references'],
['p', 'The quotations and references were checked against published information found through web searches. The full texts of the books could not be opened, so this check does not replace checking the printed books. “Confirmed” means that independent sources agreed on the wording, the page or the publication details. Items that were later removed from the handbook are not listed.'],
['table', ['Item', 'Result', 'Action taken'],
 [['Newmark (1988, p. 5): definition of translation', 'Confirmed', 'None needed.'],
  ['Newmark (1988): reading the original for two purposes', 'Wording confirmed; page not confirmed', 'Cited by chapter (Chapter 2) instead of page.'],
  ['Newmark (1988, p. 81): methods and procedures', 'Confirmed', 'None needed.'],
  ['Nida and Taber (1969, p. 12): “the closest natural equivalent”', 'Confirmed', 'None needed.'],
  ['Nida and Taber (1969, p. 4): a sentence on what can be said in any language', 'Not confirmed word for word', 'Changed from a quotation to a paraphrase.'],
  ['Jakobson (1959, p. 236)', 'Confirmed', 'None needed.'],
  ['Firth (1957, p. 11): “You shall know a word by the company it keeps”', 'Confirmed', 'None needed.'],
  ['Jerome, Letter 57: “sense for sense”', 'Confirmed', 'Cited from The Translation Studies Reader (2012).'],
  ['Samuel Johnson on dictionaries', 'Source corrected', 'The source is Johnson’s letter to Francesco Sastres (1784), in Johnsonian Miscellanies (1897), not the work previously given.'],
  ['al-Jāḥiẓ, Kitāb al-Ḥayawān: the passage on the translator', 'Wording confirmed; page not confirmed', 'Cited to Hārūn’s edition (1965, vol. 1) without a page number. Secondary sources give page 76.'],
  ['Baker and Hanna (2009): the Abbasid translators', 'Confirmed', 'None needed.'],
  ['Farghal and Shunnaq (1999): formal, functional and ideational equivalence', 'Confirmed', 'Publisher corrected to Dar Al-Hilal for Translation.'],
  ['Fairclough (1992): language as social practice', 'Not confirmed word for word', 'Changed from a quotation to a paraphrase.'],
  ['Nord (1997): “function plus loyalty”', 'Confirmed', 'None needed.'],
  ['Baker (2018): strategies for non-equivalence', 'Confirmed', 'None needed.'],
  ['Arabterm', 'Details corrected', 'Credited to ALECSO with GIZ.'],
  ['Díaz Cintas and Remael (2007, 2021); Pedersen (2011); Pérez-González (2014); Reiss and Vermeer (1984)', 'Confirmed', 'Publication details completed.'],
  ['Gambier (2003)', 'Confirmed through secondary sources; page not checked', 'Cited without a page number.'],
  ['Subtitle line length (Díaz Cintas & Remael, 2021)', 'Corrected', 'See Section 7.2.'],
  ['Anna Rusconi: “Words travel worlds. Translators do the driving.”', 'Attribution confirmed; original publication not found', 'Used on the back cover with her name only, as is usual for a cover epigraph. It is not listed in the references.'],
  ['All other references (Cabré, Dickins et al., Eco, Ghazala, Kenny, Mossop, Nord 2005, Pym, Reiss, Venuti, Vinay and Darbelnet, Wehr, and the dictionaries)', 'Confirmed', 'Minor details completed.']],
 [36, 28, 36]],
['p', 'Every work in the reference list is cited in the text, and every citation in the text appears in the reference list.'],

['h1', '12. Items to complete before publication'],
['h2', '12.1 Required'],
['ol', [
  'Have a qualified Arabic–English translator proofread all Arabic in the handbook.',
  'Check the quotations against the printed books, especially the two items without page numbers (al-Jāḥiẓ and Gambier) and the paraphrases in Section 11.',
  'Confirm the sources of the draft’s own examples. The notes say that the material was collected from more than one source. The examples are credited to the team’s course materials; if any come from a published book, such as the 180 or 182 books, that book must be credited instead.',
  'Confirm the copyright line (© 2026 Guild Professional Club, Translation Team) and the club’s official name.',
  'Confirm that the statement on AI assistance on the copyright page meets the university’s and the publisher’s rules.',
  'Add the QR code of the team’s website to the back cover of the chosen edition or editions.',
  'Open the Word file in Microsoft Word, update the contents page, and check the layout before printing.',
]],
['h2', '12.2 Decisions for the team'],
['ol', [
  '**Title.** The working English title is “Translation Handbook”. “Translator’s Equipment” has been suggested as an alternative.',
  '**Edition.** Whether to publish one edition or both.',
  '**Dr Yusuf and {{الترجمة: ماهيتها}}.** The notes attribute this text to Dr Yusuf, but the team has said there is no Dr Yusuf. The text and its author need to be confirmed before it can be used and cited.',
  '**Dr Abdullah’s framework.** A checklist based on it can be added once the framework is received.',
  '**Authentic news texts.** Whether to replace the two news texts written for the handbook with published articles, which requires the publishers’ permission.',
  '**Materials not yet received.** Whether to add material from the 180, 182, 386 and Analysis texts, “the book”, Loulwah’s notes and the other contributions listed in Section 3.2 to this edition or to a later one.',
  '**Fairclough.** Whether the three practical questions in Chapter 19 and Checklist 3 are enough for what the professor intends by the relational model.',
  '**Arabic forms and dialect.** Which of the two forms to use for “governing law” and “jet lag”, and whether to keep the few colloquial expressions, which are labelled as colloquial, or to use only formal Arabic.',
  '**Free translation.** Chapter 10 presents three of the draft’s free-translation examples as very free and notes that some specialists regard such adaptations as new texts. The team should confirm this presentation.',
]],

];
